card_to_pack = {
    "Aerodactyl": ["Aerodactyl Pack"],
    "Mysterious Fossil": ["Aerodactyl Pack", "Kabutops Pack", "Omastar Pack"],
    "Alakazam": ["Alakazam Pack"],
    "Kadabra": ["Alakazam Pack"],
    "Abra": ["Alakazam Pack"],
    "Arbok": ["Arbok Pack"],
    "Ekans": ["Arbok Pack"],
    "Arcanine Lv34": ["Arcanine 1 Pack"],
    "Growlithe": ["Arcanine 1 Pack", "Arcanine 2 Pack"],
    "Arcanine Lv45": ["Arcanine 2 Pack"],
    "Articuno Lv35": ["Articuno 1 Pack"],
    "Articuno Lv37": ["Articuno 2 Pack"],
    "Beedrill": ["Beedrill Pack"],
    "Kakuna": ["Beedrill Pack"],
    "Weedle": ["Beedrill Pack"],
    "Blastoise": ["Blastoise Pack"],
    "Wartortle": ["Blastoise Pack"],
    "Squirtle": ["Blastoise Pack"],
    "Butterfree": ["Butterfree Pack"],
    "Metapod": ["Butterfree Pack"],
    "Caterpie": ["Butterfree Pack"],
    "Chansey": ["Chansey Pack"],
    "Charizard": ["Charizard Pack"],
    "Charmeleon": ["Charizard Pack"],
    "Charmander": ["Charizard Pack"],
    "Clefable": ["Clefable Pack"],
    "Clefairy": ["Clefable Pack"],
    "Cloyster": ["Cloyster Pack"],
    "Shellder": ["Cloyster Pack"],
    "Dewgong": ["Dewgong Pack"],
    "Seel": ["Dewgong Pack"],
    "Ditto": ["Ditto Pack"],
    "Dodrio": ["Dodrio Pack"],
    "Doduo": ["Dodrio Pack"],
    "Dragonite Lv41": ["Dragonite 1 Pack"],
    "Dragonair": ["Dragonite 1 Pack", "Dragonite 2 Pack"],
    "Dratini": ["Dragonite 1 Pack", "Dragonite 2 Pack"],
    "Dragonite Lv45": ["Dragonite 2 Pack"],
    "Dugtrio": ["Dugtrio Pack"],
    "Diglett": ["Dugtrio Pack"],
    "Electabuzz Lv20": ["Electabuzz 1 Pack"],
    "Electabuzz Lv35": ["Electabuzz 2 Pack"],
    "Electrode Lv35": ["Electrode 1 Pack"],
    "Voltorb": ["Electrode 1 Pack", "Electrode 2 Pack"],
    "Electrode Lv42": ["Electrode 2 Pack"],
    "Exeggutor": ["Exeggutor Pack"],
    "Exeggcute": ["Exeggutor Pack"],
    "Farfetchd": ["Farfetchd Pack"],
    "Fearow": ["Fearow Pack"],
    "Spearow": ["Fearow Pack"],
    "Flareon Lv22": ["Flareon 1 Pack"],
    "Eevee": ["Flareon 1 Pack", "Flareon 2 Pack", "Jolteon 1 Pack", "Jolteon 2 Pack", "Vaporeon 1 Pack",
              "Vaporeon 2 Pack"],
    "Flareon Lv28": ["Flareon 2 Pack"],
    "Flying Pikachu": ["Flying Pikachu Pack"],
    "Gengar": ["Gengar 1 Pack", "Gengar 2 Pack"],
    "Haunter Lv22": ["Gengar 1 Pack"],
    "Gastly Lv8": ["Gengar 1 Pack"],
    "Haunter Lv17": ["Gengar 2 Pack"],
    "Gastly Lv17": ["Gengar 2 Pack"],
    "Golbat": ["Golbat Pack"],
    "Zubat": ["Golbat Pack"],
    "Golduck": ["Golduck Pack"],
    "Psyduck": ["Golduck Pack"],
    "Golem": ["Golem Pack"],
    "Graveler": ["Golem Pack"],
    "Geodude": ["Golem Pack"],
    "Gyarados": ["Gyrados Pack"],
    "Magikarp": ["Gyrados Pack"],
    "Hitmonchan": ["Hitmonchan Pack"],
    "Hitmonlee": ["Hitmonlee Pack"],
    "Hypno": ["Hypno Pack"],
    "Drowzee": ["Hypno Pack"],
    "Jigglypuff Lv12": ["Jigglypuff Promo Pack"],
    "Jolteon Lv24": ["Jolteon 1 Pack"],
    "Jolteon Lv29": ["Jolteon 2 Pack"],
    "Jynx": ["Jynx Pack"],
    "Kabutops": ["Kabutops Pack"],
    "Kabuto": ["Kabutops Pack"],
    "Kangaskhan": ["Kangaskhan Pack"],
    "Kingler": ["Kingler Pack"],
    "Krabby": ["Kingler Pack"],
    "Lapras": ["Lapras Pack"],
    "Lickitung": ["Lickitung Pack"],
    "Machamp": ["Machamp Pack"],
    "Machoke": ["Machamp Pack"],
    "Machop": ["Machamp Pack"],
    "Magmar Lv24": ["Magmar 1 Pack"],
    "Magmar Lv31": ["Magmar 2 Pack"],
    "Magneton Lv28": ["Magneton 1 Pack"],
    "Magnemite Lv13": ["Magneton 1 Pack"],
    "Magneton Lv35": ["Magneton 2 Pack"],
    "Magnemite Lv15": ["Magneton 2 Pack"],
    "Marowak Lv26": ["Marowak 1 Pack"],
    "Cubone": ["Marowak 1 Pack", "Marowak 2 Pack"],
    "Marowak Lv32": ["Marowak 2 Pack"],
    "Mew Lv8": ["Mew 1 Pack"],
    "Mew Lv15": ["Mew 2 Pack"],
    "Mew Lv23": ["Mew 3 Pack"],
    "Mewtwo Lv53": ["Mewtwo 1 Pack"],
    "Mewtwo Lv60": ["Mewtwo 2 Pack"],
    "Mewtwo Alt Lv60": ["Mewtwo 3 Pack"],
    "Moltres Lv35": ["Moltres 1 Pack"],
    "Moltres Lv37": ["Moltres 2 Pack"],
    "Mr Mime": ["Mr Mime Pack"],
    "Muk": ["Muk Pack"],
    "Grimer": ["Muk Pack"],
    "Nidoking": ["Nidoking Pack"],
    "Nidorino": ["Nidoking Pack"],
    "Nidoranm": ["Nidoking Pack"],
    "Nidoqueen": ["Nidoqueen Pack"],
    "Nidorina": ["Nidoqueen Pack"],
    "Nidoranf": ["Nidoqueen Pack"],
    "Ninetales Lv32": ["Ninetales 1 Pack"],
    "Vulpix": ["Ninetales 1 Pack", "Ninetales 2 Pack"],
    "Ninetales Lv35": ["Ninetales 2 Pack"],
    "Omastar": ["Omastar Pack"],
    "Omanyte": ["Omastar Pack"],
    "Onix": ["Onix Pack"],
    "Parasect": ["Parasect Pack"],
    "Paras": ["Parasect Pack"],
    "Persian": ["Persian 1 Pack", "Persian 2 Pack"],
    "Meowth Lv14": ["Persian 1 Pack"],
    "Meowth Lv15": ["Persian 2 Pack"],
    "Pidgeot Lv38": ["Pidgeot 1 Pack"],
    "Pidgeotto": ["Pidgeot 1 Pack", "Pidgeot 2 Pack"],
    "Pidgey": ["Pidgeot 1 Pack", "Pidgeot 2 Pack"],
    "Pidgeot Lv40": ["Pidgeot 2 Pack"],
    "Pinsir": ["Pinsir Pack"],
    "Poliwrath": ["Poliwrath Pack"],
    "Poliwhirl": ["Poliwrath Pack"],
    "Poliwag": ["Poliwrath Pack"],
    "Porygon": ["Porygon"],
    "Primeape": ["Primeape Pack"],
    "Mankey": ["Primeape Pack"],
    "Raichu Lv40": ["Raichu 1 Pack", "Raichu 3 Pack"],
    "Pikachu Lv12": ["Raichu 1 Pack"],
    "Raichu Lv45": ["Raichu 2 Pack", "Raichu 4 Pack"],
    "Pikachu Lv14": ["Raichu 2 Pack"],
    "Pikachu Lv16": ["Raichu 3 Pack"],
    "Pikachu Alt Lv16": ["Raichu 4 Pack"],
    "Rapidash": ["Rapidash Pack"],
    "Ponyta": ["Rapidash Pack"],
    "Raticate": ["Raticate Pack"],
    "Rattata": ["Raticate Pack"],
    "Rhydon": ["Rhydon Pack"],
    "Rhyhorn": ["Rhydon Pack"],
    "Sandslash": ["Sandslash Pack"],
    "Sandshrew": ["Sandslash Pack"],
    "Scyther": ["Scyther Pack"],
    "Seadra": ["Seadra Pack"],
    "Horsea": ["Seadra Pack"],
    "Seaking": ["Seaking Pack"],
    "Goldeen": ["Seaking Pack"],
    "Slowbro": ["Slowbro Pack"],
    "Slowpoke Lv18": ["Slowbro Pack"],
    "Slowpoke Lv9": ["Slowpoke Promo Pack"],
    "Snorlax": ["Snorlax Pack"],
    "Starmie": ["Starmie Pack"],
    "Staryu": ["Starmie Pack"],
    "Surfing Pikachu Lv13": ["Surfing Pikachu 1 Pack"],
    "Surfing Pikachu Alt Lv13": ["Surfing Pikachu 2 Pack"],
    "Tangela Lv12": ["Tangela 1 Pack"],
    "Tangela Lv8": ["Tangela 1 Pack"],
    "Tauros": ["Tauros Pack"],
    "Tentacruel": ["Tentacruel Pack"],
    "Tentacool": ["Tentacruel Pack"],
    "Vaporeon Lv29": ["Vaporeon 1 Pack"],
    "Vaporeon Lv42": ["Vaporeon 2 Pack"],
    "Venomoth": ["Venomoth Pack"],
    "Venonat": ["Venomoth Pack"],
    "Venusaur Lv64": ["Venusaur 1 Pack"],
    "Ivysaur": ["Venusaur 1 Pack", "Venusaur 2 Pack"],
    "Bulbasaur": ["Venusaur 1 Pack", "Venusaur 2 Pack"],
    "Venusaur Lv67": ["Venusaur 2 Pack"],
    "Victreebel": ["Victreebel Pack"],
    "Weepinbell": ["Victreebel Pack"],
    "Bellsprout": ["Victreebel Pack"],
    "Vileplume": ["Vileplume Pack"],
    "Gloom": ["Vileplume Pack"],
    "Oddish": ["Vileplume Pack"],
    "Weezing": ["Weezing Pack"],
    "Koffing": ["Weezing Pack"],
    "Wigglytuff": ["Wigglytuff 1 Pack", "Wigglytuff 2 Pack"],
    "Jigglypuff Lv13": ["Wigglytuff 1 Pack"],
    "Jigglypuff Lv14": ["Wigglytuff 2 Pack"],
    "Zapdos Lv40": ["Zapdos 1 Pack"],
    "Zapdos Lv64": ["Zapdos 2 Pack"],
    "Zapdos Lv68": ["Zapdos 3 Pack"],

    "Clefairy Doll": ["Clefairy Doll Pack"],
    "Defender": ["Defender Pack"],
    "Devolution Spray": ["Devolution Spray Pack"],
    "Energy Removal": ["Energy Removal Pack"],
    "Energy Retrieval": ["Energy Retrieval Pack"],
    "Energy Search": ["Energy Search Pack"],
    "Full Heal": ["Full Heal Pack"],
    "Gambler": ["Gambler Pack"],
    "Imakuni Card": ["Imakuni? Pack"],
    "Imposter Professor Oak": ["Imposter Professor Oak Pack"],
    "Item Finder": ["Item Finder Pack"],
    "Lass": ["Lass Pack"],
    "Maintenance": ["Maintenance Pack"],
    "Mr Fuji": ["Mr Fuji Pack"],
    "Poke Ball": ["Poke Ball Pack"],
    "Pokedex": ["Pokedex Pack"],
    "Pokemon Breeder": ["Pokemon Breeder Pack"],
    "Pokemon Center": ["Pokemon Center Pack"],
    "Pokemon Flute": ["Pokemon Flute Pack"],
    "Pokemon Trader": ["Pokemon Trader Pack"],
    "Potion": ["Potion Pack"],
    "Recycle": ["Recycle Pack"],
    "Revive": ["Revive Pack"],
    "Scoop Up": ["Scoop Up Pack"],
    "Super Energy Retrieval": ["Super Energy Retrieval Pack"],
    "Super Potion": ["Super Potion Pack"],
    "Switch": ["Switch Pack"],

    "Computer Search": ["Computer Search Pack"],
    "Gust  of Wind": ["Gust  of Wind Pack"],
    "Pluspower": ["Pluspower Pack"],

    "Bill": ["Bill Pack"],
    "Professor Oak": ["Professor Oak Pack"],
    "Super Energy Removal": ["Super Energy Removal Pack"],
    "Double Colorless Energy": ["Double Colorless Energy Pack"],
    "Water Energy": ["Starting Deck"],
    "Fire Energy": ["Starting Deck"],
    "Grass Energy": ["Starting Deck"],
    "Lightning Energy": ["Starting Deck"],
    "Fighting Energy": ["Starting Deck"],
    "Psychic Energy": ["Starting Deck"]
}

pack_to_card = {
    "Aerodactyl Pack": {"Aerodactyl": 4, "Mysterious Fossil": 4},
    "Dugtrio Pack": {"Dugtrio": 4, "Diglett": 4},
    "Golem Pack": {"Golem": 4, "Graveler": 4, "Geodude": 4},
    "Hitmonchan Pack": {"Hitmonchan": 4},
    "Hitmonlee Pack": {"Hitmonlee": 4},
    "Kabutops Pack": {"Kabutops": 4, "Kabuto": 4, "Mysterious Fossil": 4},
    "Machamp Pack": {"Machamp": 4, "Machoke": 4, "Machop": 4},
    "Marowak 1 Pack": {"Marowak Lv26": 4, "Cubone": 4},
    "Marowak 2 Pack": {"Marowak Lv32": 4, "Cubone": 4},
    "Onix Pack": {"Onix": 4},
    "Primeape Pack": {"Primeape": 4, "Mankey": 4},
    "Rhydon Pack": {"Rhydon": 4, "Rhyhorn": 4},
    "Sandslash Pack": {"Sandslash": 4, "Sandshrew": 4},

    "Alakazam Pack": {"Alakazam": 4, "Kadabra": 4, "Abra": 4},
    "Gengar 1 Pack": {"Gengar": 4, "Haunter Lv22": 4, "Gastly Lv8": 4},
    "Gengar 2 Pack": {"Gengar": 4, "Haunter Lv17": 4, "Gastly Lv17": 4},
    "Hypno Pack": {"Hypno": 4, "Drowzee": 4},
    "Jynx Pack": {"Jynx": 4},
    "Mew 1 Pack": {"Mew Lv8": 4},
    "Mew 2 Pack": {"Mew Lv15": 4},
    "Mew 3 Pack": {"Mew Lv23": 4},
    "Mewtwo 1 Pack": {"Mewtwo Lv53": 4},
    "Mewtwo 2 Pack": {"Mewtwo Lv60": 4},
    "Mewtwo 3 Pack": {"Mewtwo Alt Lv60": 4},
    "Mr Mime Pack": {"Mr Mime": 4},

    "Arbok Pack": {"Arbok": 4, "Ekans": 4},
    "Beedrill Pack": {"Beedrill": 4, "Kakuna": 4, "Weedle": 4},
    "Butterfree Pack": {"Butterfree": 4, "Metapod": 4, "Caterpie": 4},
    "Exeggutor Pack": {"Exeggutor": 4, "Exeggcute": 4},
    "Golbat Pack": {"Golbat": 4, "Zubat": 4},
    "Muk Pack": {"Muk": 4, "Grimer": 4},
    "Nidoking Pack": {"Nidoking": 4, "Nidorino": 4, "Nidoranm": 4},
    "Nidoqueen Pack": {"Nidoqueen": 4, "Nidorina": 4, "Nidoranf": 4},
    "Parasect Pack": {"Parasect": 4, "Paras": 4},
    "Pinsir Pack": {"Pinsir": 4},
    "Scyther Pack": {"Scyther": 4},
    "Tangela 1 Pack": {"Tangela Lv12": 4},
    "Tangela 2 Pack": {"Tangela Lv8": 4},
    "Venomoth Pack": {"Venomoth": 4, "Venonat": 4},
    "Venusaur 1 Pack": {"Venusaur Lv64": 4, "Ivysaur": 4, "Bulbasaur": 4},
    "Venusaur 2 Pack": {"Venusaur Lv67": 4, "Ivysaur": 4, "Bulbasaur": 4},
    "Victreebel Pack": {"Victreebel": 4, "Weepinbell": 4, "Bellsprout": 4},
    "Vileplume Pack": {"Vileplume": 4, "Gloom": 4, "Oddish": 4},
    "Weezing Pack": {"Weezing": 4, "Koffing": 4},

    "Arcanine 1 Pack": {"Arcanine Lv34": 4, "Growlithe": 4},
    "Arcanine 2 Pack": {"Arcanine Lv45": 4, "Growlithe": 4},
    "Charizard Pack": {"Charizard": 4, "Charmeleon": 4, "Charmander": 4},
    "Flareon 1 Pack": {"Flareon Lv22": 4, "Eevee": 4},
    "Flareon 2 Pack": {"Flareon Lv28": 4, "Eevee": 4},
    "Magmar 1 Pack": {"Magmar Lv24": 4},
    "Magmar 2 Pack": {"Magmar Lv31": 4},
    "Moltres 1 Pack": {"Moltres Lv35": 4},
    "Moltres 2 Pack": {"Moltres Lv37": 4},
    "Ninetales 1 Pack": {"Ninetales Lv32": 4, "Vulpix": 4},
    "Ninetales 2 Pack": {"Ninetales Lv35": 4, "Vulpix": 4},
    "Rapidash Pack": {"Rapidash": 4, "Ponyta": 4},

    "Articuno 1 Pack": {"Articuno Lv35": 4},
    "Articuno 2 Pack": {"Articuno Lv37": 4},
    "Blastoise Pack": {"Blastoise": 4, "Wartortle": 4, "Squirtle": 4},
    "Cloyster Pack": {"Cloyster": 4, "Shellder": 4},
    "Dewgong Pack": {"Dewgong": 4, "Seel": 4},
    "Golduck Pack": {"Golduck": 4, "Psyduck": 4},
    "Gyrados Pack": {"Gyarados": 4, "Magikarp": 4},
    "Kingler Pack": {"Kingler": 4, "Krabby": 4},
    "Lapras Pack": {"Lapras": 4},
    "Omastar Pack": {"Omastar": 4, "Omanyte": 4, "Mysterious Fossil": 4},
    "Poliwrath Pack": {"Poliwrath": 4, "Poliwhirl": 4, "Poliwag": 4},
    "Seadra Pack": {"Seadra": 4, "Horsea": 4},
    "Seaking Pack": {"Seaking": 4, "Goldeen": 4},
    "Slowbro Pack": {"Slowbro": 4, "Slowpoke Lv18": 4},
    "Slowpoke Promo Pack": {"Slowpoke Lv9": 4},
    "Starmie Pack": {"Starmie": 4, "Staryu": 4},
    "Tentacruel Pack": {"Tentacruel": 4, "Tentacool": 4},
    "Vaporeon 1 Pack": {"Vaporeon Lv29": 4, "Eevee": 4},
    "Vaporeon 2 Pack": {"Vaporeon Lv42": 4, "Eevee": 4},

    "Electabuzz 1 Pack": {"Electabuzz Lv20": 4},
    "Electabuzz 2 Pack": {"Electabuzz Lv35": 4},
    "Electrode 1 Pack": {"Electrode Lv35": 4, "Voltorb": 4},
    "Electrode 2 Pack": {"Electrode Lv42": 4, "Voltorb": 4},
    "Flying Pikachu Pack": {"Flying Pikachu": 4},
    "Jolteon 1 Pack": {"Jolteon Lv24": 4, "Eevee": 4},
    "Jolteon 2 Pack": {"Jolteon Lv29": 4, "Eevee": 4},
    "Magneton 1 Pack": {"Magneton Lv28": 4, "Magnemite Lv13": 4},
    "Magneton 2 Pack": {"Magneton Lv35": 4, "Magnemite Lv15": 4},
    "Raichu 1 Pack": {"Raichu Lv40": 4, "Pikachu Lv12": 4},
    "Raichu 2 Pack": {"Raichu Lv45": 4, "Pikachu Lv14": 4},
    "Raichu 3 Pack": {"Raichu Lv40": 4, "Pikachu Lv16": 4},
    "Raichu 4 Pack": {"Raichu Lv45": 4, "Pikachu Alt Lv16": 4},
    "Surfing Pikachu 1 Pack": {"Surfing Pikachu Lv13": 4},
    "Surfing Pikachu 2 Pack": {"Surfing Pikachu Alt Lv13": 4},
    "Zapdos 1 Pack": {"Zapdos Lv40": 4},
    "Zapdos 2 Pack": {"Zapdos Lv64": 4},
    "Zapdos 3 Pack": {"Zapdos Lv68": 4},

    "Chansey Pack": {"Chansey": 4},
    "Clefable Pack": {"Clefable": 4, "Clefairy": 4},
    "Ditto Pack": {"Ditto": 4},
    "Dodrio Pack": {"Dodrio": 4, "Doduo": 4},
    "Dragonite 1 Pack": {"Dragonite Lv41": 4, "Dragonair": 4, "Dratini": 4},
    "Dragonite 2 Pack": {"Dragonite Lv45": 4, "Dragonair": 4, "Dratini": 4},
    "Farfetch'd Pack": {"Farfetchd": 4},
    "Fearow Pack": {"Fearow": 4, "Spearow": 4},
    "Jigglypuff Promo Pack": {"Jigglypuff Lv12": 4},
    "Kangaskhan Pack": {"Kangaskhan": 4},
    "Lickitung Pack": {"Lickitung": 4},
    "Persian 1 Pack": {"Persian": 4, "Meowth Lv14": 4},
    "Persian 2 Pack": {"Persian": 4, "Meowth Lv15": 4},
    "Pidgeot 1 Pack": {"Pidgeot Lv38": 4, "Pidgeotto": 4, "Pidgey": 4},
    "Pidgeot 2 Pack": {"Pidgeot Lv40": 4, "Pidgeotto": 4, "Pidgey": 4},
    "Porygon Pack": {"Porygon": 4},
    "Raticate Pack": {"Raticate": 4, "Rattata": 4},
    "Snorlax Pack": {"Snorlax": 4},
    "Tauros Pack": {"Tauros": 4},
    "Wigglytuff 1 Pack": {"Wigglytuff": 4, "Jigglypuff Lv13": 4},
    "Wigglytuff 2 Pack": {"Wigglytuff": 4, "Jigglypuff Lv14": 4},

    "Clefairy Doll Pack": {"Clefairy Doll": 4},
    "Defender Pack": {"Defender": 4},
    "Devolution Spray Pack": {"Devolution Spray": 4},
    "Energy Removal Pack": {"Energy Removal": 4},
    "Energy Retrieval Pack": {"Energy Retrieval": 4},
    "Energy Search Pack": {"Energy Search": 4},
    "Full Heal Pack": {"Full Heal": 4},
    "Gambler Pack": {"Gambler": 4},
    "Imakuni? Pack": {"Imakuni Card": 4},
    "Imposter Professor Oak Pack": {"Imposter Professor Oak": 4},
    "Item Finder Pack": {"Item Finder": 4},
    "Lass Pack": {"Lass": 4},
    "Maintenance Pack": {"Maintenance": 4},
    "Mr Fuji Pack": {"Mr Fuji": 4},
    "Poke Ball Pack": {"Poke Ball": 4},
    "Pokedex Pack": {"Pokedex": 4},
    "Pokemon Breeder Pack": {"Pokemon Breeder": 4},
    "Pokemon Center Pack": {"Pokemon Center": 4},
    "Pokemon Flute Pack": {"Pokemon Flute": 4},
    "Pokemon Trader Pack": {"Pokemon Trader": 4},
    "Potion Pack": {"Potion": 4},
    "Recycle Pack": {"Recycle": 4},
    "Revive Pack": {"Revive": 4},
    "Super Energy Retrieval Pack": {"Super Energy Retrieval": 4},
    "Super Potion Pack": {"Super Potion": 4},
    "Switch Pack": {"Switch": 4},

    "Computer Search Pack": {"Computer Search": 2},
    "Gust of Wind Pack": {"Gust of Wind": 2},
    "Pluspower Pack": {"Pluspower": 2},

    "Bill Pack": {"Bill": 1},
    "Professor Oak Pack": {"Professor Oak": 1},
    "Super Energy Removal Pack": {"Super Energy Removal": 1},
    "Double Colorless Energy Pack": {"Double Colorless Energy": 1},

    "Energy Pack": {"Water Energy": 10, "Fire Energy": 10, "Lightning Energy": 10, "Grass Energy": 10, "Psychic Energy": 10, "Fighting Energy": 10},
}

#20 cards
primary = {
    "Water": [
        {"Squirtle": 4, "Wartortle": 3, "Blastoise": 2, "Articuno Lv35": 1, "Water Energy": 10},
        {"Poliwag": 4, "Poliwhirl": 3, "Poliwrath": 2, "Lapras": 1, "Water Energy": 10},
        {"Seel": 3, "Dewgong": 2, "Horsea": 3, "Seadra": 2, "Water Energy": 10},
        {"Magikarp": 3, "Gyarados": 2, "Krabby": 3, "Kingler": 2, "Water Energy": 10}
    ],
    "Grass": [
        {"Nidoranm": 4, "Nidorino": 3, "Nidoking": 2, "Pinsir": 1, "Grass Energy": 10},
        {"Bulbasaur": 4, "Ivysaur": 3, "Venusaur Lv64": 2, "Tangela Lv8": 1, "Grass Energy": 10},
        {"Caterpie": 4, "Metapod": 3, "Butterfree": 2, "Pinsir": 1, "Grass Energy": 10},
        {"Oddish": 4, "Gloom": 3, "Vileplume": 2, "Tangela Lv12": 1, "Grass Energy": 10},
        {"Grimer": 3, "Muk": 2, "Koffing": 3, "Weezing": 2}
    ],
    "Fire": [
        {"Charmander": 4, "Charmeleon": 3, "Charizard": 2, "Moltres Lv35": 1, "Fire Energy": 10},
        {"Vulpix": 3, "Ninetales Lv32": 2, "Growlithe": 3, "Arcanine Lv45": 2, "Fire Energy": 10}
    ],
    "Fighting": [
        {"Machop": 4, "Machoke": 3, "Machamp": 2, "Hitmonlee": 1, "Fighting Energy": 10},
        {"Geodude": 4, "Graveler": 3, "Golem": 2, "Onix": 1, "Fighting Energy": 10},
        {"Diglett": 3, "Dugtrio": 2, "Rhyhorn": 3, "Rhydon": 2, "Fighting Energy": 10},
    ],
    "Psychic": [
        {"Abra": 4, "Kadabra": 3, "Alakazam": 2, "Mewtwo Alt Lv60": 1, "Psychic Energy": 10},
        {"Abra": 4, "Kadabra": 3, "Alakazam": 2, "Mewtwo Lv60": 1, "Psychic Energy": 10},
        {"Gastly Lv17": 4, "Haunter Lv22": 3, "Gengar": 2, "Mewtwo Alt Lv60": 1, "Psychic Energy": 10},
        {"Gastly Lv8": 4, "Haunter Lv17": 3, "Gengar": 2, "Mewtwo Lv60": 1, "Psychic Energy": 10}
    ],
    "Lightning": [
        {"Pikachu Lv12": 3, "Raichu Lv40": 2, "Magnemite Lv13": 3, "Magneton Lv28": 2, "Lightning Energy": 10},
        {"Pikachu Lv14": 3, "Raichu Lv45": 2, "Magnemite Lv15": 3, "Magneton Lv35": 2, "Lightning Energy": 10},
        {"Pikachu Lv14": 3, "Raichu Lv45": 2, "Magnemite Lv13": 3, "Magneton Lv28": 2, "Lightning Energy": 10},
        {"Pikachu Lv12": 3, "Raichu Lv40": 2, "Magnemite Lv15": 3, "Magneton Lv35": 2, "Lightning Energy": 10}
    ]
}

#16 cards
secondary = {
    "Water": [
        {"Goldeen": 3, "Seaking": 2, "Staryu": 2, "Starmie": 1, "Water Energy": 8},
        {"Goldeen": 2, "Seaking": 1, "Staryu": 3, "Starmie": 2, "Water Energy": 8},
        {"Tentacool": 3, "Tentacruel": 2, "Shellder": 2, "Cloyster": 1, "Water Energy": 8},
        {"Tentacool": 2, "Tentacruel": 1, "Shellder": 3, "Cloyster": 2, "Water Energy": 8}
    ],
    "Grass": [
        {"Weedle": 4, "Kakuna": 3, "Beedrill": 1, "Grass Energy": 8},
        {"Bellsprout": 4, "Weepinbell": 3, "Victreebel": 1, "Grass Energy": 8},
        {"Nidoranf": 4, "Nidorina": 3, "Nidoqueen": 1, "Grass Energy": 8},
        {"Ekans": 3, "Arbok": 2, "Zubat": 2, "Golbat": 1, "Grass Energy": 8},
        {"Venonat": 3, "Venomoth": 2, "Grimer": 2, "Muk": 1, "Grass Energy": 8},
        {"Ekans": 2, "Arbok": 1, "Zubat": 3, "Golbat": 2, "Grass Energy": 8},
        {"Venonat": 2, "Venomoth": 1, "Grimer": 3, "Muk": 2, "Grass Energy": 8}
    ],
    "Fire": [
        {"Vulpix": 3, "Ninetales Lv35": 2, "Growlithe": 2, "Arcanine Lv34": 1, "Fire Energy": 8},
        {"Ponyta": 3, "Rapidash": 2, "Growlithe": 2, "Arcanine Lv34": 1, "Fire Energy": 8},
        {"Vulpix": 3, "Ninetales Lv35": 2, "Ponyta": 2, "Rapidash": 1, "Fire Energy": 8},
        {"Vulpix": 2, "Ninetales Lv35": 1, "Growlithe": 3, "Arcanine Lv34": 2, "Fire Energy": 8},
        {"Ponyta": 2, "Rapidash": 1, "Growlithe": 3, "Arcanine Lv34": 2, "Fire Energy": 8},
        {"Vulpix": 2, "Ninetales Lv35": 1, "Ponyta": 3, "Rapidash": 2, "Fire Energy": 8},
    ],
    "Fighting": [
        {"Sandshrew": 3, "Sandslash": 2, "Cubone": 2, "Marowak Lv26": 1, "Fighting Energy": 8},
        {"Mankey": 3, "Primeape": 2, "Cubone": 2, "Marowak Lv26": 1, "Fighting Energy": 8},
        {"Sandshrew": 3, "Sandslash": 2, "Mankey": 2, "Primeape": 1, "Fighting Energy": 8},
        {"Sandshrew": 2, "Sandslash": 1, "Cubone": 3, "Marowak Lv26": 2, "Fighting Energy": 8},
        {"Mankey": 2, "Primeape": 1, "Cubone": 3, "Marowak Lv26": 2, "Fighting Energy": 8},
        {"Sandshrew": 2, "Sandslash": 1, "Mankey": 3, "Primeape": 2, "Fighting Energy": 8},
    ],
    "Psychic": [
        {"Drowzee": 3, "Hypno": 2, "Jynx": 2, "Mr Mime": 1, "Psychic Energy": 8},
        {"Slowpoke Lv9": 3, "Slowbro": 2, "Jynx": 2, "Mr Mime": 1, "Psychic Energy": 8},
        {"Slowpoke Lv9": 3, "Slowbro": 2, "Drowzee": 2, "Hypno": 1, "Psychic Energy": 8},
        {"Drowzee": 3, "Hypno": 2, "Jynx": 1, "Mr Mime": 2, "Psychic Energy": 8},
        {"Slowpoke Lv9": 3, "Slowbro": 2, "Jynx": 1, "Mr Mime": 2, "Psychic Energy": 8},
        {"Slowpoke Lv9": 2, "Slowbro": 1, "Drowzee": 3, "Hypno": 2, "Psychic Energy": 8},
    ],
    "Lightning": [
        {"Pikachu Lv12": 3, "Raichu Lv40": 2, "Voltorb": 2, "Electrode Lv42": 1, "Lightning Energy": 8},
        {"Flying Pikachu": 3, "Electabuzz Lv20": 2, "Voltorb": 2, "Electrode Lv42": 1, "Lightning Energy": 8},
        {"Pikachu Lv12": 3, "Raichu Lv40": 2, "Flying Pikachu": 2, "Electabuzz Lv20": 1, "Lightning Energy": 8},
        {"Pikachu Lv12": 2, "Raichu Lv40": 1, "Voltorb": 3, "Electrode Lv42": 2, "Lightning Energy": 8},
        {"Flying Pikachu": 2, "Electabuzz Lv20": 1, "Voltorb": 3, "Electrode Lv42": 2, "Lightning Energy": 8},
        {"Pikachu Lv12": 2, "Raichu Lv40": 1, "Flying Pikachu": 3, "Electabuzz Lv20": 2, "Lightning Energy": 8},
    ]
}

#12 cards
tertiary = {
    "Water": [
        {"Staryu": 2, "Starmie": 1, "Eevee": 2, "Vaporeon Lv29": 1, "Water Energy": 6},
        {"Staryu": 2, "Starmie": 1, "Eevee": 2, "Vaporeon Lv42": 1, "Water Energy": 6},
        {"Goldeen": 2, "Seaking": 1, "Eevee": 2, "Vaporeon Lv29": 1, "Water Energy": 6},
        {"Goldeen": 2, "Seaking": 1, "Eevee": 2, "Vaporeon Lv42": 1, "Water Energy": 6},
        {"Goldeen": 2, "Seaking": 1, "Staryu": 2, "Starmie": 1, "Water Energy": 6},
        {"Goldeen": 2, "Seaking": 1, "Staryu": 2, "Starmie": 1, "Water Energy": 6},
    ],
    "Grass": [
        {"Paras": 2, "Parasect": 1, "Zubat": 2, "Golbat": 1, "Grass Energy": 6},
        {"Tangela Lv12": 2, "Pinsir": 1, "Zubat": 2, "Golbat": 1, "Grass Energy": 6},
        {"Paras": 2, "Parasect": 1, "Tangela Lv12": 2, "Pinsir": 1, "Grass Energy": 6}
    ],
    "Fire": [
        {"Magmar Lv31": 3, "Eevee": 2, "Flareon Lv22": 1, "Fire Energy": 6},
        {"Magmar Lv31": 3, "Eevee": 2, "Flareon Lv28": 1, "Fire Energy": 6},
        {"Magmar Lv31": 3, "Ponyta": 2, "Rapidash": 1, "Fire Energy": 6},
    ],
    "Fighting": [
        {"Sandshrew": 2, "Sandslash": 1, "Cubone": 2, "Marowak Lv26": 1, "Fighting Energy": 6},
        {"Mankey": 2, "Primeape": 1, "Cubone": 2, "Marowak Lv26": 1, "Fighting Energy": 6},
        {"Sandshrew": 2, "Sandslash": 1, "Mankey": 2, "Primeape": 1, "Fighting Energy": 6},
    ],
    "Psychic": [
        {"Mr Mime": 2, "Mewtwo Lv53": 1, "Slowpoke Lv9": 2, "Slowbro": 1, "Psychic Energy": 6},
        {"Mr Mime": 1, "Mewtwo Lv53": 2, "Slowpoke Lv9": 2, "Slowbro": 1, "Psychic Energy": 6},
        {"Mr Mime": 1, "Mewtwo Lv53": 2, "Mew Lv8": 2, "Jynx": 1, "Psychic Energy": 6},
        {"Mr Mime": 2, "Mewtwo Lv53": 1, "Mew Lv8": 2, "Jynx": 1, "Psychic Energy": 6}
    ],
    "Lightning": [
        {"Eevee": 2, "Jolteon Lv24": 1, "Flying Pikachu": 2, "Electabuzz Lv20": 1, "Lightning Energy": 6},
        {"Eevee": 2, "Jolteon Lv29": 1, "Flying Pikachu": 2, "Electabuzz Lv20": 1, "Lightning Energy": 6},
        {"Voltorb": 2, "Electrode Lv42": 1, "Flying Pikachu": 2, "Electabuzz Lv20": 1, "Lightning Energy": 6},
        {"Voltorb": 2, "Electrode Lv42": 1, "Flying Pikachu": 2, "Electabuzz Lv20": 1, "Lightning Energy": 6},
        {"Voltorb": 2, "Electrode Lv42": 1, "Eevee": 2, "Jolteon Lv29": 1, "Lightning Energy": 6},
        {"Voltorb": 2, "Electrode Lv42": 1, "Eevee": 2, "Jolteon Lv24": 1, "Lightning Energy": 6}
    ]
}

#12 cards
#3 pokemon
#9 trainers
colorless_pokemon = [
    {"Rattata": 2, "Raticate": 1},
    {"Meowth Lv14": 2, "Persian": 1},
    {"Spearow": 2, "Fearow": 1},
    {"Doduo": 2, "Dodrio": 1},
    {"Rattata": 2, "Raticate": 1},
    {"Meowth Lv14": 2, "Persian": 1},
    {"Spearow": 2, "Fearow": 1},
    {"Doduo": 2, "Dodrio": 1}
]

starting_deck_trainers = ["Imposter Professor Oak", "Mr Fuji", "Lass", "Imakuni Card",
                          "Pokemon Trader", "Pokemon Breeder", "Clefairy Doll",
                          "Mysterious Fossil", "Energy Retrieval", "Super Energy Retrieval",
                          "Energy Search", "Energy Removal", "Switch", "Pokemon Center",
                          "Poke Ball", "Scoop Up", "Pokedex", "Defender", "Item Finder",
                          "Devolution Spray", "Potion", "Super Potion", "Full Heal",
                          "Revive", "Maintenance", "Pokemon Flute", "Gambler", "Recycle"]

eevee_deck = {
    "Eeevee": 4,
    "Flareon Lv22": 1,
    "Vaporeon Lv29": 1,
    "Jolteon Lv24": 1,
    "Flareon Lv28": 1,
    "Vapoeon Lv42": 1,
    "Jolteon Lv29": 1,
    "Moltres Lv37": 2,
    "Magmar Lv31": 2,
    "Flying Pikachu Lv13": 2,
    "Electabuzz Lv20": 2,
    "Lapras": 2,
    "Surfing Pikachu": 2,
    "Kangaskhan": 2,
    "Tauros": 3,
    "Defender": 3,
    "Poke Ball": 3,
    "Pokemon Trader": 3,
    "Fire Energy": 8,
    "Lightning Energy": 8,
    "Water Energy": 8
}

card_list = [
    "Aerodactyl", "Mysterious Fossil", "Alakazam", "Kadabra", "Abra", "Arbok", "Ekans", "Arcanine Lv34", "Growlithe",
    "Arcanine Lv45", "Articuno Lv35", "Articuno Lv37", "Beedrill", "Kakuna", "Weedle", "Blastoise", "Wartortle",
    "Squirtle", "Butterfree", "Metapod", "Caterpie", "Chansey", "Charizard", "Charmeleon", "Charmander", "Clefable",
    "Clefairy", "Cloyster", "Shellder", "Dewgong", "Seel", "Ditto", "Dodrio", "Doduo", "Dragonite Lv41",
    "Dragonair", "Dratini", "Dragonite Lv45", "Dugtrio", "Diglett", "Electabuzz Lv20", "Electabuzz Lv35",
    "Electrode Lv35", "Voltorb", "Electrode Lv42", "Exeggutor", "Exeggcute", "Farfetchd", "Fearow", "Spearow",
    "Flareon Lv22", "Eevee", "Flareon Lv28", "Flying Pikachu", "Gengar", "Haunter Lv22", "Gastly Lv8", "Haunter Lv17",
    "Gastly Lv17", "Golbat", "Zubat", "Golduck", "Psyduck", "Golem", "Graveler", "Geodude", "Gyarados", "Magikarp",
    "Hitmonchan", "Hitmonlee", "Hypno", "Drowzee", "Jigglypuff Lv12", "Jolteon Lv24", "Jolteon Lv29", "Jynx", "Kabutops",
    "Kabuto", "Kangaskhan", "Kingler", "Krabby", "Lapras", "Lickitung", "Machamp", "Machoke", "Machop", "Magmar Lv24",
    "Magmar Lv31", "Magneton Lv28", "Magnemite Lv13", "Magneton Lv35", "Magnemite Lv15", "Marowak Lv26", "Cubone",
    "Marowak Lv32", "Mew Lv8", "Mew Lv15", "Mew Lv23", "Mewtwo Lv53", "Mewtwo Lv60", "Mewtwo Alt Lv60", "Moltres Lv35",
    "Moltres Lv37", "Mr Mime", "Muk", "Grimer", "Nidoking", "Nidorino", "Nidoranm", "Nidoqueen", "Nidorina",
    "Nidoranf", "Ninetales Lv32", "Vulpix", "Ninetales Lv35", "Omastar", "Omanyte", "Onix", "Parasect", "Paras",
    "Persian", "Meowth Lv14", "Meowth Lv15", "Pidgeot Lv38", "Pidgeotto", "Pidgey", "Pidgeot Lv40", "Pinsir",
    "Poliwrath", "Poliwhirl", "Poliwag", "Porygon", "Primeape", "Mankey", "Raichu Lv40", "Pikachu Lv12", "Raichu Lv45",
    "Pikachu Lv14", "Pikachu Lv16", "Pikachu Alt Lv16", "Rapidash", "Ponyta", "Raticate", "Rattata", "Rhydon",
    "Rhyhorn", "Sandslash", "Sandshrew", "Scyther", "Seadra", "Horsea", "Seaking", "Goldeen", "Slowbro", "Slowpoke Lv18",
    "Slowpoke Lv9", "Snorlax", "Starmie", "Staryu", "Surfing Pikachu Lv13", "Surfing Pikachu Alt Lv13", "Tangela Lv12",
    "Tangela Lv8", "Tauros", "Tentacruel", "Tentacool", "Vaporeon Lv29", "Vaporeon Lv42", "Venomoth", "Venonat",
    "Venusaur Lv64", "Ivysaur", "Bulbasaur", "Venusaur Lv67", "Victreebel", "Weepinbell", "Bellsprout", "Vileplume",
    "Gloom", "Oddish", "Weezing", "Koffing", "Wigglytuff", "Jigglypuff Lv13", "Jigglypuff Lv14", "Zapdos Lv40",
    "Zapdos Lv64", "Zapdos Lv68",
    "Clefairy Doll", "Defender", "Devolution Spray", "Energy Removal", "Energy Retrieval", "Energy Search",
    "Full Heal", "Gambler", "Imakuni Card", "Imposter Professor Oak", "Item Finder", "Lass", "Maintenance",
    "Mr Fuji", "Poke Ball", "Pokedex", "Pokemon Breeder", "Pokemon Center", "Pokemon Flute", "Pokemon Trader",
    "Potion", "Recycle", "Revive", "Scoop Up", "Super Energy Retrieval", "Super Potion", "Switch",
    "Computer Search", "Gust  of Wind", "Pluspower",
    "Bill", "Professor Oak", "Super Energy Removal", "Double Colorless Energy"
]

card_ids = {
    "Grass Energy": 0x01,
    "Fire Energy": 0x02,
    "Water Energy": 0x03,
    "Lightning Energy": 0x04,
    "Fighting Energy": 0x05,
    "Psychic Energy": 0x06,
    "Double Colorless Energy": 0x07,
    "Bulbasaur": 0x08,
    "Ivysaur": 0x09,
    "Venusaur Lv64": 0x0a,
    "Venusaur Lv67": 0x0b,
    "Caterpie": 0x0c,
    "Metapod": 0x0d,
    "Butterfree": 0x0e,
    "Weedle": 0x0f,
    "Kakuna": 0x10,
    "Beedrill": 0x11,
    "Ekans": 0x12,
    "Arbok": 0x13,
    "Nidoranf": 0x14,
    "Nidorina": 0x15,
    "Nidoqueen": 0x16,
    "Nidoranm": 0x17,
    "Nidorino": 0x18,
    "Nidoking": 0x19,
    "Zubat": 0x1a,
    "Golbat": 0x1b,
    "Oddish": 0x1c,
    "Gloom": 0x1d,
    "Vileplume": 0x1e,
    "Paras": 0x1f,
    "Parasect": 0x20,
    "Venonat": 0x21,
    "Venomoth": 0x22,
    "Bellsprout": 0x23,
    "Weepinbell": 0x24,
    "Victreebel": 0x25,
    "Grimer": 0x26,
    "Muk": 0x27,
    "Exeggcute": 0x28,
    "Exeggutor": 0x29,
    "Koffing": 0x2a,
    "Weezing": 0x2b,
    "Tangela Lv8": 0x2c,
    "Tangela Lv12": 0x2d,
    "Scyther": 0x2e,
    "Pinsir": 0x2f,
    "Charmander": 0x30,
    "Charmeleon": 0x31,
    "Charizard": 0x32,
    "Vulpix": 0x33,
    "Ninetales Lv32": 0x34,
    "Ninetales Lv35": 0x35,
    "Growlithe": 0x36,
    "Arcanine Lv34": 0x37,
    "Arcanine Lv45": 0x38,
    "Ponyta": 0x39,
    "Rapidash": 0x3a,
    "Magmar Lv24": 0x3b,
    "Magmar Lv31": 0x3c,
    "Flareon Lv22": 0x3d,
    "Flareon Lv28": 0x3e,
    "Moltres Lv35": 0x3f,
    "Moltres Lv37": 0x40,
    "Squirtle": 0x41,
    "Wartortle": 0x42,
    "Blastoise": 0x43,
    "Psyduck": 0x44,
    "Golduck": 0x45,
    "Poliwag": 0x46,
    "Poliwhirl": 0x47,
    "Poliwrath": 0x48,
    "Tentacool": 0x49,
    "Tentacruel": 0x4a,
    "Seel": 0x4b,
    "Dewgong": 0x4c,
    "Shellder": 0x4d,
    "Cloyster": 0x4e,
    "Krabby": 0x4f,
    "Kingler": 0x50,
    "Horsea": 0x51,
    "Seadra": 0x52,
    "Goldeen": 0x53,
    "Seaking": 0x54,
    "Staryu": 0x55,
    "Starmie": 0x56,
    "Magikarp": 0x57,
    "Gyarados": 0x58,
    "Lapras": 0x59,
    "Vaporeon Lv29": 0x5a,
    "Vaporeon Lv42": 0x5b,
    "Omanyte": 0x5c,
    "Omastar": 0x5d,
    "Articuno Lv35": 0x5e,
    "Articuno Lv37": 0x5f,
    "Pikachu Lv12": 0x60,
    "Pikachu Lv14": 0x61,
    "Pikachu Lv16": 0x62,
    "Pikachu Alt Lv16": 0x63,
    "Flying Pikachu": 0x64,
    "Surfing Pikachu Lv13": 0x65,
    "Surfing Pikachu Alt Lv13": 0x66,
    "Raichu Lv40": 0x67,
    "Raichu Lv45": 0x68,
    "Magnemite Lv13": 0x69,
    "Magnemite Lv15": 0x6a,
    "Magneton Lv28": 0x6b,
    "Magneton Lv35": 0x6c,
    "Voltorb": 0x6d,
    "Electrode Lv35": 0x6e,
    "Electrode Lv42": 0x6f,
    "Electabuzz Lv20": 0x70,
    "Electabuzz Lv35": 0x71,
    "Jolteon Lv24": 0x72,
    "Jolteon Lv29": 0x73,
    "Zapdos Lv40": 0x74,
    "Zapdos Lv64": 0x75,
    "Zapdos Lv68": 0x76,
    "Sandshrew": 0x77,
    "Sandslash": 0x78,
    "Diglett": 0x79,
    "Dugtrio": 0x7a,
    "Mankey": 0x7b,
    "Primeape": 0x7c,
    "Machop": 0x7d,
    "Machoke": 0x7e,
    "Machamp": 0x7f,
    "Geodude": 0x80,
    "Graveler": 0x81,
    "Golem": 0x82,
    "Onix": 0x83,
    "Cubone": 0x84,
    "Marowak Lv26": 0x85,
    "Marowak Lv32": 0x86,
    "Hitmonlee": 0x87,
    "Hitmonchan": 0x88,
    "Rhyhorn": 0x89,
    "Rhydon": 0x8a,
    "Kabuto": 0x8b,
    "Kabutops": 0x8c,
    "Aerodactyl": 0x8d,
    "Abra": 0x8e,
    "Kadabra": 0x8f,
    "Alakazam": 0x90,
    "Slowpoke Lv9": 0x91,
    "Slowpoke Lv18": 0x92,
    "Slowbro": 0x93,
    "Gastly Lv8": 0x94,
    "Gastly Lv17": 0x95,
    "Haunter Lv17": 0x96,
    "Haunter Lv22": 0x97,
    "Gengar": 0x98,
    "Drowzee": 0x99,
    "Hypno": 0x9a,
    "Mr Mime": 0x9b,
    "Jynx": 0x9c,
    "Mewtwo Lv53": 0x9d,
    "Mewtwo Lv60": 0x9e,
    "Mewtwo Alt Lv60": 0x9f,
    "Mew Lv8": 0xa0,
    "Mew Lv15": 0xa1,
    "Mew Lv23": 0xa2,
    "Pidgey": 0xa3,
    "Pidgeotto": 0xa4,
    "Pidgeot Lv38": 0xa5,
    "Pidgeot Lv40": 0xa6,
    "Rattata": 0xa7,
    "Raticate": 0xa8,
    "Spearow": 0xa9,
    "Fearow": 0xaa,
    "Clefairy": 0xab,
    "Clefable": 0xac,
    "Jigglypuff Lv12": 0xad,
    "Jigglypuff Lv13": 0xae,
    "Jigglypuff Lv14": 0xaf,
    "Wigglytuff": 0xb0,
    "Meowth Lv14": 0xb1,
    "Meowth Lv15": 0xb2,
    "Persian": 0xb3,
    "Farfetchd": 0xb4,
    "Doduo": 0xb5,
    "Dodrio": 0xb6,
    "Lickitung": 0xb7,
    "Chansey": 0xb8,
    "Kangaskhan": 0xb9,
    "Tauros": 0xba,
    "Ditto": 0xbb,
    "Eevee": 0xbc,
    "Porygon": 0xbd,
    "Snorlax": 0xbe,
    "Dratini": 0xbf,
    "Dragonair": 0xc0,
    "Dragonite Lv41": 0xc1,
    "Dragonite Lv45": 0xc2,
    "Professor Oak": 0xc3,
    "Imposter Professor Oak": 0xc4,
    "Bill": 0xc5,
    "Mr Fuji": 0xc6,
    "Lass": 0xc7,
    "Imakuni Card": 0xc8,
    "Pokemon Trader": 0xc9,
    "Pokemon Breeder": 0xca,
    "Clefairy Doll": 0xcb,
    "Mysterious Fossil": 0xcc,
    "Energy Retrieval": 0xcd,
    "Super Energy Retrieval": 0xce,
    "Energy Search": 0xcf,
    "Energy Removal": 0xd0,
    "Super Energy Removal": 0xd1,
    "Switch": 0xd2,
    "Pokemon Center": 0xd3,
    "Poke Ball": 0xd4,
    "Scoop Up": 0xd5,
    "Computer Search": 0xd6,
    "Pokedex": 0xd7,
    "Pluspower": 0xd8,
    "Defender": 0xd9,
    "Item Finder": 0xda,
    "Gust of Wind": 0xdb,
    "Devolution Spray": 0xdc,
    "Potion": 0xdd,
    "Super Potion": 0xde,
    "Full Heal": 0xdf,
    "Revive": 0xe0,
    "Maintenance": 0xe1,
    "Pokemon Flute": 0xe2,
    "Gambler": 0xe3,
    "Recycle": 0xe4,
}

medal_ids = {
    "Grass Medal": 0xf0,
    "Science Medal": 0xf1,
    "Fire Medal": 0xf2,
    "Water Medal": 0xf3,
    "Lightning Medal": 0xf4,
    "Psychic Medal": 0xf5,
    "Rock Medal": 0xf6,
    "Fighting Medal": 0xf7
}