evoline = {
    "Aerodactyl": ["Aerodactyle Pack"],
    "Mysterious Fossil": ["Aerodactyle Pack", "Kabutops Pack", "Omastar Pack"],
    "Alakazam": ["Alakazam Pack"],
    "Kadabra": ["Alakazam Pack"],
    "Abra": ["Alakazam Pack"],
    "Arbok": ["Arbok Pack"],
    "Ekans": ["Arbok Pack"],
    "Arcanine LV34": ["Arcanine 1 Pack"],
    "Growlithe": ["Arcanine 1 Pack", "Arcanine 2 Pack"],
    "Arcanine LV45": ["Arcanine 2 Pack"],
    "Articuno LV35": ["Articuno 1 Pack"],
    "Articuno LV37": ["Articuno 2 Pack"],
    "Beedrill": ["Beedrill Pack"],
    "Kakuna": ["Beedrill Pack"],
    "Weedle": ["Beedrill Pack"],
    "Blastoise": ["Blastoise Pack"],
    "Wartortle": ["Blastoise Pack"],
    "Squirtle": ["Blastoise Pack"],
    "Butterfree": ["Butterfree Pack"],
    "Metapod": ["Butterfree Pack"],
    "Caterpie": ["Butterfree Pack"],
    "Chansey": ["Chansey Pack"],
    "Charizard": ["Charizard Pack"],
    "Charmeleon": ["Charizard Pack"],
    "Charmander": ["Charizard Pack"],
    "Clefable": ["Clefable Pack"],
    "Clefairy": ["Clefable Pack"],
    "Cloyster": ["Cloyster Pack"],
    "Shellder": ["Cloyster Pack"],
    "Dewgong": ["Dewgong Pack"],
    "Seel": ["Dewgong Pack"],
    "Ditto": ["Ditto Pack"],
    "Dodrio": ["Dodrio Pack"],
    "Doduo": ["Dodrio Pack"],
    "Dragonite LV41": ["Dragonite 1 Pack"],
    "Dragonair": ["Dragonite 1 Pack", "Dragonite 2 Pack"],
    "Dratini": ["Dragonite 1 Pack", "Dragonite 2 Pack"],
    "Dragonite LV45": ["Dragonite 2 Pack"],
    "Dugtrio": ["Dugtrio Pack"],
    "Diglett": ["Dugtrio Pack"],
    "Electabuzz LV20": ["Electabuzz 1 Pack"],
    "Electabuzz LV35": ["Electabuzz 2 Pack"],
    "Electrode LV35": ["Electrode 1 Pack"],
    "Voltorb": ["Electrode 1 Pack", "Electrode 2 Pack"],
    "Electrode LV42": ["Electrode 2 Pack"],
    "Exeggutor": ["Exeggutor Pack"],
    "Exeggcute": ["Exeggutor Pack"],
    "Farfetchd": ["Farfetchd Pack"],
    "Fearow": ["Fearow Pack"],
    "Spearow": ["Fearow Pack"],
    "Flareon LV22": ["Flareon 1 Pack"],
    "Eevee": ["Flareon 1 Pack", "Flareon 2 Pack", "Jolteon 1 Pack", "Jolteon 2 Pack", "Vaporeon 1 Pack",
              "Vaporeon 2 Pack"],
    "Flareon LV28": ["Flareon 2 Pack"],
    "Flying Pikachu": ["Flying Pikachu Pack"],
    "Gengar": ["Gengar 1 Pack", "Gengar 2 Pack"],
    "Haunter LV22": ["Gengar 1 Pack"],
    "Gastly LV8": ["Gengar 1 Pack"],
    "Haunter LV17": ["Gengar 2 Pack"],
    "Gastly LV17": ["Gengar 2 Pack"],
    "Golbat": ["Golbat Pack"],
    "Zubat": ["Golbat Pack"],
    "Golduck": ["Golduck Pack"],
    "Psyduck": ["Golduck Pack"],
    "Golem": ["Golem Pack"],
    "Graveler": ["Golem Pack"],
    "Geodude": ["Golem Pack"],
    "Gyarados": ["Gyrados Pack"],
    "Magikarp": ["Gyrados Pack"],
    "Hitmonchan": ["Hitmonchan Pack"],
    "Hitmonlee": ["Hitmonlee Pack"],
    "Hypno": ["Hypno Pack"],
    "Drowzee": ["Hypno Pack"],
    "Jigglypuff LV12": ["Jigglypuff Promo Pack"],
    "Jolteon LV24": ["Jolteon 1 Pack"],
    "Jolteon LV29": ["Jolteon 2 Pack"],
    "Jynx": ["Jynx Pack"],
    "Kabutops": ["Kabutops Pack"],
    "Kabuto": ["Kabutops Pack"],
    "Kangaskhan": ["Kangaskhan Pack"],
    "Kingler": ["Kingler Pack"],
    "Krabby": ["Kingler Pack"],
    "Lapras": ["Lapras Pack"],
    "Lickitung": ["Lickitung Pack"],
    "Machamp": ["Machamp Pack"],
    "Machoke": ["Machamp Pack"],
    "Machop": ["Machamp Pack"],
    "Magmar LV24": ["Magmar 1 Pack"],
    "Magmar LV31": ["Magmar 2 Pack"],
    "Magneton LV28": ["Magneton 1 Pack"],
    "Magnemite LV13": ["Magneton 1 Pack"],
    "Magneton LV35": ["Magneton 2 Pack"],
    "Magnemite LV15": ["Magneton 2 Pack"],
    "Marowak LV26": ["Marowak 1 Pack"],
    "Cubone": ["Marowak 1 Pack", "Marowak 2 Pack"],
    "Marowak LV32": ["Marowak 2 Pack"],
    "Mew LV8": ["Mew 1 Pack"],
    "Mew LV15": ["Mew 2 Pack"],
    "Mew LV23": ["Mew 3 Pack"],
    "Mewtwo LV53": ["Mewtwo 1 Pack"],
    "Mewtwo LV60": ["Mewtwo 2 Pack"],
    "Mewtwo Alt LV60": ["Mewtwo 3 Pack"],
    "Moltres LV35": ["Moltres 1 Pack"],
    "Moltres LV37": ["Moltres 2 Pack"],
    "Mr Mime": ["Mr Mime Pack"],
    "Muk": ["Muk Pack"],
    "Grimer": ["Muk Pack"],
    "Nidoking": ["Nidoking Pack"],
    "Nidorino": ["Nidoking Pack"],
    "Nidoranm": ["Nidoking Pack"],
    "Nidoqueen": ["Nidoqueen Pack"],
    "Nidorina": ["Nidoqueen Pack"],
    "Nidoranf": ["Nidoqueen Pack"],
    "Ninetales LV32": ["Ninetales 1 Pack"],
    "Vulpix": ["Ninetales 1 Pack", "Ninetales 2 Pack"],
    "Ninetales LV35": ["Ninetales 2 Pack"],
    "Omastar": ["Omastar Pack"],
    "Omanyte": ["Omastar Pack"],
    "Onix": ["Onix Pack"],
    "Parasect": ["Parasect Pack"],
    "Paras": ["Parasect Pack"],
    "Persian": ["Persian 1 Pack", "Persian 2 Pack"],
    "Meowth LV14": ["Persian 1 Pack"],
    "Meowth LV15": ["Persian 2 Pack"],
    "Pidgeot LV38": ["Pidgeot 1 Pack"],
    "Pidgeotto": ["Pidgeot 1 Pack", "Pidgeot 2 Pack"],
    "Pidgey": ["Pidgeot 1 Pack", "Pidgeot 2 Pack"],
    "Pidgeot LV40": ["Pidgeot 2 Pack"],
    "Pinsir": ["Pinsir Pack"],
    "Poliwrath": ["Poliwrath Pack"],
    "Poliwhirl": ["Poliwrath Pack"],
    "Poliwag": ["Poliwrath Pack"],
    "Porygon": ["Porygon"],
    "Primeape": ["Primeape Pack"],
    "Mankey": ["Primeape Pack"],
    "Raichu LV40": ["Raichu 1 Pack", "Raichu 3 Pack"],
    "Pikachu LV12": ["Raichu 1 Pack"],
    "Raichu LV45": ["Raichu 2 Pack", "Raichu 4 Pack"],
    "Pikachu LV14": ["Raichu 2 Pack"],
    "Pikachu LV16": ["Raichu 3 Pack"],
    "Pikachu Alt LV16": ["Raichu 4 Pack"],
    "Rapidash": ["Rapidash Pack"],
    "Ponyta": ["Rapidash Pack"],
    "Raticate": ["Raticate Pack"],
    "Rattata": ["Raticate Pack"],
    "Rhydon": ["Rhydon Pack"],
    "Rhyhorn": ["Rhydon Pack"],
    "Sandslash": ["Sandslash Pack"],
    "Sandshrew": ["Sandslash Pack"],
    "Scyther": ["Scyther Pack"],
    "Seadra": ["Seadra Pack"],
    "Horsea": ["Seadra Pack"],
    "Seaking": ["Seaking Pack"],
    "Goldeen": ["Seaking Pack"],
    "Slowbro": ["Slowbro Pack"],
    "Slowpoke LV18": ["Slowbro Pack"],
    "Slowpoke LV9": ["Slowpoke Promo Pack"],
    "Snorlax": ["Snorlax Pack"],
    "Starmie": ["Starmie Pack"],
    "Staryu": ["Starmie Pack"],
    "Surfing Pikachu LV13": ["Surfing Pikachu 1 Pack"],
    "Surfing Pikachu Alt LV13": ["Surfing Pikachu 2 Pack"],
    "Tangela LV12": ["Tangela 1 Pack"],
    "Tangela LV8": ["Tangela 1 Pack"],
    "Tauros": ["Tauros Pack"],
    "Tentacruel": ["Tentacruel Pack"],
    "Tentacool": ["Tentacruel Pack"],
    "Vaporeon LV29": ["Vaporeon 1 Pack"],
    "Vaporeon LV42": ["Vaporeon 2 Pack"],
    "Venomoth": ["Venomoth Pack"],
    "Venonat": ["Venomoth Pack"],
    "Venusaur LV64": ["Venusaur 1 Pack"],
    "Ivysaur": ["Venusaur 1 Pack", "Venusaur 2 Pack"],
    "Bulbasaur": ["Venusaur 1 Pack", "Venusaur 2 Pack"],
    "Venusaur LV67": ["Venusaur 2 Pack"],
    "Victreebel": ["Victreebel Pack"],
    "Weepinbell": ["Victreebel Pack"],
    "Bellsprout": ["Victreebel Pack"],
    "Vileplume": ["Vileplume Pack"],
    "Gloom": ["Vileplume Pack"],
    "Oddish": ["Vileplume Pack"],
    "Weezing": ["Weezing Pack"],
    "Koffing": ["Weezing Pack"],
    "Wigglytuff": ["Wigglytuff 1 Pack", "Wigglytuff 2 Pack"],
    "Jigglypuff LV13": ["Wigglytuff 1 Pack"],
    "Jigglypuff LV14": ["Wigglytuff 2 Pack"],
    "Zapdos LV40": ["Zapdos 1 Pack"],
    "Zapdos LV64": ["Zapdos 2 Pack"],
    "Zapdos LV68": ["Zapdos 3 Pack"],

    "Clefairy Doll": ["Clefairy Doll Pack"],
    "Defender": ["Defender Pack"],
    "Devolution Spray": ["Devolution Spray Pack"],
    "Energy Removal": ["Energy Removal Pack"],
    "Energy Retrieval": ["Energy Retrieval Pack"],
    "Energy Search": ["Energy Search Pack"],
    "Full Heal": ["Full Heal Pack"],
    "Gambler": ["Gambler Pack"],
    "Imakuni Card": ["Imakuni? Pack"],
    "Imposter Professor Oak": ["Imposter Professor Oak Pack"],
    "Item Finder": ["Item Finder Pack"],
    "Lass": ["Lass Pack"],
    "Maintenance": ["Maintenance Pack"],
    "Mr Fuji": ["Mr Fuji Pack"],
    "Poke Ball": ["Poke Ball Pack"],
    "Pokedex": ["Pokedex Pack"],
    "Pokemon Breeder": ["Pokemon Breeder Pack"],
    "Pokemon Center": ["Pokemon Center Pack"],
    "Pokemon Flute": ["Pokemon Flute Pack"],
    "Pokemon Trader": ["Pokemon Trader Pack"],
    "Potion": ["Potion Pack"],
    "Recycle": ["Recycle Pack"],
    "Revive": ["Revive Pack"],
    "Scoop Up": ["Scoop Up Pack"],
    "Super Energy Retrieval": ["Super Energy Retrieval Pack"],
    "Super Potion": ["Super Potion Pack"],
    "Switch": ["Switch Pack"],

    "Computer Search": ["Computer Search Pack"],
    "Gust  of Wind": ["Gust  of Wind Pack"],
    "Pluspower": ["Pluspower Pack"],

    "Bill": ["Bill Pack"],
    "Professor Oak": ["Professor Oak Pack"],
    "Super Energy Removal": ["Super Energy Removal Pack"],
    "Double Colorless Energy": ["Double Colorless Energy Pack"],
    "Water Energy": ["Starting Deck"],
    "Fire Energy": ["Starting Deck"],
    "Grass Energy": ["Starting Deck"],
    "Lightning Energy": ["Starting Deck"],
    "Fighting Energy": ["Starting Deck"],
    "Psychic Energy": ["Starting Deck"]
}

three_stage = {
    "Water": [["Squirtle", "Wartortle", "Blastoise"],
              ["Poliwag", "Poliwhirl", "Poliwrath"]],

    "Grass": [["Bulbasaur", "Ivysaur", "Venusaur Lv 64"],
              ["Bulbasaur", "Ivysaur", "Venusaur Lv 67"],
              ["Caterpie", "Metapod", "Butterfree"],
              ["Weedle", "Kakuna", "Beedrill"],
              ["Nidoranf", "Nidorina", "Nidoqueen"],
              ["Nidoranm", "Nidorino", "Nidoking"],
              ["Oddish", "Gloom", "Vileplume"],
              ["Bellsprout", "Weepinbell", "Victreebel"]],

    "Fire": [["Charmander", "Charmeleon", "Charizard"]],

    "Fighting": [["Machop", "Machoke", "Machamp"],
                 ["Geodude", "Graveler", "Golem"]],

    "Psychic": [["Abra", "Kadabra", "Alakazam"],
                ["Gastly Lv8", "Haunter Lv17", "Gengar"],
                ["Gastly Lv17", "Haunter Lv22", "Gengar"]],

    "Lightning": [],

    "Colorless": [["Pidgey", "Pidgeotto", "Pidgeot Lv38"],
                  ["Pidgey", "Pidgeotto", "Pidgeot Lv40"],
                  ["Dratini", "Dragonair", "Dragonite Lv41"],
                  ["Dratini", "Dragonair", "Dragonite Lv45"]]
}

two_stage = {
    "Water": [["Psyduck", "Golduck"],
              ["Tentacool", "Tentacruel"],
              ["Seel", "Dewgong"],
              ["Shellder", "Cloyster"],
              ["Krabby", "Kingler"],
              ["Horsea", "Seadra"],
              ["Goldeen", "Seaking"],
              ["Staryu", "Starmie"],
              ["Magikarp", "Gyarados"],
              ["Eevee", "Vaporeon Lv29"],
              ["Eevee", "Vaporeon Lv42"]],

    "Grass": [["Ekans", "Arbok"],
              ["Zubat", "Golbat"],
              ["Paras", "Parasect"],
              ["Venonat", "Venomoth"],
              ["Grimer", "Muk"],
              ["Exeggcute", "Exeggutor"],
              ["Exeggcute", "Exeggutor"],
              ["Koffing", "Weezing"]],

    "Fire": [["Vulpix", "Ninetales Lv32"],
             ["Vulpix", "Ninetales Lv35"],
             ["Growlithe", "Arcanine Lv34"],
             ["Growlithe", "Arcanine Lv45"],
             ["Ponyta", "Rapidash"],
             ["Eevee", "Flareon Lv22"],
             ["Eevee", "Flareon Lv28"]],

    "Fighting": [["Sandshrew", "Sandslash"],
                 ["Diglett", "Dugtrio"],
                 ["Mankey", "Primeape"],
                 ["Cubone", "Marowak Lv26"],
                 ["Cubone", "Marowak Lv32"],
                 ["Rhyhorn", "Rhydon"]],

    "Psychic": [["Slowpoke Lv9", "Slowbro"],
                ["Slowpoke Lv18", "Slowbro"],
                ["Drowzee", "Hypno"]],

    "Lightning": [["Pikachu Lv12", "Raichu Lv40"],
                  ["Pikachu Lv14", "Raichu Lv45"],
                  ["Pikachu Lv16", "Raichu Lv40"],
                  ["Pikachu Alt Lv16", "Raichu Lv45"],
                  ["Magnemite Lv13", "Magneton Lv28"],
                  ["Magnemite Lv15", "Magneton Lv28"],
                  ["Magnemite Lv13", "Magneton Lv35"],
                  ["Magnemite Lv15", "Magneton Lv35"],
                  ["Voltorb", "Electrode Lv42"],
                  ["Voltorb", "Electrode Lv35"],
                  ["Eevee", "Jolteon Lv24"],
                  ["Eevee", "Jolteon Lv29"]],

    "Colorless": [["Rattata", "Raticate"],
                  ["Spearow", "Fearow"],
                  ["Clefairy", "Clefable"],
                  ["Jigglypuff Lv12", "Wigglytuff"],
                  ["Jigglypuff Lv13", "Wigglytuff"],
                  ["Jigglypuff Lv14", "Wigglytuff"],
                  ["Meowth Lv14", "Persian"],
                  ["Meowth Lv15", "Persian"],
                  ["Doduo", "Dodrio"]],
}

basic_only = {
    "Water": ["Lapras", "Articuno Lv35", "Articuno Lv37"],
    "Grass": ["Tangela Lv8", "Tangela Lv12", "Scyther", "Pinsir"],
    "Fire": ["Magmar Lv24", "Magmar Lv31", "Moltres Lv35", "Moltres Lv37"],
    "Fighting": ["Onix", "Hitmonlee", "Hitmonchan"],
    "Psychic": ["Mr Mime", "Jynx", "Mewtwo Lv53", "Mewtwo Lv60", "Mewtwo Alt Lv60", "Mew Lv8", "Mew Lv15", "Mew Lv23"],
    "Lightning": ["Flying Pikachu", "Electabuzz Lv20", "Electabuzz Lv35", "Zapdos Lv40", "Zapdos Lv64", "Zapdos Lv68"],
    "Colorless": ["Farfetchd", "Lickitung", "Chansey", "Kangaskhan", "Tauros", "Ditto", "Porygon", "Snorlax"],
}

starting_deck_trainers = ["Imposter Professor Oak", "Mr Fuji", "Lass", "Imakuni Card",
                          "Pokemon Trader", "Pokemon Breeder", "Clefairy Doll",
                          "Mysterious Fossil", "Energy Retrieval", "Super Energy Retrieval",
                          "Energy Search", "Energy Removal", "Switch", "Pokemon Center",
                          "Poke Ball", "Scoop Up", "Pokedex", "Defender", "Item Finder",
                          "Devolution Spray", "Potion", "Super Potion", "Full Heal",
                          "Revive", "Maintenance", "Pokemon Flute", "Gambler", "Recycle"]

card_list = [
    "Aerodactyl", "Mysterious Fossil", "Alakazam", "Kadabra", "Abra", "Arbok", "Ekans", "Arcanine LV34", "Growlithe",
    "Arcanine LV45", "Articuno LV35", "Articuno LV37", "Beedrill", "Kakuna", "Weedle", "Blastoise", "Wartortle",
    "Squirtle", "Butterfree", "Metapod", "Caterpie", "Chansey", "Charizard", "Charmeleon", "Charmander", "Clefable",
    "Clefairy", "Cloyster", "Shellder", "Dewgong", "Seel", "Ditto", "Dodrio", "Doduo", "Dragonite LV41",
    "Dragonair", "Dratini", "Dragonite LV45", "Dugtrio", "Diglett", "Electabuzz LV20", "Electabuzz LV35",
    "Electrode LV35", "Voltorb", "Electrode LV42", "Exeggutor", "Exeggcute", "Farfetchd", "Fearow", "Spearow",
    "Flareon LV22", "Eevee", "Flareon LV28", "Flying Pikachu", "Gengar", "Haunter LV22", "Gastly LV8", "Haunter LV17",
    "Gastly LV17", "Golbat", "Zubat", "Golduck", "Psyduck", "Golem", "Graveler", "Geodude", "Gyarados", "Magikarp",
    "Hitmonchan", "Hitmonlee", "Hypno", "Drowzee", "Jigglypuff LV12", "Jolteon LV24", "Jolteon LV29", "Jynx", "Kabutops",
    "Kabuto", "Kangaskhan", "Kingler", "Krabby", "Lapras", "Lickitung", "Machamp", "Machoke", "Machop", "Magmar LV24",
    "Magmar LV31", "Magneton LV28", "Magnemite LV13", "Magneton LV35", "Magnemite LV15", "Marowak LV26", "Cubone",
    "Marowak LV32", "Mew LV8", "Mew LV15", "Mew LV23", "Mewtwo LV53", "Mewtwo LV60", "Mewtwo Alt LV60", "Moltres LV35",
    "Moltres LV37", "Mr Mime", "Muk", "Grimer", "Nidoking", "Nidorino", "Nidoranm", "Nidoqueen", "Nidorina",
    "Nidoranf", "Ninetales LV32", "Vulpix", "Ninetales LV35", "Omastar", "Omanyte", "Onix", "Parasect", "Paras",
    "Persian", "Meowth LV14", "Meowth LV15", "Pidgeot LV38", "Pidgeotto", "Pidgey", "Pidgeot LV40", "Pinsir",
    "Poliwrath", "Poliwhirl", "Poliwag", "Porygon", "Primeape", "Mankey", "Raichu LV40", "Pikachu LV12", "Raichu LV45",
    "Pikachu LV14", "Pikachu LV16", "Pikachu Alt LV16", "Rapidash", "Ponyta", "Raticate", "Rattata", "Rhydon",
    "Rhyhorn", "Sandslash", "Sandshrew", "Scyther", "Seadra", "Horsea", "Seaking", "Goldeen", "Slowbro", "Slowpoke LV18",
    "Slowpoke LV9", "Snorlax", "Starmie", "Staryu", "Surfing Pikachu LV13", "Surfing Pikachu Alt LV13", "Tangela LV12",
    "Tangela LV8", "Tauros", "Tentacruel", "Tentacool", "Vaporeon LV29", "Vaporeon LV42", "Venomoth", "Venonat",
    "Venusaur LV64", "Ivysaur", "Bulbasaur", "Venusaur LV67", "Victreebel", "Weepinbell", "Bellsprout", "Vileplume",
    "Gloom", "Oddish", "Weezing", "Koffing", "Wigglytuff", "Jigglypuff LV13", "Jigglypuff LV14", "Zapdos LV40",
    "Zapdos LV64", "Zapdos LV68",
    "Clefairy Doll", "Defender", "Devolution Spray", "Energy Removal", "Energy Retrieval", "Energy Search",
    "Full Heal", "Gambler", "Imakuni Card", "Imposter Professor Oak", "Item Finder", "Lass", "Maintenance",
    "Mr Fuji", "Poke Ball", "Pokedex", "Pokemon Breeder", "Pokemon Center", "Pokemon Flute", "Pokemon Trader",
    "Potion", "Recycle", "Revive", "Scoop Up", "Super Energy Retrieval", "Super Potion", "Switch",
    "Computer Search", "Gust  of Wind", "Pluspower",
    "Bill", "Professor Oak", "Super Energy Removal", "Double Colorless Energy",
    "Water Energy", "Fire Energy", "Grass Energy", "Lightning Energy", "Fighting Energy", "Psychic Energy"
]

Card_Ids = {
    "Grass Energy": 0x01,
    "Fire Energy": 0x02,
    "Water Energy": 0x03,
    "Lightning Energy": 0x04,
    "Fighting Energy": 0x05,
    "Psychic Energy": 0x06,
    "Double Colorless Energy": 0x07,
    "Bulbasaur": 0x08,
    "Ivysaur": 0x09,
    "Venusaur Lv64": 0x0a,
    "Venusaur Lv67": 0x0b,
    "Caterpie": 0x0c,
    "Metapod": 0x0d,
    "Butterfree": 0x0e,
    "Weedle": 0x0f,
    "Kakuna": 0x10,
    "Beedrill": 0x11,
    "Ekans": 0x12,
    "Arbok": 0x13,
    "Nidoranf": 0x14,
    "Nidorina": 0x15,
    "Nidoqueen": 0x16,
    "Nidoranm": 0x17,
    "Nidorino": 0x18,
    "Nidoking": 0x19,
    "Zubat": 0x1a,
    "Golbat": 0x1b,
    "Oddish": 0x1c,
    "Gloom": 0x1d,
    "Vileplume": 0x1e,
    "Paras": 0x1f,
    "Parasect": 0x20,
    "Venonat": 0x21,
    "Venomoth": 0x22,
    "Bellsprout": 0x23,
    "Weepinbell": 0x24,
    "Victreebel": 0x25,
    "Grimer": 0x26,
    "Muk": 0x27,
    "Exeggcute": 0x28,
    "Exeggutor": 0x29,
    "Koffing": 0x2a,
    "Weezing": 0x2b,
    "Tangela Lv8": 0x2c,
    "Tangela Lv12": 0x2d,
    "Scyther": 0x2e,
    "Pinsir": 0x2f,
    "Charmander": 0x30,
    "Charmeleon": 0x31,
    "Charizard": 0x32,
    "Vulpix": 0x33,
    "Ninetales Lv32": 0x34,
    "Ninetales Lv35": 0x35,
    "Growlithe": 0x36,
    "Arcanine Lv34": 0x37,
    "Arcanine Lv45": 0x38,
    "Ponyta": 0x39,
    "Rapidash": 0x3a,
    "Magmar Lv24": 0x3b,
    "Magmar Lv31": 0x3c,
    "Flareon Lv22": 0x3d,
    "Flareon Lv28": 0x3e,
    "Moltres Lv35": 0x3f,
    "Moltres Lv37": 0x40,
    "Squirtle": 0x41,
    "Wartortle": 0x42,
    "Blastoise": 0x43,
    "Psyduck": 0x44,
    "Golduck": 0x45,
    "Poliwag": 0x46,
    "Poliwhirl": 0x47,
    "Poliwrath": 0x48,
    "Tentacool": 0x49,
    "Tentacruel": 0x4a,
    "Seel": 0x4b,
    "Dewgong": 0x4c,
    "Shellder": 0x4d,
    "Cloyster": 0x4e,
    "Krabby": 0x4f,
    "Kingler": 0x50,
    "Horsea": 0x51,
    "Seadra": 0x52,
    "Goldeen": 0x53,
    "Seaking": 0x54,
    "Staryu": 0x55,
    "Starmie": 0x56,
    "Magikarp": 0x57,
    "Gyarados": 0x58,
    "Lapras": 0x59,
    "Vaporeon Lv29": 0x5a,
    "Vaporeon Lv42": 0x5b,
    "Omanyte": 0x5c,
    "Omastar": 0x5d,
    "Articuno Lv35": 0x5e,
    "Articuno Lv37": 0x5f,
    "Pikachu Lv12": 0x60,
    "Pikachu Lv14": 0x61,
    "Pikachu Lv16": 0x62,
    "Pikachu Alt Lv16": 0x63,
    "Flying Pikachu": 0x64,
    "Surfing Pikachu Lv13": 0x65,
    "Surfing Pikachu Alt Lv13": 0x66,
    "Raichu Lv40": 0x67,
    "Raichu Lv45": 0x68,
    "Magnemite Lv13": 0x69,
    "Magnemite Lv15": 0x6a,
    "Magneton Lv28": 0x6b,
    "Magneton Lv35": 0x6c,
    "Voltorb": 0x6d,
    "Electrode Lv35": 0x6e,
    "Electrode Lv42": 0x6f,
    "Electabuzz Lv20": 0x70,
    "Electabuzz Lv35": 0x71,
    "Jolteon Lv24": 0x72,
    "Jolteon Lv29": 0x73,
    "Zapdos Lv40": 0x74,
    "Zapdos Lv64": 0x75,
    "Zapdos Lv68": 0x76,
    "Sandshrew": 0x77,
    "Sandslash": 0x78,
    "Diglett": 0x79,
    "Dugtrio": 0x7a,
    "Mankey": 0x7b,
    "Primeape": 0x7c,
    "Machop": 0x7d,
    "Machoke": 0x7e,
    "Machamp": 0x7f,
    "Geodude": 0x80,
    "Graveler": 0x81,
    "Golem": 0x82,
    "Onix": 0x83,
    "Cubone": 0x84,
    "Marowak Lv26": 0x85,
    "Marowak Lv32": 0x86,
    "Hitmonlee": 0x87,
    "Hitmonchan": 0x88,
    "Rhyhorn": 0x89,
    "Rhydon": 0x8a,
    "Kabuto": 0x8b,
    "Kabutops": 0x8c,
    "Aerodactyl": 0x8d,
    "Abra": 0x8e,
    "Kadabra": 0x8f,
    "Alakazam": 0x90,
    "Slowpoke Lv9": 0x91,
    "Slowpoke Lv18": 0x92,
    "Slowbro": 0x93,
    "Gastly Lv8": 0x94,
    "Gastly Lv17": 0x95,
    "Haunter Lv17": 0x96,
    "Haunter Lv22": 0x97,
    "Gengar": 0x98,
    "Drowzee": 0x99,
    "Hypno": 0x9a,
    "Mr Mime": 0x9b,
    "Jynx": 0x9c,
    "Mewtwo Lv53": 0x9d,
    "Mewtwo Lv60": 0x9e,
    "Mewtwo Alt Lv60": 0x9f,
    "Mew Lv8": 0xa0,
    "Mew Lv15": 0xa1,
    "Mew Lv23": 0xa2,
    "Pidgey": 0xa3,
    "Pidgeotto": 0xa4,
    "Pidgeot Lv38": 0xa5,
    "Pidgeot Lv40": 0xa6,
    "Rattata": 0xa7,
    "Raticate": 0xa8,
    "Spearow": 0xa9,
    "Fearow": 0xaa,
    "Clefairy": 0xab,
    "Clefable": 0xac,
    "Jigglypuff Lv12": 0xad,
    "Jigglypuff Lv13": 0xae,
    "Jigglypuff Lv14": 0xaf,
    "Wigglytuff": 0xb0,
    "Meowth Lv14": 0xb1,
    "Meowth Lv15": 0xb2,
    "Persian": 0xb3,
    "Farfetchd": 0xb4,
    "Doduo": 0xb5,
    "Dodrio": 0xb6,
    "Lickitung": 0xb7,
    "Chansey": 0xb8,
    "Kangaskhan": 0xb9,
    "Tauros": 0xba,
    "Ditto": 0xbb,
    "Eevee": 0xbc,
    "Porygon": 0xbd,
    "Snorlax": 0xbe,
    "Dratini": 0xbf,
    "Dragonair": 0xc0,
    "Dragonite Lv41": 0xc1,
    "Dragonite Lv45": 0xc2,
    "Professor Oak": 0xc3,
    "Imposter Professor Oak": 0xc4,
    "Bill": 0xc5,
    "Mr Fuji": 0xc6,
    "Lass": 0xc7,
    "Imakuni Card": 0xc8,
    "Pokemon Trader": 0xc9,
    "Pokemon Breeder": 0xca,
    "Clefairy Doll": 0xcb,
    "Mysterious Fossil": 0xcc,
    "Energy Retrieval": 0xcd,
    "Super Energy Retrieval": 0xce,
    "Energy Search": 0xcf,
    "Energy Removal": 0xd0,
    "Super Energy Removal": 0xd1,
    "Switch": 0xd2,
    "Pokemon Center": 0xd3,
    "Poke Ball": 0xd4,
    "Scoop Up": 0xd5,
    "Computer Search": 0xd6,
    "Pokedex": 0xd7,
    "Pluspower": 0xd8,
    "Defender": 0xd9,
    "Item Finder": 0xda,
    "Gust Of Wind": 0xdb,
    "Devolution Spray": 0xdc,
    "Potion": 0xdd,
    "Super Potion": 0xde,
    "Full Heal": 0xdf,
    "Revive": 0xe0,
    "Maintenance": 0xe1,
    "Pokemon Flute": 0xe2,
    "Gambler": 0xe3,
    "Recycle": 0xe4,
}