evoline = {
    "Aerodactyl": ["Aerodactyle Pack"],
    "Mysterious Fossil": ["Aerodactyle Pack", "Kabutops Pack", "Omastar Pack"],
    "Alakazam": ["Alakazam Pack"],
    "Kadabra": ["Alakazam Pack"],
    "Abra": ["Alakazam Pack"],
    "Arbok": ["Arbok Pack"],
    "Ekans": ["Arbok Pack"],
    "Arcanine LV34": ["Arcanine 1 Pack"],
    "Growlithe": ["Arcanine 1 Pack", "Arcanine 2 Pack"],
    "Arcanine LV45": ["Arcanine 2 Pack"],
    "Articuno LV35": ["Articuno 1 Pack"],
    "Articuno LV37": ["Articuno 2 Pack"],
    "Beedrill": ["Beedrill Pack"],
    "Kakuna": ["Beedrill Pack"],
    "Weedle": ["Beedrill Pack"],
    "Blastoise": ["Blastoise Pack"],
    "Wartortle": ["Blastoise Pack"],
    "Squirtle": ["Blastoise Pack"],
    "Butterfree": ["Butterfree Pack"],
    "Metapod": ["Butterfree Pack"],
    "Caterpie": ["Butterfree Pack"],
    "Chansey": ["Chansey Pack"],
    "Charizard": ["Charizard Pack"],
    "Charmeleon": ["Charizard Pack"],
    "Charmander": ["Charizard Pack"],
    "Clefable": ["Clefable Pack"],
    "Clefairy": ["Clefable Pack"],
    "Cloyster": ["Cloyster Pack"],
    "Shellder": ["Cloyster Pack"],
    "Dewgong": ["Dewgong Pack"],
    "Seel": ["Dewgong Pack"],
    "Ditto": ["Ditto Pack"],
    "Dodrio": ["Dodrio Pack"],
    "Doduo": ["Dodrio Pack"],
    "Dragonite LV41": ["Dragonite 1 Pack"],
    "Dragonair": ["Dragonite 1 Pack", "Dragonite 2 Pack"],
    "Dratini": ["Dragonite 1 Pack", "Dragonite 2 Pack"],
    "Dragonite LV45": ["Dragonite 2 Pack"],
    "Dugtrio": ["Dugtrio Pack"],
    "Diglett": ["Dugtrio Pack"],
    "Electabuzz LV20": ["Electabuzz 1 Pack"],
    "Electabuzz LV35": ["Electabuzz 2 Pack"],
    "Electrode LV35": ["Electrode 1 Pack"],
    "Voltorb": ["Electrode 1 Pack", "Electrode 2 Pack"],
    "Electrode LV42": ["Electrode 2 Pack"],
    "Exeggutor": ["Exeggutor Pack"],
    "Exeggcute": ["Exeggutor Pack"],
    "Farfetchd": ["Farfetchd Pack"],
    "Fearow": ["Fearow Pack"],
    "Spearow": ["Fearow Pack"],
    "Flareon LV22": ["Flareon 1 Pack"],
    "Eevee": ["Flareon 1 Pack", "Flareon 2 Pack", "Jolteon 1 Pack", "Jolteon 2 Pack", "Vaporeon 1 Pack",
              "Vaporeon 2 Pack"],
    "Flareon LV28": ["Flareon 2 Pack"],
    "Flying Pikachu": ["Flying Pikachu Pack"],
    "Gengar": ["Gengar 1 Pack", "Gengar 2 Pack"],
    "Haunter LV22": ["Gengar 1 Pack"],
    "Gastly LV8": ["Gengar 1 Pack"],
    "Haunter LV17": ["Gengar 2 Pack"],
    "Gastly LV17": ["Gengar 2 Pack"],
    "Golbat": ["Golbat Pack"],
    "Zubat": ["Golbat Pack"],
    "Golduck": ["Golduck Pack"],
    "Psyduck": ["Golduck Pack"],
    "Golem": ["Golem Pack"],
    "Graveler": ["Golem Pack"],
    "Geodude": ["Golem Pack"],
    "Gyarados": ["Gyrados Pack"],
    "Magikarp": ["Gyrados Pack"],
    "Hitmonchan": ["Hitmonchan Pack"],
    "Hitmonlee": ["Hitmonlee Pack"],
    "Hypno": ["Hypno Pack"],
    "Drowzee": ["Hypno Pack"],
    "Jigglypuff LV12": ["Jigglypuff Promo Pack"],
    "Jolteon LV24": ["Jolteon 1 Pack"],
    "Jolteon LV29": ["Jolteon 2 Pack"],
    "Jynx": ["Jynx Pack"],
    "Kabutops": ["Kabutops Pack"],
    "Kabuto": ["Kabutops Pack"],
    "Kangaskhan": ["Kangaskhan Pack"],
    "Kingler": ["Kingler Pack"],
    "Krabby": ["Kingler Pack"],
    "Lapras": ["Lapras Pack"],
    "Lickitung": ["Lickitung Pack"],
    "Machamp": ["Machamp Pack"],
    "Machoke": ["Machamp Pack"],
    "Machop": ["Machamp Pack"],
    "Magmar LV24": ["Magmar 1 Pack"],
    "Magmar LV31": ["Magmar 2 Pack"],
    "Magneton LV28": ["Magneton 1 Pack"],
    "Magnemite LV13": ["Magneton 1 Pack"],
    "Magneton LV35": ["Magneton 2 Pack"],
    "Magnemite LV15": ["Magneton 2 Pack"],
    "Marowak LV26": ["Marowak 1 Pack"],
    "Cubone": ["Marowak 1 Pack", "Marowak 2 Pack"],
    "Marowak LV32": ["Marowak 2 Pack"],
    "Mew LV8": ["Mew 1 Pack"],
    "Mew LV15": ["Mew 2 Pack"],
    "Mew LV23": ["Mew 3 Pack"],
    "Mewtwo LV53": ["Mewtwo 1 Pack"],
    "Mewtwo LV60": ["Mewtwo 2 Pack"],
    "Mewtwo Alt LV60": ["Mewtwo 3 Pack"],
    "Moltres LV35": ["Moltres 1 Pack"],
    "Moltres LV37": ["Moltres 2 Pack"],
    "Mr Mime": ["Mr Mime Pack"],
    "Muk": ["Muk Pack"],
    "Grimer": ["Muk Pack"],
    "Nidoking": ["Nidoking Pack"],
    "Nidorino": ["Nidoking Pack"],
    "Nidoranm": ["Nidoking Pack"],
    "Nidoqueen": ["Nidoqueen Pack"],
    "Nidorina": ["Nidoqueen Pack"],
    "Nidoranf": ["Nidoqueen Pack"],
    "Ninetales LV32": ["Ninetales 1 Pack"],
    "Vulpix": ["Ninetales 1 Pack", "Ninetales 2 Pack"],
    "Ninetales LV35": ["Ninetales 2 Pack"],
    "Omastar": ["Omastar Pack"],
    "Omanyte": ["Omastar Pack"],
    "Onix": ["Onix Pack"],
    "Parasect": ["Parasect Pack"],
    "Paras": ["Parasect Pack"],
    "Persian": ["Persian 1 Pack", "Persian 2 Pack"],
    "Meowth LV14": ["Persian 1 Pack"],
    "Meowth LV15": ["Persian 2 Pack"],
    "Pidgeot LV38": ["Pidgeot 1 Pack"],
    "Pidgeotto": ["Pidgeot 1 Pack", "Pidgeot 2 Pack"],
    "Pidgey": ["Pidgeot 1 Pack", "Pidgeot 2 Pack"],
    "Pidgeot LV40": ["Pidgeot 2 Pack"],
    "Pinsir": ["Pinsir Pack"],
    "Poliwrath": ["Poliwrath Pack"],
    "Poliwhirl": ["Poliwrath Pack"],
    "Poliwag": ["Poliwrath Pack"],
    "Porygon": ["Porygon"],
    "Primeape": ["Primeape Pack"],
    "Mankey": ["Primeape Pack"],
    "Raichu LV40": ["Raichu 1 Pack", "Raichu 3 Pack"],
    "Pikachu LV12": ["Raichu 1 Pack"],
    "Raichu LV45": ["Raichu 2 Pack", "Raichu 4 Pack"],
    "Pikachu LV14": ["Raichu 2 Pack"],
    "Pikachu LV16": ["Raichu 3 Pack"],
    "Pikachu Alt LV16": ["Raichu 4 Pack"],
    "Rapidash": ["Rapidash Pack"],
    "Ponyta": ["Rapidash Pack"],
    "Raticate": ["Raticate Pack"],
    "Rattata": ["Raticate Pack"],
    "Rhydon": ["Rhydon Pack"],
    "Rhyhorn": ["Rhydon Pack"],
    "Sandslash": ["Sandslash Pack"],
    "Sandshrew": ["Sandslash Pack"],
    "Scyther": ["Scyther Pack"],
    "Seadra": ["Seadra Pack"],
    "Horsea": ["Seadra Pack"],
    "Seaking": ["Seaking Pack"],
    "Goldeen": ["Seaking Pack"],
    "Slowbro": ["Slowbro Pack"],
    "Slowpoke LV18": ["Slowbro Pack"],
    "Slowpoke LV9": ["Slowpoke Promo Pack"],
    "Snorlax": ["Snorlax Pack"],
    "Starmie": ["Starmie Pack"],
    "Staryu": ["Starmie Pack"],
    "Surfing Pikachu LV13": ["Surfing Pikachu 1 Pack"],
    "Surfing Pikachu Alt LV13": ["Surfing Pikachu 2 Pack"],
    "Tangela LV12": ["Tangela 1 Pack"],
    "Tangela LV8": ["Tangela 1 Pack"],
    "Tauros": ["Tauros Pack"],
    "Tentacruel": ["Tentacruel Pack"],
    "Tentacool": ["Tentacruel Pack"],
    "Vaporeon LV29": ["Vaporeon 1 Pack"],
    "Vaporeon LV42": ["Vaporeon 2 Pack"],
    "Venomoth": ["Venomoth Pack"],
    "Venonat": ["Venomoth Pack"],
    "Venusaur LV64": ["Venusaur 1 Pack"],
    "Ivysaur": ["Venusaur 1 Pack", "Venusaur 2 Pack"],
    "Bulbasaur": ["Venusaur 1 Pack", "Venusaur 2 Pack"],
    "Venusaur LV67": ["Venusaur 2 Pack"],
    "Victreebel": ["Victreebel Pack"],
    "Weepinbell": ["Victreebel Pack"],
    "Bellsprout": ["Victreebel Pack"],
    "Vileplume": ["Vileplume Pack"],
    "Gloom": ["Vileplume Pack"],
    "Oddish": ["Vileplume Pack"],
    "Weezing": ["Weezing Pack"],
    "Koffing": ["Weezing Pack"],
    "Wigglytuff": ["Wigglytuff 1 Pack", "Wigglytuff 2 Pack"],
    "Jigglypuff LV13": ["Wigglytuff 1 Pack"],
    "Jigglypuff LV14": ["Wigglytuff 2 Pack"],
    "Zapdos LV40": ["Zapdos 1 Pack"],
    "Zapdos LV64": ["Zapdos 2 Pack"],
    "Zapdos LV68": ["Zapdos 3 Pack"],

    "Clefairy Doll": ["Clefairy Doll Pack"],
    "Defender": ["Defender Pack"],
    "Devolution Spray": ["Devolution Spray Pack"],
    "Energy Removal": ["Energy Removal Pack"],
    "Energy Retrieval": ["Energy Retrieval Pack"],
    "Energy Search": ["Energy Search Pack"],
    "Full Heal": ["Full Heal Pack"],
    "Gambler": ["Gambler Pack"],
    "Imakuni Card": ["Imakuni? Pack"],
    "Imposter Professor Oak": ["Imposter Professor Oak Pack"],
    "Item Finder": ["Item Finder Pack"],
    "Lass": ["Lass Pack"],
    "Maintenance": ["Maintenance Pack"],
    "Mr Fuji": ["Mr Fuji Pack"],
    "Poke Ball": ["Poke Ball Pack"],
    "Pokedex": ["Pokedex Pack"],
    "Pokemon Breeder": ["Pokemon Breeder Pack"],
    "Pokemon Center": ["Pokemon Center Pack"],
    "Pokemon Flute": ["Pokemon Flute Pack"],
    "Pokemon Trader": ["Pokemon Trader Pack"],
    "Potion": ["Potion Pack"],
    "Recycle": ["Recycle Pack"],
    "Revive": ["Revive Pack"],
    "Scoop Up": ["Scoop Up Pack"],
    "Super Energy Retrieval": ["Super Energy Retrieval Pack"],
    "Super Potion": ["Super Potion Pack"],
    "Switch": ["Switch Pack"],

    "Computer Search": ["Computer Search Pack"],
    "Gust  of Wind": ["Gust  of Wind Pack"],
    "Pluspower": ["Pluspower Pack"],

    "Bill": ["Bill Pack"],
    "Professor Oak": ["Professor Oak Pack"],
    "Super Energy Removal": ["Super Energy Removal Pack"],
    "Double Colorless Energy": ["Double Colorless Energy Pack"],
    "Water Energy": ["Starting Deck"],
    "Fire Energy": ["Starting Deck"],
    "Grass Energy": ["Starting Deck"],
    "Lightning Energy": ["Starting Deck"],
    "Fighting Energy": ["Starting Deck"],
    "Psychic Energy": ["Starting Deck"]
}

card_list = [
    "Aerodactyl", "Mysterious Fossil", "Alakazam", "Kadabra", "Abra", "Arbok", "Ekans", "Arcanine LV34", "Growlithe",
    "Arcanine LV45", "Articuno LV35", "Articuno LV37", "Beedrill", "Kakuna", "Weedle", "Blastoise", "Wartortle",
    "Squirtle", "Butterfree", "Metapod", "Caterpie", "Chansey", "Charizard", "Charmeleon", "Charmander", "Clefable",
    "Clefairy", "Cloyster", "Shellder", "Dewgong", "Seel", "Ditto", "Dodrio", "Doduo", "Dragonite LV41",
    "Dragonair", "Dratini", "Dragonite LV45", "Dugtrio", "Diglett", "Electabuzz LV20", "Electabuzz LV35",
    "Electrode LV35", "Voltorb", "Electrode LV42", "Exeggutor", "Exeggcute", "Farfetchd", "Fearow", "Spearow",
    "Flareon LV22", "Eevee", "Flareon LV28", "Flying Pikachu", "Gengar", "Haunter LV22", "Gastly LV8", "Haunter LV17",
    "Gastly LV17", "Golbat", "Zubat", "Golduck", "Psyduck", "Golem", "Graveler", "Geodude", "Gyarados", "Magikarp",
    "Hitmonchan", "Hitmonlee", "Hypno", "Drowzee", "Jigglypuff LV12", "Jolteon LV24", "Jolteon LV29", "Jynx", "Kabutops",
    "Kabuto", "Kangaskhan", "Kingler", "Krabby", "Lapras", "Lickitung", "Machamp", "Machoke", "Machop", "Magmar LV24",
    "Magmar LV31", "Magneton LV28", "Magnemite LV13", "Magneton LV35", "Magnemite LV15", "Marowak LV26", "Cubone",
    "Marowak LV32", "Mew LV8", "Mew LV15", "Mew LV23", "Mewtwo LV53", "Mewtwo LV60", "Mewtwo Alt LV60", "Moltres LV35",
    "Moltres LV37", "Mr Mime", "Muk", "Grimer", "Nidoking", "Nidorino", "Nidoranm", "Nidoqueen", "Nidorina",
    "Nidoranf", "Ninetales LV32", "Vulpix", "Ninetales LV35", "Omastar", "Omanyte", "Onix", "Parasect", "Paras",
    "Persian", "Meowth LV14", "Meowth LV15", "Pidgeot LV38", "Pidgeotto", "Pidgey", "Pidgeot LV40", "Pinsir",
    "Poliwrath", "Poliwhirl", "Poliwag", "Porygon", "Primeape", "Mankey", "Raichu LV40", "Pikachu LV12", "Raichu LV45",
    "Pikachu LV14", "Pikachu LV16", "Pikachu Alt LV16", "Rapidash", "Ponyta", "Raticate", "Rattata", "Rhydon",
    "Rhyhorn", "Sandslash", "Sandshrew", "Scyther", "Seadra", "Horsea", "Seaking", "Goldeen", "Slowbro", "Slowpoke LV18",
    "Slowpoke LV9", "Snorlax", "Starmie", "Staryu", "Surfing Pikachu LV13", "Surfing Pikachu Alt LV13", "Tangela LV12",
    "Tangela LV8", "Tauros", "Tentacruel", "Tentacool", "Vaporeon LV29", "Vaporeon LV42", "Venomoth", "Venonat",
    "Venusaur LV64", "Ivysaur", "Bulbasaur", "Venusaur LV67", "Victreebel", "Weepinbell", "Bellsprout", "Vileplume",
    "Gloom", "Oddish", "Weezing", "Koffing", "Wigglytuff", "Jigglypuff LV13", "Jigglypuff LV14", "Zapdos LV40",
    "Zapdos LV64", "Zapdos LV68",
    "Clefairy Doll", "Defender", "Devolution Spray", "Energy Removal", "Energy Retrieval", "Energy Search",
    "Full Heal", "Gambler", "Imakuni Card", "Imposter Professor Oak", "Item Finder", "Lass", "Maintenance",
    "Mr Fuji", "Poke Ball", "Pokedex", "Pokemon Breeder", "Pokemon Center", "Pokemon Flute", "Pokemon Trader",
    "Potion", "Recycle", "Revive", "Scoop Up", "Super Energy Retrieval", "Super Potion", "Switch",
    "Computer Search", "Gust  of Wind", "Pluspower",
    "Bill", "Professor Oak", "Super Energy Removal", "Double Colorless Energy",
    "Water Energy", "Fire Energy", "Grass Energy", "Lightning Energy", "Fighting Energy", "Psychic Energy"
]
