char_and_friends = {
    "Caterpie": 2,
    "Metapod": 1,
    "Nidoranf": 2,
    "Nidoranm": 1,
    "Pinsir": 1,
    "Charmander": 2,
    "Charmeleon": 1,
    "Charizard": 1,
    "Growlithe": 2,
    "Arcanine Lv45": 1,
    "Ponyta": 2,
    "Magmar Lv24": 1,
    "Seel": 2,
    "Dewgong": 1,
    "Goldeen": 2,
    "Seaking": 1,
    "Rattata": 2,
    "Raticate": 1,
    "Meowth Lv13": 1,
    "Professor Oak": 1,
    "Bill": 2,
    "Switch": 1,
    "Computer Search": 1,
    "PlusPower": 1,
    "Potion": 2,
    "Full Heal": 1,
    "Fire Energy": 10,
    "Grass Energy": 8,
    "Water Energy": 6
}

squirt_and_friends = {
    "Charmander": 2,
    "Charmeleon": 1,
    "Growlithe": 1,
    "Arcanine Lv45": 1,
    "Magmar Lv24": 1,
    "Squirtle": 2,
    "Wartortle": 1,
    "Blastoise": 1,
    "Seel": 2,
    "Dewgong": 1,
    "Goldeen": 1,
    "Seaking": 1,
    "Staryu": 1,
    "Starmie": 1,
    "Lapras": 1,
    "Pikachu Lv12": 2,
    "Magnemite Lv13": 1,
    "Magneton Lv28": 1,
    "Electabuzz Lv35": 1,
    "Rattata": 2,
    "Raticate": 1,
    "Meowth Lv13": 1,
    "Professor Oak": 1,
    "Bill": 1,
    "Switch": 1,
    "Poke Ball": 1,
    "Scoop Up": 1,
    "Item Finder": 1,
    "Potion": 1,
    "Full Heal": 1,
    "Water Energy": 11,
    "Fire Energy": 8,
    "Lightning Energy": 6
}

bulb_and_friends = {
    "Bulbasaur": 2,
    "Ivysaur": 1,
    "Venusaur Lv67": 1,
    "Nidoranf": 2,
    "Nidoranm": 2,
    "Nidorino": 1,
    "Tangela Lv12": 1,
    "Pikachu Lv12": 2,
    "Raichu Lv40": 1,
    "Magnemite Lv13": 1,
    "Electabuzz Lv35": 1,
    "Abra": 2,
    "Kadabra": 1,
    "Gastly Lv8": 2,
    "Haunter Lv22": 1,
    "Jynx": 1,
    "Jigglypuff Lv14": 1,
    "Meowth Lv13": 1,
    "Kangaskhan": 1,
    "Professor Oak": 1,
    "Bill": 1,
    "Switch": 1,
    "Poke Ball": 1,
    "PlusPower": 2,
    "Defender": 1,
    "Gust of Wind": 1,
    "Potion": 2,
    "Full Heal": 2,
    "Grass Energy": 9,
    "Lightning Energy": 8,
    "Psychic Energy": 6
}

psychic_machamp = {
    "Diglett": 2,
    "Dugtrio": 1,
    "Machop": 2,
    "Machoke": 1,
    "Machamp": 1,
    "Onix": 1,
    "Hitmonlee": 1,
    "Hitmonchan": 1,
    "Abra": 2,
    "Kadabra": 1,
    "Alakazam": 1,
    "Gastly Lv8": 2,
    "Haunter Lv22": 1,
    "Gengar": 1,
    "Mr Mime": 1,
    "Jynx": 1,
    "Mew Lv23": 1,
    "Pidgey": 2,
    "Pidgeotto": 1,
    "Pidgeot Lv40": 1,
    "Rattata": 2,
    "Raticate": 1,
    "Professor Oak": 1,
    "Bill": 2,
    "Switch": 1,
    "Gust of Wind": 1,
    "Potion": 2,
    "Full Heal": 1,
    "Fighting Energy": 12,
    "Psychic Energy": 12
}

water_beetle = {
    "Weedle": 2,
    "Kakuna": 1,
    "Beedrill": 1,
    "Nidoranm": 2,
    "Nidorino": 1,
    "Nidoking": 1,
    "Bellsprout": 2,
    "Weepinbell": 1,
    "Victreebel": 1,
    "Scyther": 1,
    "Poliwag": 2,
    "Poliwhirl": 1,
    "Poliwrath": 1,
    "Krabby": 2,
    "Kingler": 1,
    "Magikarp": 2,
    "Gyarados": 1,
    "Lapras": 1,
    "Articuno Lv35": 1,
    "Lickitung": 1,
    "Kangaskhan": 1,
    "Tauros": 1,
    "Professor Oak": 1,
    "Bill": 2,
    "Energy Retrieval": 1,
    "Energy Search": 1,
    "Switch": 1,
    "PlusPower": 1,
    "Full Heal": 1,
    "Grass Energy": 14,
    "Water Energy": 10
}

insect_collection = {
    "Caterpie": 3,
    "Metapod": 2,
    "Butterfree": 1,
    "Weedle": 3,
    "Kakuna": 2,
    "Beedrill": 1,
    "Paras": 4,
    "Parasect": 3,
    "Venonat": 2,
    "Venomoth": 1,
    "Scyther": 1,
    "Pinsir": 1,
    "Bill": 2,
    "Pokemon Breeder": 2,
    "Switch": 2,
    "Poke Ball": 2,
    "Pokedex": 2,
    "Potion": 2,
    "Grass Energy": 24
}

jungle = {
    "Ekans": 2,
    "Arbok": 1,
    "Zubat": 2,
    "Golbat": 1,
    "Oddish": 2,
    "Gloom": 1,
    "Vileplume": 1,
    "Paras": 2,
    "Parasect": 1,
    "Venonat": 2,
    "Venomoth": 1,
    "Bellsprout": 2,
    "Weepinbell": 1,
    "Victreebel": 1,
    "Pinsir": 1,
    "Lickitung": 1,
    "Kangaskhan": 1,
    "Bill": 2,
    "Switch": 1,
    "Poke Ball": 1,
    "PlusPower": 2,
    "Defender": 2,
    "Potion": 2,
    "Full Heal": 1,
    "Double Colorless Energy": 1,
    "Grass Energy": 25
}

flower_garden = {
    "Bulbasaur": 3,
    "Ivysaur": 2,
    "Venusaur Lv67": 2,
    "Oddish": 3,
    "Gloom": 2,
    "Vileplume": 2,
    "Bellsprout": 2,
    "Weepinbell": 1,
    "Victreebel": 1,
    "Tangela Lv12": 2,
    "Tangela Lv8": 1,
    "Lickitung": 2,
    "Pokemon Trader": 2,
    "Pokemon Breeder": 3,
    "Energy Search": 1,
    "Switch": 2,
    "Potion": 2,
    "Full Heal": 1,
    "Double Colorless Energy": 2,
    "Grass Energy": 24
}
