char_and_friends = {
    "Caterpie": 2,
    "Metapod": 1,
    "Nidoranf": 2,
    "Nidoranm": 1,
    "Pinsir": 1,
    "Charmander": 2,
    "Charmeleon": 1,
    "Charizard": 1,
    "Growlithe": 2,
    "Arcanine Lv45": 1,
    "Ponyta": 2,
    "Magmar Lv24": 1,
    "Seel": 2,
    "Dewgong": 1,
    "Goldeen": 2,
    "Seaking": 1,
    "Rattata": 2,
    "Raticate": 1,
    "Meowth Lv13": 1,
    "Professor Oak": 1,
    "Bill": 2,
    "Switch": 1,
    "Computer Search": 1,
    "PlusPower": 1,
    "Potion": 2,
    "Full Heal": 1,
    "Fire Energy": 10,
    "Grass Energy": 8,
    "Water Energy": 6
}

squirt_and_friends = {
    "Charmander": 2,
    "Charmeleon": 1,
    "Growlithe": 1,
    "Arcanine Lv45": 1,
    "Magmar Lv24": 1,
    "Squirtle": 2,
    "Wartortle": 1,
    "Blastoise": 1,
    "Seel": 2,
    "Dewgong": 1,
    "Goldeen": 1,
    "Seaking": 1,
    "Staryu": 1,
    "Starmie": 1,
    "Lapras": 1,
    "Pikachu Lv12": 2,
    "Magnemite Lv13": 1,
    "Magneton Lv28": 1,
    "Electabuzz Lv35": 1,
    "Rattata": 2,
    "Raticate": 1,
    "Meowth Lv13": 1,
    "Professor Oak": 1,
    "Bill": 1,
    "Switch": 1,
    "Poke Ball": 1,
    "Scoop Up": 1,
    "Item Finder": 1,
    "Potion": 1,
    "Full Heal": 1,
    "Water Energy": 11,
    "Fire Energy": 8,
    "Lightning Energy": 6
}

bulb_and_friends = {
    "Bulbasaur": 2,
    "Ivysaur": 1,
    "Venusaur Lv67": 1,
    "Nidoranf": 2,
    "Nidoranm": 2,
    "Nidorino": 1,
    "Tangela Lv12": 1,
    "Pikachu Lv12": 2,
    "Raichu Lv40": 1,
    "Magnemite Lv13": 1,
    "Electabuzz Lv35": 1,
    "Abra": 2,
    "Kadabra": 1,
    "Gastly Lv8": 2,
    "Haunter Lv22": 1,
    "Jynx": 1,
    "Jigglypuff Lv14": 1,
    "Meowth Lv13": 1,
    "Kangaskhan": 1,
    "Professor Oak": 1,
    "Bill": 1,
    "Switch": 1,
    "Poke Ball": 1,
    "PlusPower": 2,
    "Defender": 1,
    "Gust of Wind": 1,
    "Potion": 2,
    "Full Heal": 2,
    "Grass Energy": 9,
    "Lightning Energy": 8,
    "Psychic Energy": 6
}

psychic_machamp = {
    "Diglett": 2,
    "Dugtrio": 1,
    "Machop": 2,
    "Machoke": 1,
    "Machamp": 1,
    "Onix": 1,
    "Hitmonlee": 1,
    "Hitmonchan": 1,
    "Abra": 2,
    "Kadabra": 1,
    "Alakazam": 1,
    "Gastly Lv8": 2,
    "Haunter Lv22": 1,
    "Gengar": 1,
    "Mr Mime": 1,
    "Jynx": 1,
    "Mew Lv23": 1,
    "Pidgey": 2,
    "Pidgeotto": 1,
    "Pidgeot Lv40": 1,
    "Rattata": 2,
    "Raticate": 1,
    "Professor Oak": 1,
    "Bill": 2,
    "Switch": 1,
    "Gust of Wind": 1,
    "Potion": 2,
    "Full Heal": 1,
    "Fighting Energy": 12,
    "Psychic Energy": 12
}

water_beetle = {
    "Weedle": 2,
    "Kakuna": 1,
    "Beedrill": 1,
    "Nidoranm": 2,
    "Nidorino": 1,
    "Nidoking": 1,
    "Bellsprout": 2,
    "Weepinbell": 1,
    "Victreebel": 1,
    "Scyther": 1,
    "Poliwag": 2,
    "Poliwhirl": 1,
    "Poliwrath": 1,
    "Krabby": 2,
    "Kingler": 1,
    "Magikarp": 2,
    "Gyarados": 1,
    "Lapras": 1,
    "Articuno Lv35": 1,
    "Lickitung": 1,
    "Kangaskhan": 1,
    "Tauros": 1,
    "Professor Oak": 1,
    "Bill": 2,
    "Energy Retrieval": 1,
    "Energy Search": 1,
    "Switch": 1,
    "PlusPower": 1,
    "Full Heal": 1,
    "Grass Energy": 14,
    "Water Energy": 10
}

insect_collection = {
    "Caterpie": 3,
    "Metapod": 2,
    "Butterfree": 1,
    "Weedle": 3,
    "Kakuna": 2,
    "Beedrill": 1,
    "Paras": 4,
    "Parasect": 3,
    "Venonat": 2,
    "Venomoth": 1,
    "Scyther": 1,
    "Pinsir": 1,
    "Bill": 2,
    "Pokemon Breeder": 2,
    "Switch": 2,
    "Poke Ball": 2,
    "Pokedex": 2,
    "Potion": 2,
    "Grass Energy": 24
}

jungle = {
    "Ekans": 2,
    "Arbok": 1,
    "Zubat": 2,
    "Golbat": 1,
    "Oddish": 2,
    "Gloom": 1,
    "Vileplume": 1,
    "Paras": 2,
    "Parasect": 1,
    "Venonat": 2,
    "Venomoth": 1,
    "Bellsprout": 2,
    "Weepinbell": 1,
    "Victreebel": 1,
    "Pinsir": 1,
    "Lickitung": 1,
    "Kangaskhan": 1,
    "Bill": 2,
    "Switch": 1,
    "Poke Ball": 1,
    "PlusPower": 2,
    "Defender": 2,
    "Potion": 2,
    "Full Heal": 1,
    "Double Colorless Energy": 1,
    "Grass Energy": 25
}

flower_garden = {
    "Bulbasaur": 3,
    "Ivysaur": 2,
    "Venusaur Lv67": 2,
    "Oddish": 3,
    "Gloom": 2,
    "Vileplume": 2,
    "Bellsprout": 2,
    "Weepinbell": 1,
    "Victreebel": 1,
    "Tangela Lv12": 2,
    "Tangela Lv8": 1,
    "Lickitung": 2,
    "Pokemon Trader": 2,
    "Pokemon Breeder": 3,
    "Energy Search": 1,
    "Switch": 2,
    "Potion": 2,
    "Full Heal": 1,
    "Double Colorless Energy": 2,
    "Grass Energy": 24
}

kaleidoscope = {
    "Venonat": 3,
    "Venomoth": 2,
    "Flareon Lv22": 1,
    "Flareon Lv28": 1,
    "Vaporeon Lv29": 1,
    "Vaporeon Lv42": 1,
    "Jolteon Lv24": 1,
    "Jolteon Lv29": 1,
    "Ditto": 4,
    "Eevee": 4,
    "Porygon": 4,
    "Bill": 2,
    "Mr Fuji": 2,
    "Energy Search": 2,
    "Switch": 4,
    "Gust of Wind": 2,
    "Double Colorless Energy": 3,
    "Grass Energy": 10,
    "Fire Energy": 4,
    "Water Energy": 4,
    "Lightning Energy": 4
}

flower_power = {
    "Bulbasaur": 4,
    "Ivysaur": 3,
    "Venusaur Lv67": 2,
    "Oddish": 4,
    "Gloom": 3,
    "Vileplume": 2,
    "Exeggcute": 4,
    "Exeggutor": 3,
    "Professor Oak": 2,
    "Bill": 3,
    "Pokemon Breeder": 2,
    "Energy Retrieval": 2,
    "Switch": 2,
    "Potion": 2,
    "Grass Energy": 18,
    "Psychic Energy": 4
}

lovely_nidoran = {
    "Nidoranf": 4,
    "Nidorina": 2,
    "Nidoqueen": 2,
    "Nidoranm": 3,
    "Nidorino": 2,
    "Nidoking": 1,
    "Grimer": 2,
    "Muk": 1,
    "Koffing": 2,
    "Weezing": 1,
    "Pinsir": 1,
    "Meowth Lv15": 2,
    "Farfetch'd": 2,
    "Doduo": 2,
    "Professor Oak": 1,
    "Bill": 2,
    "Pokemon Breeder": 2,
    "Switch": 1,
    "Poke Ball": 2,
    "Gambler": 1,
    "Grass Energy": 24
}

science_corp = {
    "Ekans": 2,
    "Arbok": 1,
    "Nidoranf": 2,
    "Nidorina": 1,
    "Nidoqueen": 1,
    "Nidoranm": 3,
    "Nidorino": 2,
    "Nidoking": 1,
    "Zubat": 2,
    "Golbat": 1,
    "Grimer": 2,
    "Muk": 1,
    "Koffing": 2,
    "Weezing": 1,
    "Meowth Lv15": 2,
    "Persian": 1,
    "Professor Oak": 1,
    "Bill": 1,
    "Pokemon Trader": 1,
    "Pokemon Breeder": 1,
    "Potion": 1,
    "Full Heal": 1,
    "Maintenance": 1,
    "Gambler": 1,
    "Recycle": 1,
    "Grass Energy": 26
}

flyin_pokemon = {
    "Zubat": 4,
    "Golbat": 3,
    "Flying Pikachu": 2,
    "Pidgey": 4,
    "Pidgeotto": 3,
    "Pidgeot Lv38": 1,
    "Pidgeot Lv40": 1,
    "Spearow": 4,
    "Fearow": 3,
    "Impostor Professor Oak": 2,
    "Lass": 2,
    "Bill": 2,
    "Potion": 4,
    "Double Colorless Energy": 2,
    "Grass Energy": 13,
    "Lightning Energy": 10
}

poison = {
    "Weedle": 3,
    "Kakuna": 2,
    "Beedrill": 1,
    "Ekands": 4,
    "Arbok": 3,
    "Nidoranm": 4,
    "Nidorino": 3,
    "Nidoking": 2,
    "Koffing": 3,
    "Weezing": 2,
    "Professor Oak": 1,
    "Impostor Professor Oak": 2,
    "Pokemon Breeder": 1,
    "Potion": 2,
    "Full Heal": 2,
    "Gambler": 1,
    "Grass Energy": 24
}

wonders_of_science = {
    "Grimer": 4,
    "Muk": 3,
    "Koffing": 4,
    "Weezing": 3,
    "Mewtwo Lv53": 2,
    "Mewtwo Lv60": 2,
    "Porygon": 2,
    "Impostor Professor Oak": 1,
    "Professor Oak": 2,
    "Bill": 2,
    "Energy Search": 2,
    "Switch": 2,
    "Computer Search": 2,
    "Pokedex": 2,
    "Maintenance": 2,
    "Full Heal": 2,
    "Grass Energy": 15,
    "Psychic Energy": 8
}

replace_em = {
    "Vulpix": 4,
    "Ninetales Lv32": 2,
    "Ninetales Lv35": 1,
    "Growlithe": 4,
    "Arcanine Lv34": 1,
    "Arcanine Lv45": 1,
    "Pidgey": 4,
    "Pidgeotto": 3,
    "Pidgeot Lv38": 1,
    "Pidgeot Lv40": 1,
    "Doduo": 3,
    "Dodrio": 2,
    "Professor Oak": 2,
    "Impostor Professor Oak": 2,
    "Lass": 2,
    "Gust of Wind": 3,
    "Fire Energy": 24
}

chari_saur = {
    "Bulbasaur": 4,
    "Ivysaur": 3,
    "Venusaur Lv67": 2,
    "Charmander": 4,
    "Charmeleon": 3,
    "Charizard": 2,
    "Flareon Lv22": 3,
    "Eevee": 4,
    "Bill": 2,
    "Pokemon Trader": 3,
    "Pokemon Breeder": 3,
    "Energy Retrieval": 2,
    "Energy Removal": 1,
    "Potion": 2,
    "Grass Energy": 12,
    "Fire Energy": 10
}

traffic_light = {
    "Charmander": 3,
    "Charmeleon": 2,
    "Ponyta": 3,
    "Rapidash": 2,
    "Flareon Lv22": 2,
    "Vaporeon Lv29": 2,
    "Pikachu Lv12": 2,
    "Voltorb": 3,
    "Electrode Lv42": 2,
    "Jolteon Lv24": 2,
    "Eevee": 4,
    "Energy Search": 2,
    "Switch": 2,
    "PlusPower": 3,
    "Fire Energy": 10,
    "Water Energy": 8,
    "Lightning Energy": 8
}

fire_pokemon = {
    "Charmander": 3,
    "Charmeleon": 2,
    "Charizard": 1,
    "Vulpix": 1,
    "Ninetales Lv32": 1,
    "Ninetales Lv35": 1,
    "Growlithe": 2,
    "Arcanine Lv45": 1,
    "Ponyta": 2,
    "Rapidash": 1,
    "Magmar Lv24": 1,
    "Magmar Lv31": 1,
    "Flareon Lv22": 1,
    "Flareon Lv28": 1,
    "Moltres Lv35": 1,
    "Eevee": 3,
    "Professor Oak": 1,
    "Bill": 2,
    "Pokemon Trader": 1,
    "Pokemon Breeder": 1,
    "Energy Retrieval": 1,
    "Super Energy Retrieval": 1,
    "Switch": 1,
    "Gust of Wind": 1,
    "Double Colorless Energy": 2,
    "Fire Energy": 24
}

fire_charge = {
    "Growlithe": 4,
    "Arcanine Lv45": 3,
    "Magmar Lv24": 2,
    "Jigglypuff Lv12": 3,
    "Jigglypuff Lv14": 1,
    "Wigglytuff": 1,
    "Chansey": 2,
    "Tauros": 2,
    "Professor Oak": 1,
    "Bill": 2,
    "Energy Retrieval": 2,
    "Poke Ball": 1,
    "Computer Search": 1,
    "Defender": 2,
    "Potion": 3,
    "Full Heal": 1,
    "Recycle": 3,
    "Gambler": 1,
    "Double Colorless Energy": 4,
    "Fire Energy": 21
}

blue_water = {
    "Psyduck": 2,
    "Golduck": 1,
    "Poliwag": 2,
    "Poliwhirl": 1,
    "Poliwrath": 1,
    "Seel": 2,
    "Dewgong": 1,
    "Shellder": 2,
    "Cloyster": 1,
    "Krabby": 2,
    "Kingler": 1,
    "Horsea": 2,
    "Seadra": 1,
    "Magikarp": 1,
    "Gyarados": 1,
    "Lapras": 1,
    "Omanyte": 1,
    "Omastar": 1,
    "Articuno Lv35": 1,
    "Professor Oak": 1,
    "Bill": 2,
    "Pokemon Trader": 1,
    "Mysterious Fossil": 2,
    "Energy Search": 1,
    "Poke Ball": 1,
    "Potion": 1,
    "Super Potion": 1,
    "Water Energy": 25
}

on_the_beach = {
    "Seel": 2,
    "Dewgong": 1,
    "Shellder": 3,
    "Cloyster": 2,
    "Krabby": 3,
    "Kingler": 2,
    "Staryu": 3,
    "Starmie": 2,
    "Sandshrew": 3,
    "Sandslash": 2,
    "Bill": 2,
    "Energy Retrieval": 2,
    "Energy Removal": 2,
    "Gust of Wind": 2,
    "Potion": 3,
    "Water Energy": 16,
    "Fighting Energy": 10
}

paralyze = {
    "Caterpie": 3,
    "Metapod": 2,
    "Squirtle": 3,
    "Wartortle": 2,
    "Shellder": 3,
    "Cloyster": 2,
    "Staryu": 4,
    "Starmie": 3,
    "Professor Oak": 2,
    "Bill": 2,
    "PlusPower": 2,
    "Defender": 2,
    "Potion": 2,
    "Double Colorless Energy": 4,
    "Grass Energy": 8,
    "Water Energy": 14
}

energy_removal = {
    "Psyduck": 3,
    "Golduck": 2,
    "Poliwag": 4,
    "Poliwhirl": 3,
    "Poliwrath": 2,
    "Gastly Lv17": 4,
    "Haunter Lv17": 3,
    "Dratini": 3,
    "Dragonair": 2,
    "Professor Oak": 1,
    "Bill": 1,
    "Lass": 1,
    "Energy Search": 2,
    "Energy Retrieval": 2,
    "Super Energy Retrieval": 1,
    "Double Colorless Energy": 3,
    "Water Energy": 15,
    "Psychic Energy": 8
}

rain_dancer = {
    "Squirtle": 4,
    "Wartortle": 3,
    "Blastoise": 2,
    "Goldeen": 4,
    "Seaking": 3,
    "Horsea": 3,
    "Seadra": 2,
    "Lapras": 2,
    "Professor Oak": 2,
    "Pokemon Breeder": 1,
    "Energy Retrieval": 2,
    "Super Energy Retrieval": 1,
    "Energy Removal": 2,
    "Super Energy Removal": 1,
    "Switch": 2,
    "Potion": 2,
    "Gambler": 1,
    "Water Energy": 24
}

cute_pokemon = {
    "Flareon Lv28": 1,
    "Vaporeon Lv42": 1,
    "Pikachu Lv12": 1,
    "Pikachu Lv14": 1,
    "Pikachu Lv16": 2,
    "Flying Pikachu": 1,
    "Surfing Pikachu Lv13": 2,
    "Raichu Lv40": 1,
    "Raichu Lv45": 1,
    "Jolteon Lv29": 1,
    "Clefairy": 2,
    "Clefable": 1,
    "Jigglypuff Lv12": 1,
    "Jigglypuff Lv13": 2,
    "Jigglypuff Lv14": 1,
    "Wigglytuff": 2,
    "Eevee": 4,
    "Professor Oak": 2,
    "Bill": 3,
    "Clefairy Doll": 2,
    "Scoop Up": 2,
    "Computer Search": 1,
    "PlusPower": 1,
    "Defender": 1,
    "Potion": 3,
    "Double Colorless Energy": 2,
    "Fire Energy": 4,
    "Water Energy": 6,
    "Lightning Energy": 8
}

yellow_flash = {
    "Pikachu Lv12": 2,
    "Pikachu Lv14": 1,
    "Raichu Lv40": 1,
    "Raichu Lv45": 1,
    "Magnemite Lv13": 2,
    "Magnemite Lv15": 1,
    "Magneton Lv28": 1,
    "Magneton Lv35": 1,
    "Voltorb": 3,
    "Electrode Lv35": 1,
    "Electrode Lv42": 1,
    "Electabuzz Lv20": 1,
    "Electabuzz Lv35": 1,
    "Jolteon Lv24": 1,
    "Jolteon Lv29": 1,
    "Zapdos Lv40": 1,
    "Zapdos Lv64": 1,
    "Eevee": 3,
    "Energy Retrieval": 1,
    "Energy Removal": 2,
    "Poke Ball": 2,
    "PlusPower": 2,
    "Defender": 2,
    "Gust of Wind": 1,
    "Lightning Energy": 26
}

electric_shock = {
    "Pikachu Lv14": 2,
    "Pikachu Lv16": 1,
    "Pikachu Alt Lv16": 1,
    "Raichu Lv40": 2,
    "Magnemite Lv13": 2,
    "Magnemite Lv15": 2,
    "Magneton Lv28": 2,
    "Voltorb": 4,
    "Electrode Lv42": 3,
    "Zapdos Lv64": 1,
    "Porygon": 3,
    "Gust of Wind": 3,
    "Item Finder": 2,
    "Defender": 3,
    "Energy Retrieval": 2,
    "PlusPower": 2,
    "Double Colorless Energy": 1,
    "Lightning Energy": 24
}

zapping_selfdestruct = {
    "Magnemite Lv13": 4,
    "Magneton Lv28": 3,
    "Voltorb": 4,
    "Electrode Lv35": 2,
    "Electabuzz Lv35": 4,
    "Kangaskhan": 2,
    "Tauros": 1,
    "Professor Oak": 1,
    "Bill": 2,
    "Switch": 2,
    "Defender": 4,
    "Gust of Wind": 1,
    "Potion": 4,
    "Double Colorless Energy": 2,
    "Lightning Energy": 24
}

psychic_power = {
    "Abra": 3,
    "Kadabra": 2,
    "Alakazam": 1,
    "Slowpoke Lv18": 2,
    "Slowbro": 1,
    "Gastly Lv8": 1,
    "Gastly Lv17": 2,
    "Haunter Lv17": 1,
    "Haunter Lv22": 1,
    "Gengar": 1,
    "Drowzee": 2,
    "Hypno": 1,
    "Mr Mime": 1,
    "Jynx": 1,
    "Mewtwo Lv53": 1,
    "Mew Lv23": 1,
    "Clefairy": 1,
    "Clefable": 1,
    "Snorlax": 1,
    "Bill": 2,
    "Pokemon Traver": 1,
    "Pokemon Breeder": 1,
    "Professor Oak": 2,
    "Switch": 2,
    "Devolution Spray": 1,
    "PlusPower": 2,
    "Pokemon Center": 1,
    "Psychic Energy": 25
}

dream_eater_haunter = {
    "Zubat": 3,
    "Golbat": 2,
    "Gastly Lv8": 4,
    "Haunter Lv17": 1,
    "Haunter Lv22": 2,
    "Gengar": 2,
    "Drowzee": 3,
    "Hypno": 2,
    "Jifflypuff Lv14": 2,
    "Meowth Lv15": 2,
    "Bill": 2,
    "Professor Oak": 2,
    "Switch": 2,
    "Computer Search": 1,
    "Super Energy Retrieval": 1,
    "Energy Retrieval": 2,
    "Revive": 3,
    "Grass Energy": 7,
    "Psychic Energy": 17
}

scavenging_slowbro = {
    "Slowpoke Lv18": 4,
    "Slowbro": 3,
    "Jynx": 3,
    "Mewtwo Lv53": 2,
    "Mew Lv23": 2,
    "Jigglypuff Lv13": 2,
    "Jigglypuff Lv14": 2,
    "Eevee": 2,
    "Potion": 3,
    "Defender": 2,
    "Energy Retrieval": 2,
    "PlusPower": 2,
    "Energy Removal": 3,
    "Recycle": 4,
    "Psychic Energy": 23
}

strange_power = {
    "Slowpoke Lv9": 3,
    "Slowbro": 2,
    "Drowzee": 4,
    "Hypno": 3,
    "Mr Mime": 2,
    "Jynx": 2,
    "Mew Lv8": 1,
    "Mew Lv23": 2,
    "Lickitung": 2,
    "Snorlax": 1,
    "Pokemon Trader": 2,
    "Energy Retrieval": 2,
    "Energy Removal": 2,
    "Super Energy Removal": 1,
    "PlusPower": 2,
    "Ite Finder": 1,
    "Gust of Wind": 1,
    "Full Heal": 1,
    "Double Colorless Energy": 1,
    "Psychic Energy": 25
}

strange_psyshock = {
    "Abra": 4,
    "Kadabra": 3,
    "Alakazam": 2,
    "Mr Mime": 2,
    "Chansey": 3,
    "Kangaskhan": 3,
    "Snorlax": 2,
    "Professor Oak": 2,
    "Pokemon Center": 2,
    "Energy Removal": 3,
    "Gust of Wind": 3,
    "Scoop Up": 4,
    "Switch": 4,
    "Gambler": 1,
    "Psychic Energy": 22
}

