from BaseClasses import ItemClassification


class ItemData:
    def __init__(self, item_id, classification, groups):
        self.groups = groups
        self.classification = classification
        self.id = None if item_id is None else item_id + 17000000000

    def advancement(self):
        return self.classification == ItemClassification.progression


item_table = {
    "Colosseum Pack": ItemData(1, ItemClassification.progression, ["Pack"]),
    "Laboratory Pack": ItemData(2, ItemClassification.progression, ["Pack"]),
    "Mystery Pack": ItemData(3, ItemClassification.progression, ["Pack"]),
    "Evolution Pack": ItemData(4, ItemClassification.progression, ["Pack"]),
    "Promo Arcanine": ItemData(5, ItemClassification.progression, ["Pack"]),
    "Promo Moltres": ItemData(6, ItemClassification.progression, ["Pack"]),
    "Promo Articuno": ItemData(7, ItemClassification.progression, ["Pack"]),
    "Promo Pikachu 1": ItemData(8, ItemClassification.progression, ["Pack"]),
    "Promo Pikachu 2": ItemData(9, ItemClassification.progression, ["Pack"]),
    "Promo Flying Pikachu": ItemData(10, ItemClassification.progression, ["Pack"]),
    "Promo Surfing Pikachu 1": ItemData(11, ItemClassification.progression, ["Pack"]),
    "Promo Surfing Pikachu 2": ItemData(12, ItemClassification.progression, ["Pack"]),
    "Promo Electabuzz": ItemData(13, ItemClassification.progression, ["Pack"]),
    "Promo Zapdos": ItemData(14, ItemClassification.progression, ["Pack"]),
    "Promo Slowpoke": ItemData(15, ItemClassification.progression, ["Pack"]),
    "Promo Mewtwo 1": ItemData(16, ItemClassification.progression, ["Pack"]),
    "Promo Mewtwo 2": ItemData(17, ItemClassification.progression, ["Pack"]),
    "Promo Mew 1": ItemData(18, ItemClassification.progression, ["Pack"]),
    "Promo Jigglypuff": ItemData(19, ItemClassification.progression, ["Pack"]),
    "Promo Dragonite": ItemData(20, ItemClassification.progression, ["Pack"]),
    "Promo Imakuni": ItemData(21, ItemClassification.progression, ["Pack"]),
    "Promo Super Energy Retrieval": ItemData(22, ItemClassification.progression, ["Pack"]),
    "Promo Venusaur": ItemData(23, ItemClassification.progression, ["Pack"]),
    "Promo Mew 2": ItemData(24, ItemClassification.progression, ["Pack"]),

    "Aerodactyl Pack": ItemData(25, ItemClassification.progression, ["Fighting", "Pack"]),
    "Dugtrio Pack": ItemData(26, ItemClassification.progression, ["Fighting", "Pack"]),
    "Golem Pack": ItemData(27, ItemClassification.progression, ["Fighting", "Pack"]),
    "Hitmonchan Pack": ItemData(28, ItemClassification.progression, ["Fighting", "Pack"]),
    "Hitmonlee Pack": ItemData(29, ItemClassification.progression, ["Fighting", "Pack"]),
    "Kabutops Pack": ItemData(30, ItemClassification.progression, ["Fighting", "Pack"]),
    "Machamp Pack": ItemData(31, ItemClassification.progression, ["Fighting", "Pack"]),
    "Marowak 1 Pack": ItemData(32, ItemClassification.progression, ["Fighting", "Pack"]),
    "Marowak 2 Pack": ItemData(33, ItemClassification.progression, ["Fighting", "Pack"]),
    "Onix Pack": ItemData(34, ItemClassification.progression, ["Fighting", "Pack"]),
    "Primeape Pack": ItemData(35, ItemClassification.progression, ["Fighting", "Pack"]),
    "Rhydon Pack": ItemData(36, ItemClassification.progression, ["Fighting", "Pack"]),
    "Sandslash Pack": ItemData(37, ItemClassification.progression, ["Fighting", "Pack"]),

    "Alakazam Pack": ItemData(38, ItemClassification.progression, ["Psychic", "Pack"]),
    "Gengar 1 Pack": ItemData(39, ItemClassification.progression, ["Psychic", "Pack"]),
    "Gengar 2 Pack": ItemData(40, ItemClassification.progression, ["Psychic", "Pack"]),
    "Hypno Pack": ItemData(41, ItemClassification.progression, ["Psychic", "Pack"]),
    "Jynx Pack": ItemData(42, ItemClassification.progression, ["Psychic", "Pack"]),
    "Mew 1 Pack": ItemData(43, ItemClassification.progression, ["Psychic", "Pack"]),
    "Mew 2 Pack": ItemData(44, ItemClassification.progression, ["Psychic", "Pack"]),
    "Mew 3 Pack": ItemData(45, ItemClassification.progression, ["Psychic", "Pack"]),
    "Mewtwo 1 Pack": ItemData(46, ItemClassification.progression, ["Psychic", "Pack"]),
    "Mewtwo 2 Pack": ItemData(47, ItemClassification.progression, ["Psychic", "Pack"]),
    "Mewtwo 3 Pack": ItemData(48, ItemClassification.progression, ["Psychic", "Pack"]),
    "Mr Mime Pack": ItemData(49, ItemClassification.progression, ["Psychic", "Pack"]),

    "Arbok Pack": ItemData(50, ItemClassification.progression, ["Grass", "Pack"]),
    "Beedrill Pack": ItemData(51, ItemClassification.progression, ["Grass", "Pack"]),
    "Butterfree Pack": ItemData(52, ItemClassification.progression, ["Grass", "Pack"]),
    "Exeggutor Pack": ItemData(53, ItemClassification.progression, ["Grass", "Pack"]),
    "Golbat Pack": ItemData(54, ItemClassification.progression, ["Grass", "Pack"]),
    "Muk Pack": ItemData(55, ItemClassification.progression, ["Grass", "Pack"]),
    "Nidoking Pack": ItemData(56, ItemClassification.progression, ["Grass", "Pack"]),
    "Nidoqueen Pack": ItemData(57, ItemClassification.progression, ["Grass", "Pack"]),
    "Parasect Pack": ItemData(58, ItemClassification.progression, ["Grass", "Pack"]),
    "Pinsir Pack": ItemData(59, ItemClassification.progression, ["Grass", "Pack"]),
    "Scyther Pack": ItemData(60, ItemClassification.progression, ["Grass", "Pack"]),
    "Tangela 1 Pack": ItemData(61, ItemClassification.progression, ["Grass", "Pack"]),
    "Tangela 2 Pack": ItemData(62, ItemClassification.progression, ["Grass", "Pack"]),
    "Venomoth Pack": ItemData(63, ItemClassification.progression, ["Grass", "Pack"]),
    "Venusaur 1 Pack": ItemData(64, ItemClassification.progression, ["Grass", "Pack"]),
    "Venusaur 2 Pack": ItemData(65, ItemClassification.progression, ["Grass", "Pack"]),
    "Victreebel Pack": ItemData(66, ItemClassification.progression, ["Grass", "Pack"]),
    "Vileplume Pack": ItemData(67, ItemClassification.progression, ["Grass", "Pack"]),
    "Weezing Pack": ItemData(68, ItemClassification.progression, ["Grass", "Pack"]),

    "Arcanine 1 Pack": ItemData(69, ItemClassification.progression, ["Fire", "Pack"]),
    "Arcanine 2 Pack": ItemData(70, ItemClassification.progression, ["Fire", "Pack"]),
    "Charizard Pack": ItemData(71, ItemClassification.progression, ["Fire", "Pack"]),
    "Flareon 1 Pack": ItemData(72, ItemClassification.progression, ["Fire", "Pack"]),
    "Flareon 2 Pack": ItemData(73, ItemClassification.progression, ["Fire", "Pack"]),
    "Magmar 1 Pack": ItemData(74, ItemClassification.progression, ["Fire", "Pack"]),
    "Magmar 2 Pack": ItemData(75, ItemClassification.progression, ["Fire", "Pack"]),
    "Moltres 1 Pack": ItemData(76, ItemClassification.progression, ["Fire", "Pack"]),
    "Moltres 2 Pack": ItemData(77, ItemClassification.progression, ["Fire", "Pack"]),
    "Ninetales 1 Pack": ItemData(78, ItemClassification.progression, ["Fire", "Pack"]),
    "Ninetales 2 Pack": ItemData(79, ItemClassification.progression, ["Fire", "Pack"]),
    "Rapidash Pack": ItemData(80, ItemClassification.progression, ["Fire", "Pack"]),

    "Articuno 1 Pack": ItemData(81, ItemClassification.progression, ["Water", "Pack"]),
    "Articuno 2 Pack": ItemData(82, ItemClassification.progression, ["Water", "Pack"]),
    "Blastoise Pack": ItemData(83, ItemClassification.progression, ["Water", "Pack"]),
    "Cloyster Pack": ItemData(84, ItemClassification.progression, ["Water", "Pack"]),
    "Dewgong Pack": ItemData(85, ItemClassification.progression, ["Water", "Pack"]),
    "Golduck Pack": ItemData(86, ItemClassification.progression, ["Water", "Pack"]),
    "Gyrados Pack": ItemData(87, ItemClassification.progression, ["Water", "Pack"]),
    "Kingler Pack": ItemData(88, ItemClassification.progression, ["Water", "Pack"]),
    "Lapras Pack": ItemData(89, ItemClassification.progression, ["Water", "Pack"]),
    "Omastar Pack": ItemData(90, ItemClassification.progression, ["Water", "Pack"]),
    "Poliwrath Pack": ItemData(91, ItemClassification.progression, ["Water", "Pack"]),
    "Seadra Pack": ItemData(92, ItemClassification.progression, ["Water", "Pack"]),
    "Seaking Pack": ItemData(93, ItemClassification.progression, ["Water", "Pack"]),
    "Slowbrow Pack": ItemData(94, ItemClassification.progression, ["Water", "Pack"]),
    "Slowpoke Promo Pack": ItemData(95, ItemClassification.progression, ["Pack"]),
    "Starmie Pack": ItemData(96, ItemClassification.progression, ["Water", "Pack"]),
    "Tentacruel Pack": ItemData(97, ItemClassification.progression, ["Water", "Pack"]),
    "Vaporeon 1 Pack": ItemData(98, ItemClassification.progression, ["Water", "Pack"]),
    "Vaporeon 2 Pack": ItemData(99, ItemClassification.progression, ["Water", "Pack"]),

    "Chansey Pack": ItemData(100, ItemClassification.progression, ["Normal", "Pack"]),
    "Clefable Pack": ItemData(101, ItemClassification.progression, ["Normal", "Pack"]),
    "Ditto Pack": ItemData(102, ItemClassification.progression, ["Normal", "Pack"]),
    "Dodrio Pack": ItemData(103, ItemClassification.progression, ["Normal", "Pack"]),
    "Dragonite 1 Pack": ItemData(104, ItemClassification.progression, ["Normal", "Pack"]),
    "Dragonite 2 Pack": ItemData(105, ItemClassification.progression, ["Normal", "Pack"]),
    "Farfetch'd Pack": ItemData(106, ItemClassification.progression, ["Normal", "Pack"]),
    "Fearow Pack": ItemData(107, ItemClassification.progression, ["Normal", "Pack"]),
    "Jigglypuff Promo Pack": ItemData(108, ItemClassification.progression, ["Normal", "Pack"]),
    "Kangaskhan Pack": ItemData(109, ItemClassification.progression, ["Normal", "Pack"]),
    "Lickitung Pack": ItemData(110, ItemClassification.progression, ["Normal", "Pack"]),
    "Persian 1 Pack": ItemData(111, ItemClassification.progression, ["Normal", "Pack"]),
    "Persian 2 Pack": ItemData(112, ItemClassification.progression, ["Normal", "Pack"]),
    "Pidgeot 1 Pack": ItemData(113, ItemClassification.progression, ["Normal", "Pack"]),
    "Pidgeot 2 Pack": ItemData(114, ItemClassification.progression, ["Normal", "Pack"]),
    "Porygon Pack": ItemData(115, ItemClassification.progression, ["Normal", "Pack"]),
    "Raticate Pack": ItemData(116, ItemClassification.progression, ["Normal", "Pack"]),
    "Snorlax Pack": ItemData(117, ItemClassification.progression, ["Normal", "Pack"]),
    "Tauros Pack": ItemData(118, ItemClassification.progression, ["Normal", "Pack"]),
    "Wigglytuff 1 Pack": ItemData(119, ItemClassification.progression, ["Normal", "Pack"]),
    "Wigglytuff 2 Pack": ItemData(120, ItemClassification.progression, ["Normal", "Pack"]),

    "Electabuzz 1 Pack": ItemData(121, ItemClassification.progression, ["Lightning", "Pack"]),
    "Electabuzz 2 Pack": ItemData(122, ItemClassification.progression, ["Lightning", "Pack"]),
    "Electrode 1 Pack": ItemData(123, ItemClassification.progression, ["Lightning", "Pack"]),
    "Electrode 2 Pack": ItemData(124, ItemClassification.progression, ["Lightning", "Pack"]),
    "Flying Pikachu Pack": ItemData(125, ItemClassification.progression, ["Lightning", "Pack"]),
    "Jolteon 1 Pack": ItemData(126, ItemClassification.progression, ["Lightning", "Pack"]),
    "Jolteon 2 Pack": ItemData(127, ItemClassification.progression, ["Lightning", "Pack"]),
    "Magneton 1 Pack": ItemData(128, ItemClassification.progression, ["Lightning", "Pack"]),
    "Magneton 2 Pack": ItemData(129, ItemClassification.progression, ["Lightning", "Pack"]),
    "Raichu 1 Pack": ItemData(130, ItemClassification.progression, ["Lightning", "Pack"]),
    "Raichu 2 Pack": ItemData(131, ItemClassification.progression, ["Lightning", "Pack"]),
    "Raichu 3 Pack": ItemData(132, ItemClassification.progression, ["Lightning", "Pack"]),
    "Raichu 4 Pack": ItemData(133, ItemClassification.progression, ["Lightning", "Pack"]),
    "Surfing Pikachu 1 Pack": ItemData(134, ItemClassification.progression, ["Lightning", "Pack"]),
    "Surfing Pikachu 2 Pack": ItemData(135, ItemClassification.progression, ["Lightning", "Pack"]),
    "Zapdos 1 Pack": ItemData(136, ItemClassification.progression, ["Lightning", "Pack"]),
    "Zapdos 2 Pack": ItemData(137, ItemClassification.progression, ["Lightning", "Pack"]),
    "Zapdos 3 Pack": ItemData(138, ItemClassification.progression, ["Lightning", "Pack"]),

    "Clefairy Doll Pack": ItemData(139, ItemClassification.progression, ["Trainer", "Pack"]),
    "Defender Pack": ItemData(140, ItemClassification.progression, ["Trainer", "Pack"]),
    "Devolution Spray Pack": ItemData(141, ItemClassification.progression, ["Trainer", "Pack"]),
    "Energy Removal Pack": ItemData(142, ItemClassification.progression, ["Trainer", "Pack"]),
    "Energy Retrieval Pack": ItemData(143, ItemClassification.progression, ["Trainer", "Pack"]),
    "Energy Search Pack": ItemData(144, ItemClassification.progression, ["Trainer", "Pack"]),
    "Full Heal Pack": ItemData(145, ItemClassification.progression, ["Trainer", "Pack"]),
    "Gambler Pack": ItemData(146, ItemClassification.progression, ["Trainer", "Pack"]),
    "Imakuni? Pack": ItemData(147, ItemClassification.progression, ["Trainer", "Pack"]),
    "Imposter Professor Oak Pack": ItemData(148, ItemClassification.progression, ["Trainer", "Pack"]),
    "Item Finder Pack": ItemData(149, ItemClassification.progression, ["Trainer", "Pack"]),
    "Lass Pack": ItemData(150, ItemClassification.progression, ["Trainer", "Pack"]),
    "Maintenance Pack": ItemData(151, ItemClassification.progression, ["Trainer", "Pack"]),
    "Mr Fuji Pack": ItemData(152, ItemClassification.progression, ["Trainer", "Pack"]),
    "Poke Ball Pack": ItemData(153, ItemClassification.progression, ["Trainer", "Pack"]),
    "Pokedex Pack": ItemData(154, ItemClassification.progression, ["Trainer", "Pack"]),
    "Pokemon Breeder Pack": ItemData(155, ItemClassification.progression, ["Trainer", "Pack"]),
    "Pokemon Center Pack": ItemData(156, ItemClassification.progression, ["Trainer", "Pack"]),
    "Pokemon Flute Pack": ItemData(157, ItemClassification.progression, ["Trainer", "Pack"]),
    "Pokemon Trader Pack": ItemData(158, ItemClassification.progression, ["Trainer", "Pack"]),
    "Potion Pack": ItemData(159, ItemClassification.progression, ["Trainer", "Pack"]),
    "Recycle Pack": ItemData(160, ItemClassification.progression, ["Trainer", "Pack"]),
    "Revive Pack": ItemData(161, ItemClassification.progression, ["Trainer", "Pack"]),
    "Super Energy Retrieval Pack": ItemData(162, ItemClassification.progression, ["Trainer", "Pack"]),
    "Super Potion Pack": ItemData(163, ItemClassification.progression, ["Trainer", "Pack"]),
    "Switch Pack": ItemData(164, ItemClassification.progression, ["Trainer", "Pack"]),

    "Computer Search Pack": ItemData(165, ItemClassification.progression, ["Trainer", "Pack"]),
    "Gust of Wind Pack": ItemData(166, ItemClassification.progression, ["Trainer", "Pack"]),
    "Pluspower Pack": ItemData(167, ItemClassification.progression, ["Trainer", "Pack"]),

    "Bill Pack": ItemData(168, ItemClassification.progression, ["Trainer", "Pack"]),
    "Professor Oak Pack": ItemData(169, ItemClassification.progression, ["Trainer", "Pack"]),
    "Super Energy Removal Pack": ItemData(170, ItemClassification.progression, ["Trainer", "Pack"]),
    "Double Colorless Energy Pack": ItemData(171, ItemClassification.useful, ["Energy", "Pack"]),

    "Grass Medal": ItemData(172, ItemClassification.progression, ["Medal"]),
    "Lightning Medal": ItemData(173, ItemClassification.progression, ["Medal"]),
    "Fire Medal": ItemData(174, ItemClassification.progression, ["Medal"]),
    "Fighting Medal": ItemData(175, ItemClassification.progression, ["Medal"]),
    "Rock Medal": ItemData(176, ItemClassification.progression, ["Medal"]),
    "Science Medal": ItemData(177, ItemClassification.progression, ["Medal"]),
    "Psychic Medal": ItemData(178, ItemClassification.progression, ["Medal"]),
    "Water Medal": ItemData(179, ItemClassification.progression, ["Medal"]),

    "Energy Pack": ItemData(180, ItemClassification.filler, ["Energy", "Pack"]),

    "Beat Sam": ItemData(None, ItemClassification.progression, []),
    "Beat Aaron LF": ItemData(None, ItemClassification.progression, []),
    "Beat Aaron WF": ItemData(None, ItemClassification.progression, []),
    "Beat Aaron GP": ItemData(None, ItemClassification.progression, []),
    "Beat Heather": ItemData(None, ItemClassification.progression, []),
    "Beat Kristin": ItemData(None, ItemClassification.progression, []),
    "Beat Brittany": ItemData(None, ItemClassification.progression, []),
    "Beat Nikki": ItemData(None, ItemClassification.progression, []),
    "Beat Joseph": ItemData(None, ItemClassification.progression, []),
    "Beat David": ItemData(None, ItemClassification.progression, []),
    "Beat Erik": ItemData(None, ItemClassification.progression, []),
    "Beat Rick": ItemData(None, ItemClassification.progression, []),
    "Beat Jonathan": ItemData(None, ItemClassification.progression, []),
    "Beat Adam": ItemData(None, ItemClassification.progression, []),
    "Beat John": ItemData(None, ItemClassification.progression, []),
    "Beat Ken": ItemData(None, ItemClassification.progression, []),
    "Beat Joshua": ItemData(None, ItemClassification.progression, []),
    "Beat Amanda": ItemData(None, ItemClassification.progression, []),
    "Beat Sara": ItemData(None, ItemClassification.progression, []),
    "Beat Amy": ItemData(None, ItemClassification.progression, []),
    "Beat Nicholas": ItemData(None, ItemClassification.progression, []),
    "Beat Brandon": ItemData(None, ItemClassification.progression, []),
    "Beat Jennifer": ItemData(None, ItemClassification.progression, []),
    "Beat Isaac": ItemData(None, ItemClassification.progression, []),
    "Beat Daniel": ItemData(None, ItemClassification.progression, []),
    "Beat Stephanie": ItemData(None, ItemClassification.progression, []),
    "Beat Robert": ItemData(None, ItemClassification.progression, []),
    "Beat Murray": ItemData(None, ItemClassification.progression, []),
    "Beat Ryan": ItemData(None, ItemClassification.progression, []),
    "Beat Andrew": ItemData(None, ItemClassification.progression, []),
    "Beat Matthew": ItemData(None, ItemClassification.progression, []),
    "Beat Gene": ItemData(None, ItemClassification.progression, []),
    "Beat Jessica": ItemData(None, ItemClassification.progression, []),
    "Beat Michael": ItemData(None, ItemClassification.progression, []),
    "Beat Chris": ItemData(None, ItemClassification.progression, []),
    "Beat Mitch": ItemData(None, ItemClassification.progression, []),
    "Beat Courtney": ItemData(None, ItemClassification.progression, []),
    "Beat Steve": ItemData(None, ItemClassification.progression, []),
    "Beat Jack": ItemData(None, ItemClassification.progression, []),
    "Beat Rod": ItemData(None, ItemClassification.progression, []),
    "Become Champion": ItemData(None, ItemClassification.progression, []),
    "Water Club Door": ItemData(None, ItemClassification.progression, []),
    "Fighting Club Door": ItemData(None, ItemClassification.progression, []),
    "Rock Club Door": ItemData(None, ItemClassification.progression, []),
    "Lightning Club Door": ItemData(None, ItemClassification.progression, []),
    "Psychic Club Door": ItemData(None, ItemClassification.progression, []),
    "Science Club Door": ItemData(None, ItemClassification.progression, []),
    "Fire Club Door": ItemData(None, ItemClassification.progression, []),
    "Grass Club Door": ItemData(None, ItemClassification.progression, []),
}

vanilla_items = [
    "Colosseum Pack", "Laboratory Pack", "Mystery Pack", "Evolution Pack", "Promo Arcanine", "Promo Moltres",
    "Promo Articuno", "Promo Pikachu 1", "Promo Pikachu 2", "Promo Flying Pikachu", "Promo Surfing Pikachu 1",
    "Promo Surfing Pikachu 2", "Promo Electabuzz", "Promo Zapdos", "Promo Slowpoke", "Promo Mewtwo 1", "Promo Mewtwo 2",
    "Promo Mew 1", "Promo Jigglypuff", "Promo Dragonite", "Promo Imakuni", "Promo Super Energy Retrieval",
    "Promo Venusaur", "Promo Mew 2",
]

packs = {
    "Fighting": ["Aerodactyl Pack",
                 "Dugtrio Pack",
                 "Golem Pack",
                 "Hitmonchan Pack",
                 "Hitmonlee Pack",
                 "Kabutops Pack",
                 "Machamp Pack",
                 "Marowak 1 Pack",
                 "Marowak 2 Pack",
                 "Onix Pack",
                 "Primeape Pack",
                 "Rhydon Pack",
                 "Sandslash Pack"],

    "Psychic": ["Alakazam Pack",
                "Gengar 1 Pack",
                "Gengar 2 Pack",
                "Hypno Pack",
                "Jynx Pack",
                "Mew 1 Pack",
                "Mew 2 Pack",
                "Mew 3 Pack",
                "Mewtwo 1 Pack",
                "Mewtwo 2 Pack",
                "Mewtwo 3 Pack",
                "Mr Mime Pack"],

    "Grass": ["Arbok Pack",
              "Beedrill Pack",
              "Butterfree Pack",
              "Exeggutor Pack",
              "Golbat Pack",
              "Muk Pack",
              "Nidoking Pack",
              "Nidoqueen Pack",
              "Parasect Pack",
              "Pinsir Pack",
              "Scyther Pack",
              "Tangela 1 Pack",
              "Tangela 2 Pack",
              "Venomoth Pack",
              "Venusaur 1 Pack",
              "Venusaur 2 Pack",
              "Victreebel Pack",
              "Vileplume Pack",
              "Weezing Pack"],

    "Fire": ["Arcanine 1 Pack",
             "Arcanine 2 Pack",
             "Charizard Pack",
             "Flareon 1 Pack",
             "Flareon 2 Pack",
             "Magmar 1 Pack",
             "Magmar 2 Pack",
             "Moltres 1 Pack",
             "Moltres 2 Pack",
             "Ninetales 1 Pack",
             "Ninetales 2 Pack",
             "Rapidash Pack"],

    "Water": ["Articuno 1 Pack",
              "Articuno 2 Pack",
              "Blastoise Pack",
              "Cloyster Pack",
              "Dewgong Pack",
              "Golduck Pack",
              "Gyrados Pack",
              "Kingler Pack",
              "Lapras Pack",
              "Omastar Pack",
              "Poliwrath Pack",
              "Seadra Pack",
              "Seaking Pack",
              "Slowbrow Pack",
              "Slowpoke Promo Pack",
              "Starmie Pack",
              "Tentacruel Pack",
              "Vaporeon 1 Pack",
              "Vaporeon 2 Pack", ],

    "Normal": ["Chansey Pack",
               "Clefable Pack",
               "Ditto Pack",
               "Dodrio Pack",
               "Dragonite 1 Pack",
               "Dragonite 2 Pack",
               "Farfetch'd Pack",
               "Fearow Pack",
               "Jigglypuff Promo Pack",
               "Kangaskhan Pack",
               "Lickitung Pack",
               "Persian 1 Pack",
               "Persian 2 Pack",
               "Pidgeot 1 Pack",
               "Pidgeot 2 Pack",
               "Porygon Pack",
               "Raticate Pack",
               "Snorlax Pack",
               "Tauros Pack",
               "Wigglytuff 1 Pack",
               "Wigglytuff 2 Pack"],

    "Lightning": ["Electabuzz 1 Pack",
                  "Electabuzz 2 Pack",
                  "Electrode 1 Pack",
                  "Electrode 2 Pack",
                  "Flying Pikachu Pack",
                  "Jolteon 1 Pack",
                  "Jolteon 2 Pack",
                  "Magneton 1 Pack",
                  "Magneton 2 Pack",
                  "Raichu 1 Pack",
                  "Raichu 2 Pack",
                  "Raichu 3 Pack",
                  "Raichu 4 Pack",
                  "Surfing Pikachu 1 Pack",
                  "Surfing Pikachu 2 Pack",
                  "Zapdos 1 Pack",
                  "Zapdos 2 Pack",
                  "Zapdos 3 Pack"],

    "Trainer": ["Clefairy Doll Pack",
                "Defender Pack",
                "Devolution Spray Pack",
                "Energy Removal Pack",
                "Energy Retrieval Pack",
                "Energy Search Pack",
                "Full Heal Pack",
                "Gambler Pack",
                "Imakuni? Pack",
                "Imposter Professor Oak Pack",
                "Item Finder Pack",
                "Lass Pack",
                "Maintenance Pack",
                "Mr Fuji Pack",
                "Poke Ball Pack",
                "Pokedex Pack",
                "Pokemon Breeder Pack",
                "Pokemon Center Pack",
                "Pokemon Flute Pack",
                "Pokemon Trader Pack",
                "Potion Pack",
                "Recycle Pack",
                "Revive Pack",
                "Super Energy Retrieval Pack",
                "Super Potion Pack",
                "Switch Pack",

                "Computer Search Pack",
                "Gust of Wind Pack",
                "Pluspower Pack",

                "Bill Pack",
                "Professor Oak Pack",
                "Super Energy Removal Pack",
                "Double Colorless Energy Pack"],
}

medals = [
    "Water Medal",
    "Fighting Medal",
    "Rock Medal",
    "Lightning Medal",
    "Psychic Medal",
    "Science Medal",
    "Fire Medal",
    "Grass Medal"
]

doors = [
    "Water Club Door",
    "Fighting Club Door",
    "Rock Club Door",
    "Lightning Club Door",
    "Psychic Club Door",
    "Science Club Door",
    "Fire Club Door",
    "Grass Club Door"
]

masters_talkable = [
    "Water Club Talkable",
    "Fighting Club Talkable",
    "Rock Club Talkable",
    "Lightning Club Talkable",
    "Psychic Club Talkable",
    "Science Club Talkable",
    "Fire Club Talkable",
    "Grass Club Talkable"
]

evoline_pack_list = [
    "Aerodactyl Pack",
    "Dugtrio Pack",
    "Golem Pack",
    "Hitmonchan Pack",
    "Hitmonlee Pack",
    "Kabutops Pack",
    "Machamp Pack",
    "Marowak 1 Pack",
    "Marowak 2 Pack",
    "Onix Pack",
    "Primeape Pack",
    "Rhydon Pack",
    "Sandslash Pack",

    "Alakazam Pack",
    "Gengar 1 Pack",
    "Gengar 2 Pack",
    "Hypno Pack",
    "Jynx Pack",
    "Mew 1 Pack",
    "Mew 2 Pack",
    "Mew 3 Pack",
    "Mewtwo 1 Pack",
    "Mewtwo 2 Pack",
    "Mewtwo 3 Pack",
    "Mr Mime Pack",

    "Arbok Pack",
    "Beedrill Pack",
    "Butterfree Pack",
    "Exeggutor Pack",
    "Golbat Pack",
    "Muk Pack",
    "Nidoking Pack",
    "Nidoqueen Pack",
    "Parasect Pack",
    "Pinsir Pack",
    "Scyther Pack",
    "Tangela 1 Pack",
    "Tangela 2 Pack",
    "Venomoth Pack",
    "Venusaur 1 Pack",
    "Venusaur 2 Pack",
    "Victreebel Pack",
    "Vileplume Pack",
    "Weezing Pack",

    "Arcanine 1 Pack",
    "Arcanine 2 Pack",
    "Charizard Pack",
    "Flareon 1 Pack",
    "Flareon 2 Pack",
    "Magmar 1 Pack",
    "Magmar 2 Pack",
    "Moltres 1 Pack",
    "Moltres 2 Pack",
    "Ninetales 1 Pack",
    "Ninetales 2 Pack",
    "Rapidash Pack",

    "Articuno 1 Pack",
    "Articuno 2 Pack",
    "Blastoise Pack",
    "Cloyster Pack",
    "Dewgong Pack",
    "Golduck Pack",
    "Gyrados Pack",
    "Kingler Pack",
    "Lapras Pack",
    "Omastar Pack",
    "Poliwrath Pack",
    "Seadra Pack",
    "Seaking Pack",
    "Slowbrow Pack",
    "Slowpoke Promo Pack",
    "Starmie Pack",
    "Tentacruel Pack",
    "Vaporeon 1 Pack",
    "Vaporeon 2 Pack",

    "Chansey Pack",
    "Clefable Pack",
    "Ditto Pack",
    "Dodrio Pack",
    "Dragonite 1 Pack",
    "Dragonite 2 Pack",
    "Farfetch'd Pack",
    "Fearow Pack",
    "Jigglypuff Promo Pack",
    "Kangaskhan Pack",
    "Lickitung Pack",
    "Persian 1 Pack",
    "Persian 2 Pack",
    "Pidgeot 1 Pack",
    "Pidgeot 2 Pack",
    "Porygon Pack",
    "Raticate Pack",
    "Snorlax Pack",
    "Tauros Pack",
    "Wigglytuff 1 Pack",
    "Wigglytuff 2 Pack",

    "Electabuzz 1 Pack",
    "Electabuzz 2 Pack",
    "Electrode 1 Pack",
    "Electrode 2 Pack",
    "Flying Pikachu Pack",
    "Jolteon 1 Pack",
    "Jolteon 2 Pack",
    "Magneton 1 Pack",
    "Magneton 2 Pack",
    "Raichu 1 Pack",
    "Raichu 2 Pack",
    "Raichu 3 Pack",
    "Raichu 4 Pack",
    "Surfing Pikachu 1 Pack",
    "Surfing Pikachu 2 Pack",
    "Zapdos 1 Pack",
    "Zapdos 2 Pack",
    "Zapdos 3 Pack",

    "Clefairy Doll Pack",
    "Defender Pack",
    "Devolution Spray Pack",
    "Energy Removal Pack",
    "Energy Retrieval Pack",
    "Energy Search Pack",
    "Full Heal Pack",
    "Gambler Pack",
    "Imakuni? Pack",
    "Imposter Professor Oak Pack",
    "Item Finder Pack",
    "Lass Pack",
    "Maintenance Pack",
    "Mr Fuji Pack",
    "Poke Ball Pack",
    "Pokedex Pack",
    "Pokemon Breeder Pack",
    "Pokemon Center Pack",
    "Pokemon Flute Pack",
    "Pokemon Trader Pack",
    "Potion Pack",
    "Recycle Pack",
    "Revive Pack",
    "Super Energy Retrieval Pack",
    "Super Potion Pack",
    "Switch Pack",

    "Computer Search Pack", "Computer Search Pack",
    "Gust of Wind Pack", "Gust of Wind Pack",
    "Pluspower Pack", "Pluspower Pack",

    "Bill Pack", "Bill Pack", "Bill Pack", "Bill Pack",
    "Professor Oak Pack", "Professor Oak Pack", "Professor Oak Pack", "Professor Oak Pack",
    "Super Energy Removal Pack", "Super Energy Removal Pack", "Super Energy Removal Pack", "Super Energy Removal Pack",
    "Double Colorless Energy Pack", "Double Colorless Energy Pack", "Double Colorless Energy Pack",
    "Double Colorless Energy Pack",
]

item_groups = {}
for item, data in item_table.items():
    for group in data.groups:
        item_groups[group] = item_groups.get(group, []) + [item]
