from worlds.generic.Rules import add_item_rule, add_rule, location_item_name
from .items import item_groups
from . import logic


def set_rules(multiworld, world, player):
    access_rules = {
        "Mason Laboratory Center Room - Sam Reward 1": lambda state: True,
        "Mason Laboratory Center Room - Sam Reward 2": lambda state: True,
        "Mason Laboratory Center Room - Beat Sam": lambda state: True,
        "Mason Laboratory Center Room - Sam Rematch Reward 1": lambda state: state.has("Beat Sam", player),
        "Mason Laboratory Center Room - Sam Rematch Reward 2": lambda state: state.has("Beat Sam", player),
        "Mason Laboratory Center Room - Aaron Reward 1": lambda state: True,
        "Mason Laboratory Center Room - Aaron Reward 2": lambda state: True,
        "Mason Laboratory Center Room - Beat Aaron": lambda state: True,
        "Mason Laboratory Center Room - Aaron Rematch Reward 1": lambda state: state.has("Beat Aaron", player),
        "Mason Laboratory Center Room - Aaron Rematch Reward 2": lambda state: state.has("Beat Aaron", player),
        # "Aaron LF Reward 1": lambda state: logic.has_type(state, world, player, "Rock",number=1) or logic.has_type(state, world, player, "Water",number=1),
        # "Aaron LF Reward 2": lambda state: logic.has_type(state, world, player, "Rock",number=1) or logic.has_type(state, world, player, "Water",number=1),
        # "Beat Aaron LF": lambda state: logic.has_type(state, world, player, "Rock",number=1) or logic.has_type(state, world, player, "Water",number=1),
        # "Aaron LF Rematch Reward 1": lambda state: (logic.has_type(state, world, player, "Rock",number=2) or logic.has_type(state, world, player, "Water",number=2)) and state.has("Beat Arron LF"),
        # "Aaron LF Rematch Reward 2": lambda state: (logic.has_type(state, world, player, "Rock",number=2) or logic.has_type(state, world, player, "Water",number=2)) and state.has("Beat Arron LF"),
        # "Aaron WF Reward 1": lambda state: logic.has_type(state, world, player, "Grass",number=2) or (logic.has_type(state, world, player, "Lightning",number=1) and logic.has_type(state, world, player, "Psychic",number=1)),
        # "Aaron WF Reward 2": lambda state: logic.has_type(state, world, player, "Grass",number=2) or (logic.has_type(state, world, player, "Lightning",number=1) and logic.has_type(state, world, player, "Psychic",number=1)),
        # "Beat Aaron WF": lambda state: logic.has_type(state, world, player, "Grass",number=2) and logic.has_type(state, world, player, "Lightning",number=1) and logic.has_type(state, world, player, "Psychic",number=1),
        # "Aaron WF Rematch Reward 1": lambda state: (logic.has_type(state, world, player, "Grass",number=2) or (logic.has_type(state, world, player, "Lightning",number=1) and logic.has_type(state, world, player, "Psychic",number=1))) and state.has("Beat Aaron WF"),
        # "Aaron WF Rematch Reward 2": lambda state: (logic.has_type(state, world, player, "Grass",number=2) or (logic.has_type(state, world, player, "Lightning",number=1) and logic.has_type(state, world, player, "Psychic",number=1))) and state.has("Beat Aaron WF"),
        # "Aaron GP Reward 1": lambda state: logic.has_type(state, world, player, "Fire",number=2) or logic.has_type(state, world, player, "Psychic",number=2),
        # "Aaron GP Reward 2": lambda state: logic.has_type(state, world, player, "Fire",number=2) or logic.has_type(state, world, player, "Psychic",number=2),
        # "Beat Aaron GP": lambda state: logic.has_type(state, world, player, "Fire",number=2) and logic.has_type(state, world, player, "Psychic",number=2),
        # "Aaron GP Rematch Reward 1": lambda state: (logic.has_type(state, world, player, "Fire",number=2) or logic.has_type(state, world, player, "Psychic",number=2)) and state.has("Beat Aaron GP"),
        # "Aaron GP Rematch Reward 2": lambda state: (logic.has_type(state, world, player, "Fire",number=2) or logic.has_type(state, world, player, "Psychic",number=2)) and state.has("Beat Aaron GP"),

        "Grass Club Main Hall - Heather Reward 1": lambda state: True,
        "Grass Club Main Hall - Heather Reward 2": lambda state: True,
        "Grass Club Main Hall - Beat Heather": lambda state: True,
        "Grass Club Main Hall - Heather Rematch Reward 1": lambda state: state.has("Beat Heather", player),
        "Grass Club Main Hall - Heather Rematch Reward 2": lambda state: state.has("Beat Heather", player),
        "Grass Club Main Hall - Kristin Reward 1": lambda state: logic.has_type(state, world, player, "Fire",number=8),
        "Grass Club Main Hall - Kristin Reward 2": lambda state: logic.has_type(state, world, player, "Fire",number=8),
        "Grass Club Main Hall - Beat Kristin": lambda state: logic.has_type(state, world, player, "Fire",number=8),
        "Grass Club Main Hall - Kristin Rematch Reward 1": lambda state: logic.has_type(state, world, player, "Fire",number=8) and state.has("Beat Kristin", player),
        "Grass Club Main Hall - Kristin Rematch Reward 2": lambda state: logic.has_type(state, world, player, "Fire",number=8) and state.has("Beat Kristin", player),
        "Grass Club Main Hall - Brittany Reward 1": lambda state: True,
        "Grass Club Main Hall - Brittany Reward 2": lambda state: True,
        "Grass Club Main Hall - Beat Brittany": lambda state: True,
        "Grass Club Main Hall - Brittany Rematch Reward 1": lambda state: state.has("Beat Brittany", player),
        "Grass Club Main Hall - Brittany Rematch Reward 2": lambda state: state.has("Beat Brittany", player),
        "Grass Club Main Hall - Nikki Reward 1": lambda state: logic.has_type(state, world, player, "Fire",number=16) and logic.club_leader_logic(state, world, player) and state.has("Grass Club Talkable", player),
        "Grass Club Main Hall - Nikki Reward 2": lambda state: logic.has_type(state, world, player, "Fire",number=16) and logic.club_leader_logic(state, world, player) and state.has("Grass Club Talkable", player),
        "Grass Club Main Hall - Beat Nikki": lambda state: logic.has_type(state, world, player, "Fire",number=16) and logic.club_leader_logic(state, world, player) and state.has("Grass Club Talkable", player),
        "Grass Club Main Hall - Nikki Rematch Reward 1": lambda state: logic.has_type(state, world, player, "Fire",number=16) and logic.club_leader_logic(state, world, player) and state.has("Grass Club Talkable", player) and state.has("Beat Nikki", player),
        "Grass Club Main Hall - Nikki Rematch Reward 2": lambda state: logic.has_type(state, world, player, "Fire",number=16) and logic.club_leader_logic(state, world, player) and state.has("Grass Club Talkable", player) and state.has("Beat Nikki", player),

        "Science Club Main Hall - Joseph Reward 1": lambda state: logic.has_type(state, world, player, "Lightning",number=4),
        "Science Club Main Hall - Joseph Reward 2": lambda state: logic.has_type(state, world, player, "Lightning",number=4),
        "Science Club Main Hall - Beat Joseph": lambda state: logic.has_type(state, world, player, "Lightning",number=4),
        "Science Club Main Hall - Joseph Rematch Reward 1": lambda state: logic.has_type(state, world, player, "Lightning",number=4) and state.has("Beat Joseph", player),
        "Science Club Main Hall - Joseph Rematch Reward 2": lambda state: logic.has_type(state, world, player, "Lightning",number=4) and state.has("Beat Joseph", player),
        "Science Club Main Hall - David Reward 1": lambda state: logic.has_type(state, world, player, "Psychic",number=4),
        "Science Club Main Hall - David Reward 2": lambda state: logic.has_type(state, world, player, "Psychic",number=4),
        "Science Club Main Hall - Beat David": lambda state: logic.has_type(state, world, player, "Psychic",number=4),
        "Science Club Main Hall - David Rematch Reward 1": lambda state: logic.has_type(state, world, player, "Psychic",number=4) and state.has("Beat David", player),
        "Science Club Main Hall - David Rematch Reward 2": lambda state: logic.has_type(state, world, player, "Psychic",number=4) and state.has("Beat David", player),
        "Science Club Main Hall - Erik Reward 1": lambda state: logic.has_type(state, world, player, "Psychic",number=4),
        "Science Club Main Hall - Erik Reward 2": lambda state: logic.has_type(state, world, player, "Psychic",number=4),
        "Science Club Main Hall - Beat Erik": lambda state: logic.has_type(state, world, player, "Psychic",number=4),
        "Science Club Main Hall - Erik Rematch Reward 1": lambda state: logic.has_type(state, world, player, "Psychic",number=4) and state.has("Beat Erik", player),
        "Science Club Main Hall - Erik Rematch Reward 2": lambda state: logic.has_type(state, world, player, "Psychic",number=4) and state.has("Beat Erik", player),
        "Science Club Main Hall - Rick Reward 1": lambda state: logic.has_type(state, world, player, "Psychic",number=16) and logic.club_leader_logic(state, world, player) and state.has("Science Club Talkable", player),
        "Science Club Main Hall - Rick Reward 2": lambda state: logic.has_type(state, world, player, "Psychic",number=16) and logic.club_leader_logic(state, world, player) and state.has("Science Club Talkable", player),
        "Science Club Main Hall - Beat Rick": lambda state: logic.has_type(state, world, player, "Psychic",number=16) and logic.club_leader_logic(state, world, player) and state.has("Science Club Talkable", player),
        "Science Club Main Hall - Rick Rematch Reward 1": lambda state: logic.has_type(state, world, player, "Psychic",number=16) and logic.club_leader_logic(state, world, player) and state.has("Science Club Talkable", player) and state.has("Beat Rick", player),
        "Science Club Main Hall - Rick Rematch Reward 2": lambda state: logic.has_type(state, world, player, "Psychic",number=16) and logic.club_leader_logic(state, world, player) and state.has("Science Club Talkable", player) and state.has("Beat Rick", player),

        "Fire Club Main Hall - Jonathan Reward 1": lambda state: logic.has_type(state, world, player, "Water",number=4),
        "Fire Club Main Hall - Jonathan Reward 2": lambda state: logic.has_type(state, world, player, "Water",number=4),
        "Beat Jonathan": lambda state: logic.has_type(state, world, player, "Water",number=4),
        "Fire Club Main Hall - Jonathan Rematch Reward 1": lambda state: logic.has_type(state, world, player, "Water",number=4) and state.has("Beat Jonathan", player),
        "Fire Club Main Hall - Jonathan Rematch Reward 2": lambda state: logic.has_type(state, world, player, "Water",number=4) and state.has("Beat Jonathan", player),
        "Fire Club Main Hall - Adam Reward 1": lambda state: logic.has_type(state, world, player, "Water",number=8),
        "Fire Club Main Hall - Adam Reward 2": lambda state: logic.has_type(state, world, player, "Water",number=8),
        "Fire Club Main Hall - Beat Adam": lambda state: logic.has_type(state, world, player, "Water",number=8),
        "Fire Club Main Hall - Adam Rematch Reward 1": lambda state: logic.has_type(state, world, player, "Water",number=8) and state.has("Beat Adam", player),
        "Fire Club Main Hall - Adam Rematch Reward 2": lambda state: logic.has_type(state, world, player, "Water",number=8) and state.has("Beat Adam", player),
        "Fire Club Main Hall - John Reward 1": lambda state: logic.has_type(state, world, player, "Water",number=4),
        "Fire Club Main Hall - John Reward 2": lambda state: logic.has_type(state, world, player, "Water",number=4),
        "Fire Club Main Hall - Beat John": lambda state: logic.has_type(state, world, player, "Water",number=4),
        "Fire Club Main Hall - John Rematch Reward 1": lambda state: logic.has_type(state, world, player, "Water",number=4) and state.has("Beat John", player),
        "Fire Club Main Hall - John Rematch Reward 2": lambda state: logic.has_type(state, world, player, "Water",number=4) and state.has("Beat John", player),
        "Fire Club Main Hall - Ken Reward 1": lambda state: logic.has_type(state, world, player, "Water",number=8) and logic.has_type(state, world, player, "Fighting",number=8) and logic.club_leader_logic(state, world, player) and state.has("Fire Club Talkable", player),
        "Fire Club Main Hall - Ken Reward 2": lambda state: logic.has_type(state, world, player, "Water",number=8) and logic.has_type(state, world, player, "Fighting",number=8) and logic.club_leader_logic(state, world, player) and state.has("Fire Club Talkable", player),
        "Fire Club Main Hall - Beat Ken": lambda state: logic.has_type(state, world, player, "Water",number=8) and logic.has_type(state, world, player, "Fighting",number=8) and logic.club_leader_logic(state, world, player) and state.has("Fire Club Talkable", player),
        "Fire Club Main Hall - Ken Rematch Reward 1": lambda state: logic.has_type(state, world, player, "Water",number=8) and logic.has_type(state, world, player, "Fighting",number=8) and logic.club_leader_logic(state, world, player) and state.has("Fire Club Talkable", player) and state.has("Beat Ken", player),
        "Fire Club Main Hall - Ken Rematch Reward 2": lambda state: logic.has_type(state, world, player, "Water",number=8) and logic.has_type(state, world, player, "Fighting",number=8) and logic.club_leader_logic(state, world, player) and state.has("Fire Club Talkable", player) and state.has("Beat Ken", player),

        "Water Club Main Hall - Sara Reward 1": lambda state: logic.has_type(state, world, player, "Lightning",number=4),
        "Water Club Main Hall - Sara Reward 2": lambda state: logic.has_type(state, world, player, "Lightning",number=4),
        "Water Club Main Hall - Beat Sara": lambda state: logic.has_type(state, world, player, "Lightning",number=4),
        "Water Club Main Hall - Sara Rematch Reward 1": lambda state: logic.has_type(state, world, player, "Lightning",number=4) and state.has("Beat Sara", player),
        "Water Club Main Hall - Sara Rematch Reward 2": lambda state: logic.has_type(state, world, player, "Lightning",number=4) and state.has("Beat Sara", player),
        "Water Club Main Hall - Amanda Reward 1": lambda state: True,
        "Water Club Main Hall - Amanda Reward 2": lambda state: True,
        "Water Club Main Hall - Beat Amanda": lambda state: True,
        "Water Club Main Hall - Amanda Rematch Reward 1": lambda state: state.has("Beat Amanda", player),
        "Water Club Main Hall - Amanda Rematch Reward 2": lambda state: state.has("Beat Amanda", player),
        "Water Club Main Hall - Joshua Reward 1": lambda state: logic.has_type(state, world, player, "Lightning",number=8) and state.has("Beat Sara", player) and state.has("Beat Amanda", player),
        "Water Club Main Hall - Joshua Reward 2": lambda state: logic.has_type(state, world, player, "Lightning",number=8) and state.has("Beat Sara", player) and state.has("Beat Amanda", player),
        "Water Club Main Hall - Beat Joshua": lambda state: logic.has_type(state, world, player, "Lightning",number=8) and state.has("Beat Sara", player) and state.has("Beat Amanda", player),
        "Water Club Main Hall - Joshua Rematch Reward 1": lambda state: logic.has_type(state, world, player, "Lightning",number=8) and state.has("Beat Sara", player) and state.has("Beat Amanda", player) and state.has("Beat Joshua", player),
        "Water Club Main Hall - Joshua Rematch Reward 2": lambda state: logic.has_type(state, world, player, "Lightning",number=8) and state.has("Beat Sara", player) and state.has("Beat Amanda", player) and state.has("Beat Joshua", player),
        "Water Club Main Hall - Amy Reward 1": lambda state: logic.has_type(state, world, player, "Lightning",number=16) and logic.club_leader_logic(state, world, player) and state.has("Water Club Talkable", player),
        "Water Club Main Hall - Amy Reward 2": lambda state: logic.has_type(state, world, player, "Lightning",number=16) and logic.club_leader_logic(state, world, player) and state.has("Water Club Talkable", player),
        "Water Club Main Hall - Beat Amy": lambda state: logic.has_type(state, world, player, "Lightning",number=16) and logic.club_leader_logic(state, world, player) and state.has("Water Club Talkable", player),
        "Water Club Main Hall - Amy Rematch Reward 1": lambda state: logic.has_type(state, world, player, "Lightning",number=16) and logic.club_leader_logic(state, world, player) and state.has("Water Club Talkable", player) and state.has("Beat Amy", player),
        "Water Club Main Hall - Amy Rematch Reward 2": lambda state: logic.has_type(state, world, player, "Lightning",number=16) and logic.club_leader_logic(state, world, player) and state.has("Water Club Talkable", player) and state.has("Beat Amy", player),

        "Lightning Club Main Hall - Nicholas Reward 1": lambda state: (logic.has_type(state, world, player, "Grass",number=4) or logic.has_type(state, world, player, "Psychic",number=4) or logic.has_type(state, world, player, "Fighting",number=4)),
        "Lightning Club Main Hall - Nicholas Reward 2": lambda state: (logic.has_type(state, world, player, "Grass",number=4) or logic.has_type(state, world, player, "Psychic",number=4) or logic.has_type(state, world, player, "Fighting",number=4)),
        "Lightning Club Main Hall - Beat Nicholas": lambda state: (logic.has_type(state, world, player, "Grass",number=4) or logic.has_type(state, world, player, "Psychic",number=4) or logic.has_type(state, world, player, "Fighting",number=4)),
        "Lightning Club Main Hall - Nicholas Rematch Reward 1": lambda state: (logic.has_type(state, world, player, "Grass",number=4) or logic.has_type(state, world, player, "Psychic",number=4) or logic.has_type(state, world, player, "Fighting",number=4)) and state.has("Beat Nicholas", player),
        "Lightning Club Main Hall - Nicholas Rematch Reward 2": lambda state: (logic.has_type(state, world, player, "Grass",number=4) or logic.has_type(state, world, player, "Psychic",number=4) or logic.has_type(state, world, player, "Fighting",number=4)) and state.has("Beat Nicholas", player),
        "Lightning Club Main Hall - Brandon Reward 1": lambda state: logic.has_type(state, world, player, "Fighting",number=8),
        "Lightning Club Main Hall - Brandon Reward 2": lambda state: logic.has_type(state, world, player, "Fighting",number=8),
        "Lightning Club Main Hall - Beat Brandon": lambda state: logic.has_type(state, world, player, "Fighting",number=8),
        "Lightning Club Main Hall - Brandon Rematch Reward 1": lambda state: logic.has_type(state, world, player, "Fighting",number=8) and state.has("Beat Brandon", player),
        "Lightning Club Main Hall - Brandon Rematch Reward 2": lambda state: logic.has_type(state, world, player, "Fighting",number=8) and state.has("Beat Brandon", player),
        "Lightning Club Main Hall - Jennifer Reward 1": lambda state: logic.has_type(state, world, player, "Fighting",number=8),
        "Lightning Club Main Hall - Jennifer Reward 2": lambda state: logic.has_type(state, world, player, "Fighting",number=8),
        "Lightning Club Main Hall - Beat Jennifer": lambda state: logic.has_type(state, world, player, "Fighting",number=8),
        "Lightning Club Main Hall - Jennifer Rematch Reward 1": lambda state: logic.has_type(state, world, player, "Fighting",number=8) and state.has("Beat Jennifer", player),
        "Lightning Club Main Hall - Jennifer Rematch Reward 2": lambda state: logic.has_type(state, world, player, "Fighting",number=8) and state.has("Beat Jennifer", player),
        "Lightning Club Main Hall - Isaac Reward 1": lambda state: logic.has_type(state, world, player, "Fighting",number=16) and logic.club_leader_logic(state, world, player) and state.has("Lightning Club Talkable", player),
        "Lightning Club Main Hall - Isaac Reward 2": lambda state: logic.has_type(state, world, player, "Fighting",number=16) and logic.club_leader_logic(state, world, player) and state.has("Lightning Club Talkable", player),
        "Lightning Club Main Hall - Beat Isaac": lambda state: logic.has_type(state, world, player, "Fighting",number=16) and logic.club_leader_logic(state, world, player) and state.has("Lightning Club Talkable", player),
        "Lightning Club Main Hall - Isaac Rematch Reward 1": lambda state: logic.has_type(state, world, player, "Fighting",number=16) and logic.club_leader_logic(state, world, player) and state.has("Lightning Club Talkable", player) and state.has("Beat Isaac", player),
        "Lightning Club Main Hall - Isaac Rematch Reward 2": lambda state: logic.has_type(state, world, player, "Fighting",number=16) and logic.club_leader_logic(state, world, player) and state.has("Lightning Club Talkable", player) and state.has("Beat Isaac", player),

        "Psychic Club Main Hall - Daniel Reward 1": lambda state: (logic.has_type(state, world, player, "Fire",number=4) or logic.has_type(state, world, player, "Psychic",number=4) or logic.has_type(state, world, player, "Fighting",number=4)),
        "Psychic Club Main Hall - Daniel Reward 2": lambda state: (logic.has_type(state, world, player, "Fire",number=4) or logic.has_type(state, world, player, "Psychic",number=4) or logic.has_type(state, world, player, "Fighting",number=4)),
        "Psychic Club Main Hall - Beat Daniel": lambda state: (logic.has_type(state, world, player, "Fire",number=4) or logic.has_type(state, world, player, "Psychic",number=4) or logic.has_type(state, world, player, "Fighting",number=4)),
        "Psychic Club Main Hall - Daniel Rematch Reward 1": lambda state: (logic.has_type(state, world, player, "Fire",number=4) or logic.has_type(state, world, player, "Psychic",number=4) or logic.has_type(state, world, player, "Fighting",number=4)) and state.has("Beat Daniel", player),
        "Psychic Club Main Hall - Daniel Rematch Reward 2": lambda state: (logic.has_type(state, world, player, "Fire",number=4) or logic.has_type(state, world, player, "Psychic",number=4) or logic.has_type(state, world, player, "Fighting",number=4)) and state.has("Beat Daniel", player),
        "Psychic Club Main Hall - Stephanie Reward 1": lambda state: logic.has_type(state, world, player, "Psychic",number=4),
        "Psychic Club Main Hall - Stephanie Reward 2": lambda state: logic.has_type(state, world, player, "Psychic",number=4),
        "Psychic Club Main Hall - Beat Stephanie": lambda state: logic.has_type(state, world, player, "Psychic",number=4),
        "Psychic Club Main Hall - Stephanie Rematch Reward 1": lambda state: logic.has_type(state, world, player, "Psychic",number=4) and state.has("Beat Stephanie", player),
        "Psychic Club Main Hall - Stephanie Rematch Reward 2": lambda state: logic.has_type(state, world, player, "Psychic",number=4)  and state.has("Beat Stephanie", player),
        "Psychic Club Main Hall - Robert Reward 1": lambda state: logic.has_type(state, world, player, "Psychic",number=4),
        "Psychic Club Main Hall - Robert Reward 2": lambda state: logic.has_type(state, world, player, "Psychic",number=4),
        "Psychic Club Main Hall - Beat Robert": lambda state: logic.has_type(state, world, player, "Psychic",number=4),
        "Psychic Club Main Hall - Robert Rematch Reward 1": lambda state: logic.has_type(state, world, player, "Psychic",number=4) and state.has("Beat Robert", player),
        "Psychic Club Main Hall - Robert Rematch Reward 2": lambda state: logic.has_type(state, world, player, "Psychic",number=4) and state.has("Beat Robert", player),
        "Psychic Club Main Hall - Murray Reward 1": lambda state: logic.has_type(state, world, player, "Psychic",number=8) and logic.has_type(state, world, player, "Fighting",number=8) and logic.club_leader_logic(state, world, player) and state.has("Psychic Club Talkable", player),
        "Psychic Club Main Hall - Murray Reward 2": lambda state: logic.has_type(state, world, player, "Psychic",number=8) and logic.has_type(state, world, player, "Fighting",number=8) and logic.club_leader_logic(state, world, player) and state.has("Psychic Club Talkable", player),
        "Psychic Club Main Hall - Beat Murray": lambda state: logic.has_type(state, world, player, "Psychic",number=8) and logic.has_type(state, world, player, "Fighting",number=8) and logic.club_leader_logic(state, world, player) and state.has("Psychic Club Talkable", player),
        "Psychic Club Main Hall - Murray Rematch Reward 1": lambda state: logic.has_type(state, world, player, "Psychic",number=8) and logic.has_type(state, world, player, "Fighting",number=8) and logic.club_leader_logic(state, world, player) and state.has("Psychic Club Talkable", player) and state.has("Beat Murray", player),
        "Psychic Club Main Hall - Murray Rematch Reward 2": lambda state: logic.has_type(state, world, player, "Psychic",number=8) and logic.has_type(state, world, player, "Fighting",number=8) and logic.club_leader_logic(state, world, player) and state.has("Psychic Club Talkable", player) and state.has("Beat Murray", player),

        "Rock Club Main Hall - Ryan Reward 1": lambda state: logic.has_type(state, world, player, "Grass",number=4),
        "Rock Club Main Hall - Ryan Reward 2": lambda state: logic.has_type(state, world, player, "Grass",number=4),
        "Rock Club Main Hall - Beat Ryan": lambda state: logic.has_type(state, world, player, "Grass",number=4),
        "Rock Club Main Hall - Ryan Rematch Reward 1": lambda state: logic.has_type(state, world, player, "Grass",number=4) and state.has("Beat Ryan", player),
        "Rock Club Main Hall - Ryan Rematch Reward 2": lambda state: logic.has_type(state, world, player, "Grass",number=4) and state.has("Beat Ryan", player),
        "Rock Club Main Hall - Andrew Reward 1": lambda state: logic.has_type(state, world, player, "Grass",number=4),
        "Rock Club Main Hall - Andrew Reward 2": lambda state: logic.has_type(state, world, player, "Grass",number=4),
        "Rock Club Main Hall - Beat Andrew": lambda state: logic.has_type(state, world, player, "Grass",number=4),
        "Rock Club Main Hall - Andrew Rematch Reward 1": lambda state: logic.has_type(state, world, player, "Grass",number=4) and state.has("Beat Andrew", player),
        "Rock Club Main Hall - Andrew Rematch Reward 2": lambda state: logic.has_type(state, world, player, "Grass",number=4) and state.has("Beat Andrew", player),
        "Rock Club Lounge - Matthew Reward 1": lambda state: logic.has_type(state, world, player, "Grass",number=8),
        "Rock Club Lounge -Matthew Reward 2": lambda state: logic.has_type(state, world, player, "Grass",number=8),
        "Rock Club Lounge -Beat Matthew": lambda state: logic.has_type(state, world, player, "Grass",number=8),
        "Rock Club Lounge -Matthew Rematch Reward 1": lambda state: logic.has_type(state, world, player, "Grass",number=8) and state.has("Beat Matthew", player),
        "Rock Club Lounge -Matthew Rematch Reward 2": lambda state: logic.has_type(state, world, player, "Grass",number=8) and state.has("Beat Matthew", player),
        "Rock Club Main Hall - Gene Reward 1": lambda state: logic.has_type(state, world, player, "Grass",number=16) and logic.club_leader_logic(state, world, player) and state.has("Rock Club Talkable", player),
        "Rock Club Main Hall - Gene Reward 2": lambda state: logic.has_type(state, world, player, "Grass",number=16) and logic.club_leader_logic(state, world, player) and state.has("Rock Club Talkable", player),
        "Rock Club Main Hall - Beat Gene": lambda state: logic.has_type(state, world, player, "Grass",number=16) and logic.club_leader_logic(state, world, player) and state.has("Rock Club Talkable", player),
        "Rock Club Main Hall - Gene Rematch Reward 1": lambda state: logic.has_type(state, world, player, "Grass",number=16) and logic.club_leader_logic(state, world, player) and state.has("Rock Club Talkable", player) and state.has("Beat Gene", player),
        "Rock Club Main Hall - Gene Rematch Reward 2": lambda state: logic.has_type(state, world, player, "Grass",number=16) and logic.club_leader_logic(state, world, player) and state.has("Rock Club Talkable", player) and state.has("Beat Gene", player),

        "Fire Club Lounge - Jessica Reward 1": lambda state: logic.has_type(state, world, player, "Psychic",number=4),
        "Fire Club Lounge - Jessica Reward 2": lambda state: logic.has_type(state, world, player, "Psychic",number=4),
        "Fire Club Lounge - Beat Jessica": lambda state: logic.has_type(state, world, player, "Psychic",number=4),
        "Fighting Club Main Hall - Jessica Rematch Reward 1": lambda state: logic.has_type(state, world, player, "Psychic",number=4) and state.has("Beat Jessica", player),
        "Fighting Club Main Hall - Jessica Rematch Reward 2": lambda state: logic.has_type(state, world, player, "Psychic",number=4) and state.has("Beat Jessica", player),
        "Grass Club Lobby - Michael Reward 1": lambda state: logic.has_type(state, world, player, "Psychic",number=4),
        "Grass Club Lobby - Michael Reward 2": lambda state: logic.has_type(state, world, player, "Psychic",number=4),
        "Grass Club Lobby - Beat Michael": lambda state: logic.has_type(state, world, player, "Psychic",number=4),
        "Fighting Club Main Hall - Michael Rematch Reward 1": lambda state: logic.has_type(state, world, player, "Psychic",number=4) and state.has("Beat Michael", player),
        "Fighting Club Main Hall - Michael Rematch Reward 2": lambda state: logic.has_type(state, world, player, "Psychic",number=4) and state.has("Beat Michael", player),
        "Rock Club Lounge - Chris Reward 1": lambda state: logic.has_type(state, world, player, "Psychic",number=4),
        "Rock Club Lounge - Chris Reward 2": lambda state: logic.has_type(state, world, player, "Psychic",number=4),
        "Rock Club Lounge - Beat Christ": lambda state: logic.has_type(state, world, player, "Psychic",number=4),
        "Fighting Club Main Hall - Chris Rematch Reward 1": lambda state: logic.has_type(state, world, player, "Psychic",number=4) and state.has("Beat Chris", player),
        "Fighting Club Main Hall - Chris Rematch Reward 2": lambda state: logic.has_type(state, world, player, "Psychic",number=4) and state.has("Beat Chris", player),
        "Fighting Club Main Hall - Mitch Reward 1": lambda state: logic.has_type(state, world, player, "Psychic",number=16) and logic.club_leader_logic(state, world, player) and state.has("Fighting Club Talkable", player),
        "Fighting Club Main Hall - Mitch Reward 2": lambda state: logic.has_type(state, world, player, "Psychic",number=16) and logic.club_leader_logic(state, world, player) and state.has("Fighting Club Talkable", player),
        "Fighting Club Main Hall - Beat Mitch": lambda state: logic.has_type(state, world, player, "Psychic",number=16) and logic.club_leader_logic(state, world, player) and state.has("Fighting Club Talkable", player),
        "Fighting Club Main Hall - Mitch Rematch Reward 1": lambda state: logic.has_type(state, world, player, "Psychic",number=16) and logic.club_leader_logic(state, world, player) and state.has("Fighting Club Talkable", player) and state.has("Beat Mitch", player),
        "Fighting Club Main Hall - Mitch Rematch Reward 2": lambda state: logic.has_type(state, world, player, "Psychic",number=16) and logic.club_leader_logic(state, world, player) and state.has("Fighting Club Talkable", player) and state.has("Beat Mitch", player),

        "Grass Club Main Hall - Grass Medal": lambda state: logic.has_type(state, world, player, "Fire",number=16) and logic.club_leader_logic(state, world, player) and state.has("Grass Club Talkable", player),
        "Science Club Main Hall - Science Medal": lambda state: logic.has_type(state, world, player, "Psychic",number=16) and logic.club_leader_logic(state, world, player) and state.has("Science Club Talkable", player),
        "Water Club Main Hall - Water Medal": lambda state: logic.has_type(state, world, player, "Lightning",number=16) and logic.club_leader_logic(state, world, player) and state.has("Water Club Talkable", player),
        "Fire Club Main Hall - Fire Medal": lambda state: logic.has_type(state, world, player, "Water",number=8) and logic.has_type(state, world, player, "Fighting",number=8) and logic.club_leader_logic(state, world, player) and state.has("Fire Club Talkable", player),
        "Lightning Club Main Hall - Lightning Medal": lambda state: logic.has_type(state, world, player, "Fighting",number=16) and logic.club_leader_logic(state, world, player) and state.has("Lightning Club Talkable", player),
        "Rock Club Main Hall - Rock Medal": lambda state: logic.has_type(state, world, player, "Grass",number=16) and logic.club_leader_logic(state, world, player) and state.has("Rock Club Talkable", player),
        "Psychic Club Main Hall - Psychic Medal": lambda state: logic.has_type(state, world, player, "Psychic",number=8) and logic.has_type(state, world, player, "Fighting",number=8) and logic.club_leader_logic(state, world, player) and state.has("Psychic Club Talkable", player),
        "Fighting Club Main Hall - Fighting Medal": lambda state: logic.has_type(state, world, player, "Psychic",number=16) and logic.club_leader_logic(state, world, player) and state.has("Fighting Club Talkable", player),

        "Fighting Club Lounge - Imakuni Reward 1": lambda state: True,
        "Science Club Lounge - Imakuni Reward 2": lambda state: True,
        "Lightning Club Lounge - Imakuni Rematch Reward 1": lambda state: True,
        "Water Club Lounge - Imakuni Rematch Reward 2": lambda state: True,

        "Rock Club Main Hall - Ronald Reward 1": lambda state: logic.has_type(state, world, player, "Water",number=8) and logic.has_type(state, world, player, "Lightning",number=16) and logic.has_type(state, world, player, "Grass",number=1) and logic.medal_count(state, world, player) >= 2 and logic.ronald_logic(state, world, player),
        "Fire Club Main Hall - Ronald Reward 2": lambda state: logic.has_type(state, world, player, "Water",number=8) and logic.has_type(state, world, player, "Lightning",number=16) and logic.has_type(state, world, player, "Grass",number=1) and logic.medal_count(state, world, player) >= 2 and logic.ronald_logic(state, world, player),
        "Grass Club Main Hall - Ronald Rematch Reward 1": lambda state: logic.has_type(state, world, player, "Psychic",number=16) and logic.has_type(state, world, player, "Fighting",number=16) and logic.medal_count(state, world, player) >= 5 and logic.ronald_logic(state, world, player),
        "Psychic Club Main Hall - Ronald Rematch Reward 2": lambda state: logic.has_type(state, world, player, "Psychic",number=16) and logic.has_type(state, world, player, "Fighting",number=16) and logic.medal_count(state, world, player) >= 5 and logic.ronald_logic(state, world, player),

        "Psychic Club Lounge - Promo Mewtwo Gift": lambda state: logic.has_item(state, world, player, world.options.psychic_club_trade.value),
        "Fighting Club Lounge - Promo Pikachu Trade (Fighting Club)": lambda state: logic.has_all_cards(state, world, player, world.options.fighting_club_trade.value),
        "Fire Club Lounge - Promo Slowpoke Trade": lambda state: logic.medal_count(state, world, player) >= world.options.fire_club_trade.value,
        "Lightning Club Lounge - Promo Electabuzz Trade": lambda state: logic.has_item(state, world, player, world.options.lightning_club_trade.value),
        "Water Club Lounge - Promo Arcanine Trade": lambda state: logic.has_item(state, world, player, world.options.water_club_trade.value),
        "Grass Club Lounge - Vileplume Trade": lambda state: logic.has_item(state, world, player, world.options.grass_club_trade_1.value),
        "Grass Club Lounge - Promo Pikachu Trade (Grass Club)": lambda state: logic.has_item(state, world, player, world.options.grass_club_trade_1.value) and logic.has_item(state, world, player, world.options.grass_club_trade_2.value),
        "Grass Club Lounge - Blastoise Trade": lambda state: logic.has_item(state, world, player, world.options.grass_club_trade_1.value) and logic.has_item(state, world, player, world.options.grass_club_trade_2.value) and logic.has_item(state, world, player, world.options.grass_club_trade_3.value),
        "Ishihara's House - Ishihara Trade 1": lambda state: logic.has_item(state, world, player, world.options.ishihara_trade_1.value),
        "Ishihara's House - Ishihara Trade 2": lambda state: logic.has_item(state, world, player, world.options.ishihara_trade_1.value) and logic.has_item(state, world, player, world.options.ishihara_trade_2.value),
        "Ishihara's House - Ishihara Trade 3": lambda state: logic.has_item(state, world, player, world.options.ishihara_trade_1.value) and logic.has_item(state, world, player, world.options.ishihara_trade_2.value) and logic.has_item(state, world, player, world.options.ishihara_trade_3.value),

        # Email logic
        "Mason Laboratory Center Room - Email 1": lambda state: logic.email_count(state, world, player) >= 1,
        "Mason Laboratory Center Room - Email 2": lambda state: logic.email_count(state, world, player) >= 2,
        "Mason Laboratory Center Room - Email 3": lambda state: logic.email_count(state, world, player) >= 3,
        "Mason Laboratory Center Room - Email 4": lambda state: logic.email_count(state, world, player) >= 4,
        "Mason Laboratory Center Room - Email 5": lambda state: logic.email_count(state, world, player) >= 5,
        "Mason Laboratory Center Room - Email 6": lambda state: logic.email_count(state, world, player) >= 6,
        "Mason Laboratory Center Room - Email 7": lambda state: logic.email_count(state, world, player) >= 7,
        "Mason Laboratory Center Room - Email 8": lambda state: logic.email_count(state, world, player) >= 8,
        "Mason Laboratory Center Room - Email 9": lambda state: logic.email_count(state, world, player) >= 9,
        "Mason Laboratory Center Room - Email 10": lambda state: logic.email_count(state, world, player) >= 10,
        "Mason Laboratory Center Room - Email 11": lambda state: logic.email_count(state, world, player) >= 11,
        "Mason Laboratory Center Room - Email 12": lambda state: logic.email_count(state, world, player) >= 12,
        "Mason Laboratory Center Room - Email 13": lambda state: logic.email_count(state, world, player) >= 13,
        "Mason Laboratory Center Room - Email 14": lambda state: logic.email_count(state, world, player) >= 14,
        "Mason Laboratory Center Room - Email 15": lambda state: logic.email_count(state, world, player) >= 15,

        "Water Club Lobby - Open Water Club Door": lambda state: logic.has_item(state, world, player,world.options.water_club_unlock.value),
        "Fire Club Lobby - Open Fire Club Door": lambda state: logic.has_item(state, world, player,world.options.fire_club_unlock.value),
        "Lightning Club Lobby - Open Lightning Club Door": lambda state: logic.has_item(state, world, player,world.options.lightning_club_unlock.value),
        "Science Club Lobby - Open Science Club Door": lambda state: logic.has_item(state, world, player,world.options.science_club_unlock.value),
        "Psychic Club Lobby - Open Psychic Club Door": lambda state: logic.has_item(state, world, player,world.options.psychic_club_unlock.value),
        "Grass Club Lobby - Open Grass Club Door": lambda state: logic.has_item(state, world, player,world.options.grass_club_unlock.value),
        "Rock Club Lobby - Open Rock Club Door": lambda state: logic.has_item(state, world, player,world.options.rock_club_unlock.value),
        "Fighting Club Lobby - Open Fighting Club Door": lambda state: logic.has_item(state, world, player,world.options.fighting_club_unlock.value),

        "Water Club Lobby - Water Club Talkable": lambda state: state.has("Open Water Club Door", player) and state.has("Beat Joshua", player),
        "Fighting Club Lobby - Fighting Club Talkable": lambda state: state.has("Open Fighting Club Door", player) and state.has("Beat Jessica", player) and state.has("Beat Michael", player) and state.has("Beat Chris", player),
        "Rock Club Lobby - Rock Club Talkable": lambda state: state.has("Open Rock Club Door", player),
        "Lightning Club Lobby - Lightning Club Talkable": lambda state: state.has("Open Lightning Club Door", player) and state.has("Beat Jennifer", player) and state.has("Beat Brandon", player) and state.has("Beat Nicholas", player),
        "Psychic Club Lobby - Psychic Club Talkable": lambda state: state.has("Open Psychic Club Door", player) and logic.medal_count(state, world, player) >= 4,
        "Science Club Lobby - Science Club Talkable": lambda state: state.has("Open Science Club Door", player) and state.has("Beat Joseph"),
        "Fire Club Lobby - Fire Club Talkable": lambda state: state.has("Open Fire Club Door", player) and logic.card_count(state, world, player) >= 700,
        "Grass Club Lobby - Grass Club Talkable": lambda state: state.has("Open Grass Club Door", player) and state.has("Beat Kristin", player) and state.has("Beat Heather", player) and state.has("Beat Brittany", player),

        "Pokemon Dome Main Hall - Beat Courtney": lambda state: logic.grand_master_logic(state, world, player) and logic.has_type(state, world, player, "Water", number=8),
        "Pokemon Dome Main Hall - Beat Steve": lambda state: state.has("Beat Courtney", player) and logic.has_type(state, world, player, "Fighting", number=8),
        "Pokemon Dome Main Hall - Beat Jack": lambda state: state.has("Beat Steve", player) and logic.has_type(state, world, player, "Lightning", number=8),
        "Pokemon Dome Main Hall - Beat Rod": lambda state: state.has("Beat Jack", player),
        "Pokemon Dome Main Hall - Become Champion": lambda state: state.has("Beat Rod", player),
    }

    for loc in multiworld.get_locations(player):
        if loc.name in access_rules:
            add_rule(loc, access_rules[loc.name])
