from worlds.generic.Rules import add_item_rule, add_rule, location_item_name
from .items import item_groups
from . import logic


def set_rules(multiworld, world, player):
    access_rules = {
        "Sam Reward 1": lambda state: True,
        "Sam Reward 2": lambda state: True,
        "Beat Sam": lambda state: True,
        "Sam Rematch Reward 1": lambda state: state.has("Beat Sam"),
        "Sam Rematch Reward 2": lambda state: state.has("Beat Sam"),
        "Aaron Reward 1": lambda state: True,
        "Aaron Reward 2": lambda state: True,
        "Beat Aaron": lambda state: True,
        "Aaron Rematch Reward 1": lambda state: state.has("Beat Arron"),
        "Aaron Rematch Reward 2": lambda state: state.has("Beat Arron"),
        # "Aaron LF Reward 1": lambda state: logic.has_type("Rock",number=1) or logic.has_type("Water",number=1),
        # "Aaron LF Reward 2": lambda state: logic.has_type("Rock",number=1) or logic.has_type("Water",number=1),
        # "Beat Aaron LF": lambda state: logic.has_type("Rock",number=1) or logic.has_type("Water",number=1),
        # "Aaron LF Rematch Reward 1": lambda state: (logic.has_type("Rock",number=2) or logic.has_type("Water",number=2)) and state.has("Beat Arron LF"),
        # "Aaron LF Rematch Reward 2": lambda state: (logic.has_type("Rock",number=2) or logic.has_type("Water",number=2)) and state.has("Beat Arron LF"),
        # "Aaron WF Reward 1": lambda state: logic.has_type("Grass",number=2) or (logic.has_type("Lightning",number=1) and logic.has_type("Psychic",number=1)),
        # "Aaron WF Reward 2": lambda state: logic.has_type("Grass",number=2) or (logic.has_type("Lightning",number=1) and logic.has_type("Psychic",number=1)),
        # "Beat Aaron WF": lambda state: logic.has_type("Grass",number=2) and logic.has_type("Lightning",number=1) and logic.has_type("Psychic",number=1),
        # "Aaron WF Rematch Reward 1": lambda state: (logic.has_type("Grass",number=2) or (logic.has_type("Lightning",number=1) and logic.has_type("Psychic",number=1))) and state.has("Beat Aaron WF"),
        # "Aaron WF Rematch Reward 2": lambda state: (logic.has_type("Grass",number=2) or (logic.has_type("Lightning",number=1) and logic.has_type("Psychic",number=1))) and state.has("Beat Aaron WF"),
        # "Aaron GP Reward 1": lambda state: logic.has_type("Fire",number=2) or logic.has_type("Psychic",number=2),
        # "Aaron GP Reward 2": lambda state: logic.has_type("Fire",number=2) or logic.has_type("Psychic",number=2),
        # "Beat Aaron GP": lambda state: logic.has_type("Fire",number=2) and logic.has_type("Psychic",number=2),
        # "Aaron GP Rematch Reward 1": lambda state: (logic.has_type("Fire",number=2) or logic.has_type("Psychic",number=2)) and state.has("Beat Aaron GP"),
        # "Aaron GP Rematch Reward 2": lambda state: (logic.has_type("Fire",number=2) or logic.has_type("Psychic",number=2)) and state.has("Beat Aaron GP"),

        "Heather Reward 1": lambda state: True,
        "Heather Reward 2": lambda state: True,
        "Beat Heather": lambda state: True,
        "Heather Rematch Reward 1": lambda state: state.has("Beat Heather"),
        "Heather Rematch Reward 2": lambda state: state.has("Beat Heather"),
        "Kristin Reward 1": lambda state: logic.has_type("Fire",number=2),
        "Kristin Reward 2": lambda state: logic.has_type("Fire",number=2),
        "Beat Kristin": lambda state: logic.has_type("Fire",number=2),
        "Kristin Rematch Reward 1": lambda state: logic.has_type("Fire",number=2) and state.has("Beat Kristin"),
        "Kristin Rematch Reward 2": lambda state: logic.has_type("Fire",number=2) and state.has("Beat Kristin"),
        "Brittany Reward 1": lambda state: True,
        "Brittany Reward 2": lambda state: True,
        "Beat Brittany": lambda state: True,
        "Brittany Rematch Reward 1": lambda state: state.has("Beat Brittany"),
        "Brittany Rematch Reward 2": lambda state: state.has("Beat Brittany"),
        "Nikki Reward 1": lambda state: logic.has_type("Fire",number=3) and logic.club_leader_logic() and state.has("Grass Club Talkable"),
        "Nikki Reward 2": lambda state: logic.has_type("Fire",number=3) and logic.club_leader_logic() and state.has("Grass Club Talkable"),
        "Beat Nikki": lambda state: logic.has_type("Fire",number=3) and logic.club_leader_logic() and state.has("Grass Club Talkable"),
        "Nikki Rematch Reward 1": lambda state: logic.has_type("Fire",number=3) and logic.club_leader_logic() and state.has("Grass Club Talkable") and state.has("Beat Nikki"),
        "Nikki Rematch Reward 2": lambda state: logic.has_type("Fire",number=3) and logic.club_leader_logic() and state.has("Grass Club Talkable") and state.has("Beat Nikki"),

        "Joseph Reward 1": lambda state: logic.has_type("Lightning",number=1),
        "Joseph Reward 2": lambda state: logic.has_type("Lightning",number=1),
        "Beat Joseph": lambda state: logic.has_type("Lightning",number=1),
        "Joseph Rematch Reward 1": lambda state: logic.has_type("Lightning",number=1) and state.has("Beat Joseph"),
        "Joseph Rematch Reward 2": lambda state: logic.has_type("Lightning",number=1) and state.has("Beat Joseph"),
        "David Reward 1": lambda state: logic.has_type("Psychic",number=1),
        "David Reward 2": lambda state: logic.has_type("Psychic",number=1),
        "Beat David": lambda state: logic.has_type("Psychic",number=1),
        "David Rematch Reward 1": lambda state: logic.has_type("Psychic",number=1) and state.has("Beat David"),
        "David Rematch Reward 2": lambda state: logic.has_type("Psychic",number=1) and state.has("Beat David"),
        "Erik Reward 1": lambda state: logic.has_type("Psychic",number=1),
        "Erik Reward 2": lambda state: logic.has_type("Psychic",number=1),
        "Beat Erik": lambda state: logic.has_type("Psychic",number=1),
        "Erik Rematch Reward 1": lambda state: logic.has_type("Psychic",number=1) and state.has("Beat Erik"),
        "Erik Rematch Reward 2": lambda state: logic.has_type("Psychic",number=1) and state.has("Beat Erik"),
        "Rick Reward 1": lambda state: logic.has_type("Psychic",number=3) and logic.club_leader_logic() and state.has("Science Club Talkable"),
        "Rick Reward 2": lambda state: logic.has_type("Psychic",number=3) and logic.club_leader_logic() and state.has("Science Club Talkable"),
        "Beat Rick": lambda state: logic.has_type("Psychic",number=3) and logic.club_leader_logic() and state.has("Science Club Talkable"),
        "Rick Rematch Reward 1": lambda state: logic.has_type("Psychic",number=3) and logic.club_leader_logic() and state.has("Science Club Talkable") and state.has("Beat Rick"),
        "Rick Rematch Reward 2": lambda state: logic.has_type("Psychic",number=3) and logic.club_leader_logic() and state.has("Science Club Talkable") and state.has("Beat Rick"),

        "Jonathan Reward 1": lambda state: logic.has_type("Water",number=1),
        "Jonathan Reward 2": lambda state: logic.has_type("Water",number=1),
        "Beat Jonathan": lambda state: logic.has_type("Water",number=1),
        "Jonathan Rematch Reward 1": lambda state: logic.has_type("Water",number=1) and state.has("Beat Jonathan"),
        "Jonathan Rematch Reward 2": lambda state: logic.has_type("Water",number=1) and state.has("Beat Jonathan"),
        "Adam Reward 1": lambda state: logic.has_type("Water",number=2),
        "Adam Reward 2": lambda state: logic.has_type("Water",number=2),
        "Beat Adam": lambda state: logic.has_type("Water",number=2),
        "Adam Rematch Reward 1": lambda state: logic.has_type("Water",number=2) and state.has("Beat Adam"),
        "Adam Rematch Reward 2": lambda state: logic.has_type("Water",number=2) and state.has("Beat Adam"),
        "John Reward 1": lambda state: logic.has_type("Water",number=1),
        "John Reward 2": lambda state: logic.has_type("Water",number=1),
        "Beat John": lambda state: logic.has_type("Water",number=1),
        "John Rematch Reward 1": lambda state: logic.has_type("Water",number=1) and state.has("Beat John"),
        "John Rematch Reward 2": lambda state: logic.has_type("Water",number=1) and state.has("Beat John"),
        "Ken Reward 1": lambda state: logic.has_type("Water",number=2) and logic.has_type("Fighting",number=2) and logic.club_leader_logic() and state.has("Fire Club Talkable"),
        "Ken Reward 2": lambda state: logic.has_type("Water",number=2) and logic.has_type("Fighting",number=2) and logic.club_leader_logic() and state.has("Fire Club Talkable"),
        "Beat Ken": lambda state: logic.has_type("Water",number=2) and logic.has_type("Fighting",number=2) and logic.club_leader_logic() and state.has("Fire Club Talkable"),
        "Ken Rematch Reward 1": lambda state: logic.has_type("Water",number=2) and logic.has_type("Fighting",number=2) and logic.club_leader_logic() and state.has("Fire Club Talkable") and state.has("Beat Ken"),
        "Ken Rematch Reward 2": lambda state: logic.has_type("Water",number=2) and logic.has_type("Fighting",number=2) and logic.club_leader_logic() and state.has("Fire Club Talkable") and state.has("Beat Ken"),

        "Sara Reward 1": lambda state: logic.has_type("Lightning",number=1),
        "Sara Reward 2": lambda state: logic.has_type("Lightning",number=1),
        "Beat Sara": lambda state: logic.has_type("Lightning",number=1),
        "Sara Rematch Reward 1": lambda state: logic.has_type("Lightning",number=1) and state.has("Beat Sara"),
        "Sara Rematch Reward 2": lambda state: logic.has_type("Lightning",number=1) and state.has("Beat Sara"),
        "Amanda Reward 1": lambda state: True,
        "Amanda Reward 2": lambda state: True,
        "Beat Amanda": lambda state: True,
        "Amanda Rematch Reward 1": lambda state: state.has("Beat Amanda"),
        "Amanda Rematch Reward 2": lambda state: state.has("Beat Amanda"),
        "Joshua Reward 1": lambda state: logic.has_type("Lightning",number=2) and state.has("Beat Sara") and state.has("Beat Amanda"),
        "Joshua Reward 2": lambda state: logic.has_type("Lightning",number=2) and state.has("Beat Sara") and state.has("Beat Amanda"),
        "Beat Joshua": lambda state: logic.has_type("Lightning",number=2) and state.has("Beat Sara") and state.has("Beat Amanda"),
        "Joshua Rematch Reward 1": lambda state: logic.has_type("Lightning",number=2) and state.has("Beat Sara") and state.has("Beat Amanda") and state.has("Beat Joshua"),
        "Joshua Rematch Reward 2": lambda state: logic.has_type("Lightning",number=2) and state.has("Beat Sara") and state.has("Beat Amanda") and state.has("Beat Joshua"),
        "Amy Reward 1": lambda state: logic.has_type("Lightning",number=3) and logic.club_leader_logic() and state.has("Water Club Talkable"),
        "Amy Reward 2": lambda state: logic.has_type("Lightning",number=3) and logic.club_leader_logic() and state.has("Water Club Talkable"),
        "Beat Amy": lambda state: logic.has_type("Lightning",number=3) and logic.club_leader_logic() and state.has("Water Club Talkable"),
        "Amy Rematch Reward 1": lambda state: logic.has_type("Lightning",number=3) and logic.club_leader_logic() and state.has("Water Club Talkable") and state.has("Beat Amy"),
        "Amy Rematch Reward 2": lambda state: logic.has_type("Lightning",number=3) and logic.club_leader_logic() and state.has("Water Club Talkable") and state.has("Beat Amy"),

        "Nicholas Reward 1": lambda state: (logic.has_type("Grass",number=1) or logic.has_type("Psychic",number=1) or logic.has_type("Fighting",number=1)),
        "Nicholas Reward 2": lambda state: (logic.has_type("Grass",number=1) or logic.has_type("Psychic",number=1) or logic.has_type("Fighting",number=1)),
        "Beat Nicholas": lambda state: (logic.has_type("Grass",number=1) or logic.has_type("Psychic",number=1) or logic.has_type("Fighting",number=1)),
        "Nicholas Rematch Reward 1": lambda state: (logic.has_type("Grass",number=1) or logic.has_type("Psychic",number=1) or logic.has_type("Fighting",number=1)) and state.has("Beat Nicholas"),
        "Nicholas Rematch Reward 2": lambda state: (logic.has_type("Grass",number=1) or logic.has_type("Psychic",number=1) or logic.has_type("Fighting",number=1)) and state.has("Beat Nicholas"),
        "Brandon Reward 1": lambda state: logic.has_type("Fighting",number=2),
        "Brandon Reward 2": lambda state: logic.has_type("Fighting",number=2),
        "Beat Brandon": lambda state: logic.has_type("Fighting",number=2),
        "Brandon Rematch Reward 1": lambda state: logic.has_type("Fighting",number=2) and state.has("Beat Brandon"),
        "Brandon Rematch Reward 2": lambda state: logic.has_type("Fighting",number=2) and state.has("Beat Brandon"),
        "Jennifer Reward 1": lambda state: logic.has_type("Fighting",number=2),
        "Jennifer Reward 2": lambda state: logic.has_type("Fighting",number=2),
        "Beat Jennifer": lambda state: logic.has_type("Fighting",number=2),
        "Jennifer Rematch Reward 1": lambda state: logic.has_type("Fighting",number=2) and state.has("Beat Jennifer"),
        "Jennifer Rematch Reward 2": lambda state: logic.has_type("Fighting",number=2) and state.has("Beat Jennifer"),
        "Isaac Reward 1": lambda state: logic.has_type("Fighting",number=3) and logic.club_leader_logic() and state.has("Lightning Club Talkable"),
        "Isaac Reward 2": lambda state: logic.has_type("Fighting",number=3) and logic.club_leader_logic() and state.has("Lightning Club Talkable"),
        "Beat Isaac": lambda state: logic.has_type("Fighting",number=3) and logic.club_leader_logic() and state.has("Lightning Club Talkable"),
        "Isaac Rematch Reward 1": lambda state: logic.has_type("Fighting",number=3) and logic.club_leader_logic() and state.has("Lightning Club Talkable") and state.has("Beat Isaac"),
        "Isaac Rematch Reward 2": lambda state: logic.has_type("Fighting",number=3) and logic.club_leader_logic() and state.has("Lightning Club Talkable") and state.has("Beat Isaac"),

        "Daniel Reward 1": lambda state: (logic.has_type("Fire",number=1) or logic.has_type("Psychic",number=1) or logic.has_type("Fighting",number=1)),
        "Daniel Reward 2": lambda state: (logic.has_type("Fire",number=1) or logic.has_type("Psychic",number=1) or logic.has_type("Fighting",number=1)),
        "Beat Daniel": lambda state: (logic.has_type("Fire",number=1) or logic.has_type("Psychic",number=1) or logic.has_type("Fighting",number=1)),
        "Daniel Rematch Reward 1": lambda state: (logic.has_type("Fire",number=1) or logic.has_type("Psychic",number=1) or logic.has_type("Fighting",number=1)) and state.has("Beat Daniel"),
        "Daniel Rematch Reward 2": lambda state: (logic.has_type("Fire",number=1) or logic.has_type("Psychic",number=1) or logic.has_type("Fighting",number=1)) and state.has("Beat Daniel"),
        "Stephanie Reward 1": lambda state: logic.has_type("Psychic",number=1),
        "Stephanie Reward 2": lambda state: logic.has_type("Psychic",number=1),
        "Beat Stephanie": lambda state: logic.has_type("Psychic",number=1),
        "Stephanie Rematch Reward 1": lambda state: logic.has_type("Psychic",number=1) and state.has("Beat Stephanie"),
        "Stephanie Rematch Reward 2": lambda state: logic.has_type("Psychic",number=1)  and state.has("Beat Stephanie"),
        "Robert Reward 1": lambda state: logic.has_type("Psychic",number=1),
        "Robert Reward 2": lambda state: logic.has_type("Psychic",number=1),
        "Beat Robert": lambda state: logic.has_type("Psychic",number=1),
        "Robert Rematch Reward 1": lambda state: logic.has_type("Psychic",number=1) and state.has("Beat Robert"),
        "Robert Rematch Reward 2": lambda state: logic.has_type("Psychic",number=1) and state.has("Beat Robert"),
        "Murray Reward 1": lambda state: logic.has_type("Psychic",number=2) and logic.has_type("Fighting",number=2) and logic.club_leader_logic() and state.has("Psychic Club Talkable"),
        "Murray Reward 2": lambda state: logic.has_type("Psychic",number=2) and logic.has_type("Fighting",number=2) and logic.club_leader_logic() and state.has("Psychic Club Talkable"),
        "Beat Murray": lambda state: logic.has_type("Psychic",number=2) and logic.has_type("Fighting",number=2) and logic.club_leader_logic() and state.has("Psychic Club Talkable"),
        "Murray Rematch Reward 1": lambda state: logic.has_type("Psychic",number=2) and logic.has_type("Fighting",number=2) and logic.club_leader_logic() and state.has("Psychic Club Talkable") and state.has("Beat Murray"),
        "Murray Rematch Reward 2": lambda state: logic.has_type("Psychic",number=2) and logic.has_type("Fighting",number=2) and logic.club_leader_logic() and state.has("Psychic Club Talkable") and state.has("Beat Murray"),

        "Ryan Reward 1": lambda state: logic.has_type("Grass",number=1),
        "Ryan Reward 2": lambda state: logic.has_type("Grass",number=1),
        "Beat Ryan": lambda state: logic.has_type("Grass",number=1),
        "Ryan Rematch Reward 1": lambda state: logic.has_type("Grass",number=1) and state.has("Beat Ryan"),
        "Ryan Rematch Reward 2": lambda state: logic.has_type("Grass",number=1) and state.has("Beat Ryan"),
        "Andrew Reward 1": lambda state: logic.has_type("Grass",number=1),
        "Andrew Reward 2": lambda state: logic.has_type("Grass",number=1),
        "Beat Andrew": lambda state: logic.has_type("Grass",number=1),
        "Andrew Rematch Reward 1": lambda state: logic.has_type("Grass",number=1) and state.has("Beat Andrew"),
        "Andrew Rematch Reward 2": lambda state: logic.has_type("Grass",number=1) and state.has("Beat Andrew"),
        "Matthew Reward 1": lambda state: logic.has_type("Grass",number=2),
        "Matthew Reward 2": lambda state: logic.has_type("Grass",number=2),
        "Beat Matthew": lambda state: logic.has_type("Grass",number=2),
        "Matthew Rematch Reward 1": lambda state: logic.has_type("Grass",number=2) and state.has("Beat Matthew"),
        "Matthew Rematch Reward 2": lambda state: logic.has_type("Grass",number=2) and state.has("Beat Matthew"),
        "Gene Reward 1": lambda state: logic.has_type("Grass",number=3) and logic.club_leader_logic() and state.has("Rock Club Talkable"),
        "Gene Reward 2": lambda state: logic.has_type("Grass",number=3) and logic.club_leader_logic() and state.has("Rock Club Talkable"),
        "Beat Gene": lambda state: logic.has_type("Grass",number=3) and logic.club_leader_logic() and state.has("Rock Club Talkable"),
        "Gene Rematch Reward 1": lambda state: logic.has_type("Grass",number=3) and logic.club_leader_logic() and state.has("Rock Club Talkable") and state.has("Beat Gene"),
        "Gene Rematch Reward 2": lambda state: logic.has_type("Grass",number=3) and logic.club_leader_logic() and state.has("Rock Club Talkable") and state.has("Beat Gene"),

        "Jessica Reward 1": lambda state: logic.has_type("Psychic",number=1),
        "Jessica Reward 2": lambda state: logic.has_type("Psychic",number=1),
        "Beat Jessica": lambda state: logic.has_type("Psychic",number=1),
        "Jessica Rematch Reward 1": lambda state: logic.has_type("Psychic",number=1) and state.has("Beat Jessica"),
        "Jessica Rematch Reward 2": lambda state: logic.has_type("Psychic",number=1) and state.has("Beat Jessica"),
        "Michael Reward 1": lambda state: logic.has_type("Psychic",number=1),
        "Michael Reward 2": lambda state: logic.has_type("Psychic",number=1),
        "Beat Michael": lambda state: logic.has_type("Psychic",number=1),
        "Michael Rematch Reward 1": lambda state: logic.has_type("Psychic",number=1) and state.has("Beat Michael"),
        "Michael Rematch Reward 2": lambda state: logic.has_type("Psychic",number=1) and state.has("Beat Michael"),
        "Chris Reward 1": lambda state: logic.has_type("Psychic",number=1),
        "Chris Reward 2": lambda state: logic.has_type("Psychic",number=1),
        "Beat Christ": lambda state: logic.has_type("Psychic",number=1),
        "Chris Rematch Reward 1": lambda state: logic.has_type("Psychic",number=1) and state.has("Beat Chris"),
        "Chris Rematch Reward 2": lambda state: logic.has_type("Psychic",number=1) and state.has("Beat Chris"),
        "Mitch Reward 1": lambda state: logic.has_type("Psychic",number=3) and logic.club_leader_logic() and state.has("Fighting Club Talkable"),
        "Mitch Reward 2": lambda state: logic.has_type("Psychic",number=3) and logic.club_leader_logic() and state.has("Fighting Club Talkable"),
        "Beat Mitch": lambda state: logic.has_type("Psychic",number=3) and logic.club_leader_logic() and state.has("Fighting Club Talkable"),
        "Mitch Rematch Reward 1": lambda state: logic.has_type("Psychic",number=3) and logic.club_leader_logic() and state.has("Fighting Club Talkable") and state.has("Beat Mitch"),
        "Mitch Rematch Reward 2": lambda state: logic.has_type("Psychic",number=3) and logic.club_leader_logic() and state.has("Fighting Club Talkable") and state.has("Beat Mitch"),

        "Grass Medal": lambda state: logic.has_type("Fire",number=3) and logic.club_leader_logic() and state.has("Grass Club Talkable"),
        "Science Medal": lambda state: logic.has_type("Psychic",number=3) and logic.club_leader_logic() and state.has("Science Club Talkable"),
        "Water Medal": lambda state: logic.has_type("Lightning",number=3) and logic.club_leader_logic() and state.has("Water Club Talkable"),
        "Fire Medal": lambda state: logic.has_type("Water",number=2) and logic.has_type("Fighting",number=2) and logic.club_leader_logic() and state.has("Fire Club Talkable"),
        "Lightning Medal": lambda state: logic.has_type("Fighting",number=3) and logic.club_leader_logic() and state.has("Lightning Club Talkable"),
        "Rock Medal": lambda state: logic.has_type("Grass",number=3) and logic.club_leader_logic() and state.has("Rock Club Talkable"),
        "Psychic Medal": lambda state: logic.has_type("Psychic",number=2) and logic.has_type("Fighting",number=2) and logic.club_leader_logic() and state.has("Psychic Club Talkable"),
        "Fighting Medal": lambda state: logic.has_type("Psychic",number=3) and logic.club_leader_logic() and state.has("Fighting Club Talkable"),

        "Imakuni Reward 1": lambda state: True,
        "Imakuni Reward 2": lambda state: True,
        "Imakuni Rematch Reward 1": lambda state: True,
        "Imakuni Rematch Reward 2": lambda state: True,

        "Ronald Reward 1": lambda state: logic.has_type("Water",number=2) and logic.has_type("Lightning",number=3) and logic.has_type("Grass",number=1) and logic.medal_count() >= 2 and logic.ronald_logic(),
        "Ronald Reward 2": lambda state: logic.has_type("Water",number=2) and logic.has_type("Lightning",number=3) and logic.has_type("Grass",number=1) and logic.medal_count() >= 2 and logic.ronald_logic(),
        "Ronald Rematch Reward 1": lambda state: logic.has_type("Psychic",number=3) and logic.has_type("Fighting",number=3) and logic.medal_count() >= 5 and logic.ronald_logic(),
        "Ronald Rematch Reward 2": lambda state: logic.has_type("Psychic",number=3) and logic.has_type("Fighting",number=3) and logic.medal_count() >= 5 and logic.ronald_logic(),

        "Promo Mewtwo Gift": lambda state: state.has(world.options.psychic_club_trade, player),
        "Promo Pikachu Trade (Fighting Club)": lambda state: state.has(world.options.fighting_club_trade, player),
        "Promo Slowpoke Trade": lambda state: state.has(world.options.fire_club_trade, player),
        "Promo Electabuzz Trade": lambda state: state.has(world.options.lightning_club_trade, player),
        "Promo Arcanine Trade": lambda state: state.has(world.options.water_club_trade, player),
        "Vileplume Trade": lambda state: state.has(world.options.grass_club_trade_1, player),
        "Promo Pikachu Trade (Grass Club)": lambda state: state.has(world.options.grass_club_trade_1, player) and state.has(world.options.grass_club_trade_2, player),
        "Blastoise Trade": lambda state: state.has(world.options.grass_club_trade_1, player) and state.has(world.options.grass_club_trade_2, player) and state.has(world.options.grass_club_trade_3, player),
        "Ishihara Trade 1": lambda state: state.has(world.options.ishihara_trade_1, player),
        "Ishihara Trade 2": lambda state: state.has(world.options.ishihara_trade_1, player) and state.has(world.options.ishihara_trade_2, player),
        "Ishihara Trade 3": lambda state: state.has(world.options.ishihara_trade_1, player) and state.has(world.options.ishihara_trade_2, player) and state.has(world.options.ishihara_trade_3, player),

        # Email logic
        "Email 1": lambda state: logic.email_count() >= 1,
        "Email 2": lambda state: logic.email_count() >= 2,
        "Email 3": lambda state: logic.email_count() >= 3,
        "Email 4": lambda state: logic.email_count() >= 4,
        "Email 5": lambda state: logic.email_count() >= 5,
        "Email 6": lambda state: logic.email_count() >= 6,
        "Email 7": lambda state: logic.email_count() >= 7,
        "Email 8": lambda state: logic.email_count() >= 8,
        "Email 9": lambda state: logic.email_count() >= 9,
        "Email 10": lambda state: logic.email_count() >= 10,
        "Email 11": lambda state: logic.email_count() >= 11,
        "Email 12": lambda state: logic.email_count() >= 12,
        "Email 13": lambda state: logic.email_count() >= 13,
        "Email 14": lambda state: logic.email_count() >= 14,
        "Email 15": lambda state: logic.email_count() >= 15,

        "Open Water Club Door": lambda state: state.has(world.options.water_club_door.value),
        "Open Fire Club Door": lambda state: state.has(world.options.fire_club_door.value),
        "Open Lightning Club Door": lambda state: state.has(world.options.lightning_club_door.value),
        "Open Science Club Door": lambda state: state.has(world.options.science_club_door.value),
        "Open Psychic Club Door": lambda state: state.has(world.options.psychic_club_door.value),
        "Open Grass Club Door": lambda state: state.has(world.options.grass_club_door.value),
        "Open Rock Club Door": lambda state: state.has(world.options.rock_club_door.value),
        "Open Fighting Club Door": lambda state: state.has(world.options.fighting_club_door.value),

        "Water Club Talkable": lambda state: state.has("Water Club Door") and state.has("Beat Joshua"),
        "Fighting Club Talkable": lambda state: state.has("Fighting Club Door") and state.has("Beat Jessica") and state.has("Beat Michael") and state.has("Beat Chris"),
        "Rock Club Talkable": lambda state: state.has("Rock Club Door"),
        "Lightning Club Talkable": lambda state: state.has("Lightning Club Door") and state.has("Beat Jennifer") and state.has("Beat Brandon") and state.has("Beat Nicholas"),
        "Psychic Club Talkable": lambda state: state.has("Psychic Club Door") and logic.medal_count() >= 4,
        "Science Club Talkable": lambda state: state.has("Science Club Door") and state.has("Beat Joseph"),
        "Fire Club Talkable": lambda state: state.has("Fire Club Door") and logic.card_count() >= 700,
        "Grass Club Talkable": lambda state: state.has("Grass Club Door") and state.has("Beat Kristin") and state.has("Beat Heather") and state.has("Beat Brittany") and state.has("Nikki at Ishihara's"),

        "Beat Courtney": lambda state: logic.grand_master_logic() and logic.has_type("Water", number=6),
        "Beat Steve": lambda state: state.has("Beat Courtney") and logic.has_type("Fighting", number=6),
        "Beat Jack": lambda state: state.has("Beat Steve") and logic.has_type("Lightning", number=6),
        "Beat Rod": lambda state: state.has("Beat Jack"),
        "Become Champion": lambda state: state.has("Beat Rod"),
    }
